// <auto-generated>
/*
 * Ais-Stream WebsocketObjects
 *
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Defines AisMessageTypes
    /// </summary>
    public enum AisMessageTypes
    {
        /// <summary>
        /// Enum PositionReport for value: PositionReport
        /// </summary>
        PositionReport = 1,

        /// <summary>
        /// Enum UnknownMessage for value: UnknownMessage
        /// </summary>
        UnknownMessage = 2,

        /// <summary>
        /// Enum AddressedSafetyMessage for value: AddressedSafetyMessage
        /// </summary>
        AddressedSafetyMessage = 3,

        /// <summary>
        /// Enum AddressedBinaryMessage for value: AddressedBinaryMessage
        /// </summary>
        AddressedBinaryMessage = 4,

        /// <summary>
        /// Enum AidsToNavigationReport for value: AidsToNavigationReport
        /// </summary>
        AidsToNavigationReport = 5,

        /// <summary>
        /// Enum AssignedModeCommand for value: AssignedModeCommand
        /// </summary>
        AssignedModeCommand = 6,

        /// <summary>
        /// Enum BaseStationReport for value: BaseStationReport
        /// </summary>
        BaseStationReport = 7,

        /// <summary>
        /// Enum BinaryAcknowledge for value: BinaryAcknowledge
        /// </summary>
        BinaryAcknowledge = 8,

        /// <summary>
        /// Enum BinaryBroadcastMessage for value: BinaryBroadcastMessage
        /// </summary>
        BinaryBroadcastMessage = 9,

        /// <summary>
        /// Enum ChannelManagement for value: ChannelManagement
        /// </summary>
        ChannelManagement = 10,

        /// <summary>
        /// Enum CoordinatedUTCInquiry for value: CoordinatedUTCInquiry
        /// </summary>
        CoordinatedUTCInquiry = 11,

        /// <summary>
        /// Enum DataLinkManagementMessage for value: DataLinkManagementMessage
        /// </summary>
        DataLinkManagementMessage = 12,

        /// <summary>
        /// Enum DataLinkManagementMessageData for value: DataLinkManagementMessageData
        /// </summary>
        DataLinkManagementMessageData = 13,

        /// <summary>
        /// Enum ExtendedClassBPositionReport for value: ExtendedClassBPositionReport
        /// </summary>
        ExtendedClassBPositionReport = 14,

        /// <summary>
        /// Enum GroupAssignmentCommand for value: GroupAssignmentCommand
        /// </summary>
        GroupAssignmentCommand = 15,

        /// <summary>
        /// Enum GnssBroadcastBinaryMessage for value: GnssBroadcastBinaryMessage
        /// </summary>
        GnssBroadcastBinaryMessage = 16,

        /// <summary>
        /// Enum Interrogation for value: Interrogation
        /// </summary>
        Interrogation = 17,

        /// <summary>
        /// Enum LongRangeAisBroadcastMessage for value: LongRangeAisBroadcastMessage
        /// </summary>
        LongRangeAisBroadcastMessage = 18,

        /// <summary>
        /// Enum MultiSlotBinaryMessage for value: MultiSlotBinaryMessage
        /// </summary>
        MultiSlotBinaryMessage = 19,

        /// <summary>
        /// Enum SafetyBroadcastMessage for value: SafetyBroadcastMessage
        /// </summary>
        SafetyBroadcastMessage = 20,

        /// <summary>
        /// Enum ShipStaticData for value: ShipStaticData
        /// </summary>
        ShipStaticData = 21,

        /// <summary>
        /// Enum SingleSlotBinaryMessage for value: SingleSlotBinaryMessage
        /// </summary>
        SingleSlotBinaryMessage = 22,

        /// <summary>
        /// Enum StandardClassBPositionReport for value: StandardClassBPositionReport
        /// </summary>
        StandardClassBPositionReport = 23,

        /// <summary>
        /// Enum StandardSearchAndRescueAircraftReport for value: StandardSearchAndRescueAircraftReport
        /// </summary>
        StandardSearchAndRescueAircraftReport = 24,

        /// <summary>
        /// Enum StaticDataReport for value: StaticDataReport
        /// </summary>
        StaticDataReport = 25
    }

    /// <summary>
    /// Converts <see cref="AisMessageTypes"/> to and from the JSON value
    /// </summary>
    public static class AisMessageTypesValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="AisMessageTypes"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static AisMessageTypes FromString(string value)
        {
            if (value.Equals("PositionReport"))
                return AisMessageTypes.PositionReport;

            if (value.Equals("UnknownMessage"))
                return AisMessageTypes.UnknownMessage;

            if (value.Equals("AddressedSafetyMessage"))
                return AisMessageTypes.AddressedSafetyMessage;

            if (value.Equals("AddressedBinaryMessage"))
                return AisMessageTypes.AddressedBinaryMessage;

            if (value.Equals("AidsToNavigationReport"))
                return AisMessageTypes.AidsToNavigationReport;

            if (value.Equals("AssignedModeCommand"))
                return AisMessageTypes.AssignedModeCommand;

            if (value.Equals("BaseStationReport"))
                return AisMessageTypes.BaseStationReport;

            if (value.Equals("BinaryAcknowledge"))
                return AisMessageTypes.BinaryAcknowledge;

            if (value.Equals("BinaryBroadcastMessage"))
                return AisMessageTypes.BinaryBroadcastMessage;

            if (value.Equals("ChannelManagement"))
                return AisMessageTypes.ChannelManagement;

            if (value.Equals("CoordinatedUTCInquiry"))
                return AisMessageTypes.CoordinatedUTCInquiry;

            if (value.Equals("DataLinkManagementMessage"))
                return AisMessageTypes.DataLinkManagementMessage;

            if (value.Equals("DataLinkManagementMessageData"))
                return AisMessageTypes.DataLinkManagementMessageData;

            if (value.Equals("ExtendedClassBPositionReport"))
                return AisMessageTypes.ExtendedClassBPositionReport;

            if (value.Equals("GroupAssignmentCommand"))
                return AisMessageTypes.GroupAssignmentCommand;

            if (value.Equals("GnssBroadcastBinaryMessage"))
                return AisMessageTypes.GnssBroadcastBinaryMessage;

            if (value.Equals("Interrogation"))
                return AisMessageTypes.Interrogation;

            if (value.Equals("LongRangeAisBroadcastMessage"))
                return AisMessageTypes.LongRangeAisBroadcastMessage;

            if (value.Equals("MultiSlotBinaryMessage"))
                return AisMessageTypes.MultiSlotBinaryMessage;

            if (value.Equals("SafetyBroadcastMessage"))
                return AisMessageTypes.SafetyBroadcastMessage;

            if (value.Equals("ShipStaticData"))
                return AisMessageTypes.ShipStaticData;

            if (value.Equals("SingleSlotBinaryMessage"))
                return AisMessageTypes.SingleSlotBinaryMessage;

            if (value.Equals("StandardClassBPositionReport"))
                return AisMessageTypes.StandardClassBPositionReport;

            if (value.Equals("StandardSearchAndRescueAircraftReport"))
                return AisMessageTypes.StandardSearchAndRescueAircraftReport;

            if (value.Equals("StaticDataReport"))
                return AisMessageTypes.StaticDataReport;

            throw new NotImplementedException($"Could not convert value to type AisMessageTypes: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="AisMessageTypes"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static AisMessageTypes? FromStringOrDefault(string value)
        {
            if (value.Equals("PositionReport"))
                return AisMessageTypes.PositionReport;

            if (value.Equals("UnknownMessage"))
                return AisMessageTypes.UnknownMessage;

            if (value.Equals("AddressedSafetyMessage"))
                return AisMessageTypes.AddressedSafetyMessage;

            if (value.Equals("AddressedBinaryMessage"))
                return AisMessageTypes.AddressedBinaryMessage;

            if (value.Equals("AidsToNavigationReport"))
                return AisMessageTypes.AidsToNavigationReport;

            if (value.Equals("AssignedModeCommand"))
                return AisMessageTypes.AssignedModeCommand;

            if (value.Equals("BaseStationReport"))
                return AisMessageTypes.BaseStationReport;

            if (value.Equals("BinaryAcknowledge"))
                return AisMessageTypes.BinaryAcknowledge;

            if (value.Equals("BinaryBroadcastMessage"))
                return AisMessageTypes.BinaryBroadcastMessage;

            if (value.Equals("ChannelManagement"))
                return AisMessageTypes.ChannelManagement;

            if (value.Equals("CoordinatedUTCInquiry"))
                return AisMessageTypes.CoordinatedUTCInquiry;

            if (value.Equals("DataLinkManagementMessage"))
                return AisMessageTypes.DataLinkManagementMessage;

            if (value.Equals("DataLinkManagementMessageData"))
                return AisMessageTypes.DataLinkManagementMessageData;

            if (value.Equals("ExtendedClassBPositionReport"))
                return AisMessageTypes.ExtendedClassBPositionReport;

            if (value.Equals("GroupAssignmentCommand"))
                return AisMessageTypes.GroupAssignmentCommand;

            if (value.Equals("GnssBroadcastBinaryMessage"))
                return AisMessageTypes.GnssBroadcastBinaryMessage;

            if (value.Equals("Interrogation"))
                return AisMessageTypes.Interrogation;

            if (value.Equals("LongRangeAisBroadcastMessage"))
                return AisMessageTypes.LongRangeAisBroadcastMessage;

            if (value.Equals("MultiSlotBinaryMessage"))
                return AisMessageTypes.MultiSlotBinaryMessage;

            if (value.Equals("SafetyBroadcastMessage"))
                return AisMessageTypes.SafetyBroadcastMessage;

            if (value.Equals("ShipStaticData"))
                return AisMessageTypes.ShipStaticData;

            if (value.Equals("SingleSlotBinaryMessage"))
                return AisMessageTypes.SingleSlotBinaryMessage;

            if (value.Equals("StandardClassBPositionReport"))
                return AisMessageTypes.StandardClassBPositionReport;

            if (value.Equals("StandardSearchAndRescueAircraftReport"))
                return AisMessageTypes.StandardSearchAndRescueAircraftReport;

            if (value.Equals("StaticDataReport"))
                return AisMessageTypes.StaticDataReport;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="AisMessageTypes"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(AisMessageTypes value)
        {
            if (value == AisMessageTypes.PositionReport)
                return "PositionReport";

            if (value == AisMessageTypes.UnknownMessage)
                return "UnknownMessage";

            if (value == AisMessageTypes.AddressedSafetyMessage)
                return "AddressedSafetyMessage";

            if (value == AisMessageTypes.AddressedBinaryMessage)
                return "AddressedBinaryMessage";

            if (value == AisMessageTypes.AidsToNavigationReport)
                return "AidsToNavigationReport";

            if (value == AisMessageTypes.AssignedModeCommand)
                return "AssignedModeCommand";

            if (value == AisMessageTypes.BaseStationReport)
                return "BaseStationReport";

            if (value == AisMessageTypes.BinaryAcknowledge)
                return "BinaryAcknowledge";

            if (value == AisMessageTypes.BinaryBroadcastMessage)
                return "BinaryBroadcastMessage";

            if (value == AisMessageTypes.ChannelManagement)
                return "ChannelManagement";

            if (value == AisMessageTypes.CoordinatedUTCInquiry)
                return "CoordinatedUTCInquiry";

            if (value == AisMessageTypes.DataLinkManagementMessage)
                return "DataLinkManagementMessage";

            if (value == AisMessageTypes.DataLinkManagementMessageData)
                return "DataLinkManagementMessageData";

            if (value == AisMessageTypes.ExtendedClassBPositionReport)
                return "ExtendedClassBPositionReport";

            if (value == AisMessageTypes.GroupAssignmentCommand)
                return "GroupAssignmentCommand";

            if (value == AisMessageTypes.GnssBroadcastBinaryMessage)
                return "GnssBroadcastBinaryMessage";

            if (value == AisMessageTypes.Interrogation)
                return "Interrogation";

            if (value == AisMessageTypes.LongRangeAisBroadcastMessage)
                return "LongRangeAisBroadcastMessage";

            if (value == AisMessageTypes.MultiSlotBinaryMessage)
                return "MultiSlotBinaryMessage";

            if (value == AisMessageTypes.SafetyBroadcastMessage)
                return "SafetyBroadcastMessage";

            if (value == AisMessageTypes.ShipStaticData)
                return "ShipStaticData";

            if (value == AisMessageTypes.SingleSlotBinaryMessage)
                return "SingleSlotBinaryMessage";

            if (value == AisMessageTypes.StandardClassBPositionReport)
                return "StandardClassBPositionReport";

            if (value == AisMessageTypes.StandardSearchAndRescueAircraftReport)
                return "StandardSearchAndRescueAircraftReport";

            if (value == AisMessageTypes.StaticDataReport)
                return "StaticDataReport";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AisMessageTypes"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class AisMessageTypesJsonConverter : JsonConverter<AisMessageTypes>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override AisMessageTypes Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            AisMessageTypes? result = rawValue == null
                ? null
                : AisMessageTypesValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the AisMessageTypes to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="aisMessageTypes"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, AisMessageTypes aisMessageTypes, JsonSerializerOptions options)
        {
            writer.WriteStringValue(AisMessageTypesValueConverter.ToJsonValue(aisMessageTypes).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AisMessageTypes"/>
    /// </summary>
    public class AisMessageTypesNullableJsonConverter : JsonConverter<AisMessageTypes?>
    {
        /// <summary>
        /// Returns a AisMessageTypes from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override AisMessageTypes? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            AisMessageTypes? result = rawValue == null
                ? null
                : AisMessageTypesValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the AisMessageTypes to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="aisMessageTypes"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, AisMessageTypes? aisMessageTypes, JsonSerializerOptions options)
        {
            writer.WriteStringValue(aisMessageTypes.HasValue ? AisMessageTypesValueConverter.ToJsonValue(aisMessageTypes.Value).ToString() : "null");
        }
    }
}
