// <auto-generated>
/*
 * Ais-Stream WebsocketObjects
 *
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// BinaryAcknowledge
    /// </summary>
    public partial class BinaryAcknowledge : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BinaryAcknowledge" /> class.
        /// </summary>
        /// <param name="messageID">messageID</param>
        /// <param name="repeatIndicator">repeatIndicator</param>
        /// <param name="userID">userID</param>
        /// <param name="valid">valid</param>
        /// <param name="spare">spare</param>
        /// <param name="destinations">destinations</param>
        [JsonConstructor]
        public BinaryAcknowledge(int messageID, int repeatIndicator, int userID, bool valid, int spare, BinaryAcknowledgeDestinations destinations)
        {
            MessageID = messageID;
            RepeatIndicator = repeatIndicator;
            UserID = userID;
            Valid = valid;
            Spare = spare;
            Destinations = destinations;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets MessageID
        /// </summary>
        [JsonPropertyName("MessageID")]
        public int MessageID { get; set; }

        /// <summary>
        /// Gets or Sets RepeatIndicator
        /// </summary>
        [JsonPropertyName("RepeatIndicator")]
        public int RepeatIndicator { get; set; }

        /// <summary>
        /// Gets or Sets UserID
        /// </summary>
        [JsonPropertyName("UserID")]
        public int UserID { get; set; }

        /// <summary>
        /// Gets or Sets Valid
        /// </summary>
        [JsonPropertyName("Valid")]
        public bool Valid { get; set; }

        /// <summary>
        /// Gets or Sets Spare
        /// </summary>
        [JsonPropertyName("Spare")]
        public int Spare { get; set; }

        /// <summary>
        /// Gets or Sets Destinations
        /// </summary>
        [JsonPropertyName("Destinations")]
        public BinaryAcknowledgeDestinations Destinations { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BinaryAcknowledge {\n");
            sb.Append("  MessageID: ").Append(MessageID).Append("\n");
            sb.Append("  RepeatIndicator: ").Append(RepeatIndicator).Append("\n");
            sb.Append("  UserID: ").Append(UserID).Append("\n");
            sb.Append("  Valid: ").Append(Valid).Append("\n");
            sb.Append("  Spare: ").Append(Spare).Append("\n");
            sb.Append("  Destinations: ").Append(Destinations).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BinaryAcknowledge" />
    /// </summary>
    public class BinaryAcknowledgeJsonConverter : JsonConverter<BinaryAcknowledge>
    {
        /// <summary>
        /// Deserializes json to <see cref="BinaryAcknowledge" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override BinaryAcknowledge Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> messageID = default;
            Option<int?> repeatIndicator = default;
            Option<int?> userID = default;
            Option<bool?> valid = default;
            Option<int?> spare = default;
            Option<BinaryAcknowledgeDestinations?> destinations = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "MessageID":
                            messageID = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "RepeatIndicator":
                            repeatIndicator = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "UserID":
                            userID = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "Valid":
                            valid = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "Spare":
                            spare = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "Destinations":
                            destinations = new Option<BinaryAcknowledgeDestinations?>(JsonSerializer.Deserialize<BinaryAcknowledgeDestinations>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!messageID.IsSet)
                throw new ArgumentException("Property is required for class BinaryAcknowledge.", nameof(messageID));

            if (!repeatIndicator.IsSet)
                throw new ArgumentException("Property is required for class BinaryAcknowledge.", nameof(repeatIndicator));

            if (!userID.IsSet)
                throw new ArgumentException("Property is required for class BinaryAcknowledge.", nameof(userID));

            if (!valid.IsSet)
                throw new ArgumentException("Property is required for class BinaryAcknowledge.", nameof(valid));

            if (!spare.IsSet)
                throw new ArgumentException("Property is required for class BinaryAcknowledge.", nameof(spare));

            if (!destinations.IsSet)
                throw new ArgumentException("Property is required for class BinaryAcknowledge.", nameof(destinations));

            if (messageID.IsSet && messageID.Value == null)
                throw new ArgumentNullException(nameof(messageID), "Property is not nullable for class BinaryAcknowledge.");

            if (repeatIndicator.IsSet && repeatIndicator.Value == null)
                throw new ArgumentNullException(nameof(repeatIndicator), "Property is not nullable for class BinaryAcknowledge.");

            if (userID.IsSet && userID.Value == null)
                throw new ArgumentNullException(nameof(userID), "Property is not nullable for class BinaryAcknowledge.");

            if (valid.IsSet && valid.Value == null)
                throw new ArgumentNullException(nameof(valid), "Property is not nullable for class BinaryAcknowledge.");

            if (spare.IsSet && spare.Value == null)
                throw new ArgumentNullException(nameof(spare), "Property is not nullable for class BinaryAcknowledge.");

            if (destinations.IsSet && destinations.Value == null)
                throw new ArgumentNullException(nameof(destinations), "Property is not nullable for class BinaryAcknowledge.");

            return new BinaryAcknowledge(messageID.Value!.Value!, repeatIndicator.Value!.Value!, userID.Value!.Value!, valid.Value!.Value!, spare.Value!.Value!, destinations.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="BinaryAcknowledge" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="binaryAcknowledge"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, BinaryAcknowledge binaryAcknowledge, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, binaryAcknowledge, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="BinaryAcknowledge" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="binaryAcknowledge"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, BinaryAcknowledge binaryAcknowledge, JsonSerializerOptions jsonSerializerOptions)
        {
            if (binaryAcknowledge.Destinations == null)
                throw new ArgumentNullException(nameof(binaryAcknowledge.Destinations), "Property is required for class BinaryAcknowledge.");

            writer.WriteNumber("MessageID", binaryAcknowledge.MessageID);

            writer.WriteNumber("RepeatIndicator", binaryAcknowledge.RepeatIndicator);

            writer.WriteNumber("UserID", binaryAcknowledge.UserID);

            writer.WriteBoolean("Valid", binaryAcknowledge.Valid);

            writer.WriteNumber("Spare", binaryAcknowledge.Spare);

            writer.WritePropertyName("Destinations");
            JsonSerializer.Serialize(writer, binaryAcknowledge.Destinations, jsonSerializerOptions);
        }
    }
}
