// <auto-generated>
/*
 * Ais-Stream WebsocketObjects
 *
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ChannelManagement
    /// </summary>
    public partial class ChannelManagement : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ChannelManagement" /> class.
        /// </summary>
        /// <param name="messageID">messageID</param>
        /// <param name="repeatIndicator">repeatIndicator</param>
        /// <param name="userID">userID</param>
        /// <param name="valid">valid</param>
        /// <param name="spare1">spare1</param>
        /// <param name="channelA">channelA</param>
        /// <param name="channelB">channelB</param>
        /// <param name="txRxMode">txRxMode</param>
        /// <param name="lowPower">lowPower</param>
        /// <param name="area">area</param>
        /// <param name="unicast">unicast</param>
        /// <param name="isAddressed">isAddressed</param>
        /// <param name="bwA">bwA</param>
        /// <param name="bwB">bwB</param>
        /// <param name="transitionalZoneSize">transitionalZoneSize</param>
        /// <param name="spare4">spare4</param>
        [JsonConstructor]
        public ChannelManagement(int messageID, int repeatIndicator, int userID, bool valid, int spare1, int channelA, int channelB, int txRxMode, bool lowPower, ChannelManagementArea area, ChannelManagementUnicast unicast, bool isAddressed, bool bwA, bool bwB, int transitionalZoneSize, int spare4)
        {
            MessageID = messageID;
            RepeatIndicator = repeatIndicator;
            UserID = userID;
            Valid = valid;
            Spare1 = spare1;
            ChannelA = channelA;
            ChannelB = channelB;
            TxRxMode = txRxMode;
            LowPower = lowPower;
            Area = area;
            Unicast = unicast;
            IsAddressed = isAddressed;
            BwA = bwA;
            BwB = bwB;
            TransitionalZoneSize = transitionalZoneSize;
            Spare4 = spare4;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets MessageID
        /// </summary>
        [JsonPropertyName("MessageID")]
        public int MessageID { get; set; }

        /// <summary>
        /// Gets or Sets RepeatIndicator
        /// </summary>
        [JsonPropertyName("RepeatIndicator")]
        public int RepeatIndicator { get; set; }

        /// <summary>
        /// Gets or Sets UserID
        /// </summary>
        [JsonPropertyName("UserID")]
        public int UserID { get; set; }

        /// <summary>
        /// Gets or Sets Valid
        /// </summary>
        [JsonPropertyName("Valid")]
        public bool Valid { get; set; }

        /// <summary>
        /// Gets or Sets Spare1
        /// </summary>
        [JsonPropertyName("Spare1")]
        public int Spare1 { get; set; }

        /// <summary>
        /// Gets or Sets ChannelA
        /// </summary>
        [JsonPropertyName("ChannelA")]
        public int ChannelA { get; set; }

        /// <summary>
        /// Gets or Sets ChannelB
        /// </summary>
        [JsonPropertyName("ChannelB")]
        public int ChannelB { get; set; }

        /// <summary>
        /// Gets or Sets TxRxMode
        /// </summary>
        [JsonPropertyName("TxRxMode")]
        public int TxRxMode { get; set; }

        /// <summary>
        /// Gets or Sets LowPower
        /// </summary>
        [JsonPropertyName("LowPower")]
        public bool LowPower { get; set; }

        /// <summary>
        /// Gets or Sets Area
        /// </summary>
        [JsonPropertyName("Area")]
        public ChannelManagementArea Area { get; set; }

        /// <summary>
        /// Gets or Sets Unicast
        /// </summary>
        [JsonPropertyName("Unicast")]
        public ChannelManagementUnicast Unicast { get; set; }

        /// <summary>
        /// Gets or Sets IsAddressed
        /// </summary>
        [JsonPropertyName("IsAddressed")]
        public bool IsAddressed { get; set; }

        /// <summary>
        /// Gets or Sets BwA
        /// </summary>
        [JsonPropertyName("BwA")]
        public bool BwA { get; set; }

        /// <summary>
        /// Gets or Sets BwB
        /// </summary>
        [JsonPropertyName("BwB")]
        public bool BwB { get; set; }

        /// <summary>
        /// Gets or Sets TransitionalZoneSize
        /// </summary>
        [JsonPropertyName("TransitionalZoneSize")]
        public int TransitionalZoneSize { get; set; }

        /// <summary>
        /// Gets or Sets Spare4
        /// </summary>
        [JsonPropertyName("Spare4")]
        public int Spare4 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ChannelManagement {\n");
            sb.Append("  MessageID: ").Append(MessageID).Append("\n");
            sb.Append("  RepeatIndicator: ").Append(RepeatIndicator).Append("\n");
            sb.Append("  UserID: ").Append(UserID).Append("\n");
            sb.Append("  Valid: ").Append(Valid).Append("\n");
            sb.Append("  Spare1: ").Append(Spare1).Append("\n");
            sb.Append("  ChannelA: ").Append(ChannelA).Append("\n");
            sb.Append("  ChannelB: ").Append(ChannelB).Append("\n");
            sb.Append("  TxRxMode: ").Append(TxRxMode).Append("\n");
            sb.Append("  LowPower: ").Append(LowPower).Append("\n");
            sb.Append("  Area: ").Append(Area).Append("\n");
            sb.Append("  Unicast: ").Append(Unicast).Append("\n");
            sb.Append("  IsAddressed: ").Append(IsAddressed).Append("\n");
            sb.Append("  BwA: ").Append(BwA).Append("\n");
            sb.Append("  BwB: ").Append(BwB).Append("\n");
            sb.Append("  TransitionalZoneSize: ").Append(TransitionalZoneSize).Append("\n");
            sb.Append("  Spare4: ").Append(Spare4).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ChannelManagement" />
    /// </summary>
    public class ChannelManagementJsonConverter : JsonConverter<ChannelManagement>
    {
        /// <summary>
        /// Deserializes json to <see cref="ChannelManagement" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ChannelManagement Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> messageID = default;
            Option<int?> repeatIndicator = default;
            Option<int?> userID = default;
            Option<bool?> valid = default;
            Option<int?> spare1 = default;
            Option<int?> channelA = default;
            Option<int?> channelB = default;
            Option<int?> txRxMode = default;
            Option<bool?> lowPower = default;
            Option<ChannelManagementArea?> area = default;
            Option<ChannelManagementUnicast?> unicast = default;
            Option<bool?> isAddressed = default;
            Option<bool?> bwA = default;
            Option<bool?> bwB = default;
            Option<int?> transitionalZoneSize = default;
            Option<int?> spare4 = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "MessageID":
                            messageID = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "RepeatIndicator":
                            repeatIndicator = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "UserID":
                            userID = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "Valid":
                            valid = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "Spare1":
                            spare1 = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "ChannelA":
                            channelA = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "ChannelB":
                            channelB = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "TxRxMode":
                            txRxMode = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "LowPower":
                            lowPower = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "Area":
                            area = new Option<ChannelManagementArea?>(JsonSerializer.Deserialize<ChannelManagementArea>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "Unicast":
                            unicast = new Option<ChannelManagementUnicast?>(JsonSerializer.Deserialize<ChannelManagementUnicast>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "IsAddressed":
                            isAddressed = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "BwA":
                            bwA = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "BwB":
                            bwB = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "TransitionalZoneSize":
                            transitionalZoneSize = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "Spare4":
                            spare4 = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!messageID.IsSet)
                throw new ArgumentException("Property is required for class ChannelManagement.", nameof(messageID));

            if (!repeatIndicator.IsSet)
                throw new ArgumentException("Property is required for class ChannelManagement.", nameof(repeatIndicator));

            if (!userID.IsSet)
                throw new ArgumentException("Property is required for class ChannelManagement.", nameof(userID));

            if (!valid.IsSet)
                throw new ArgumentException("Property is required for class ChannelManagement.", nameof(valid));

            if (!spare1.IsSet)
                throw new ArgumentException("Property is required for class ChannelManagement.", nameof(spare1));

            if (!channelA.IsSet)
                throw new ArgumentException("Property is required for class ChannelManagement.", nameof(channelA));

            if (!channelB.IsSet)
                throw new ArgumentException("Property is required for class ChannelManagement.", nameof(channelB));

            if (!txRxMode.IsSet)
                throw new ArgumentException("Property is required for class ChannelManagement.", nameof(txRxMode));

            if (!lowPower.IsSet)
                throw new ArgumentException("Property is required for class ChannelManagement.", nameof(lowPower));

            if (!area.IsSet)
                throw new ArgumentException("Property is required for class ChannelManagement.", nameof(area));

            if (!unicast.IsSet)
                throw new ArgumentException("Property is required for class ChannelManagement.", nameof(unicast));

            if (!isAddressed.IsSet)
                throw new ArgumentException("Property is required for class ChannelManagement.", nameof(isAddressed));

            if (!bwA.IsSet)
                throw new ArgumentException("Property is required for class ChannelManagement.", nameof(bwA));

            if (!bwB.IsSet)
                throw new ArgumentException("Property is required for class ChannelManagement.", nameof(bwB));

            if (!transitionalZoneSize.IsSet)
                throw new ArgumentException("Property is required for class ChannelManagement.", nameof(transitionalZoneSize));

            if (!spare4.IsSet)
                throw new ArgumentException("Property is required for class ChannelManagement.", nameof(spare4));

            if (messageID.IsSet && messageID.Value == null)
                throw new ArgumentNullException(nameof(messageID), "Property is not nullable for class ChannelManagement.");

            if (repeatIndicator.IsSet && repeatIndicator.Value == null)
                throw new ArgumentNullException(nameof(repeatIndicator), "Property is not nullable for class ChannelManagement.");

            if (userID.IsSet && userID.Value == null)
                throw new ArgumentNullException(nameof(userID), "Property is not nullable for class ChannelManagement.");

            if (valid.IsSet && valid.Value == null)
                throw new ArgumentNullException(nameof(valid), "Property is not nullable for class ChannelManagement.");

            if (spare1.IsSet && spare1.Value == null)
                throw new ArgumentNullException(nameof(spare1), "Property is not nullable for class ChannelManagement.");

            if (channelA.IsSet && channelA.Value == null)
                throw new ArgumentNullException(nameof(channelA), "Property is not nullable for class ChannelManagement.");

            if (channelB.IsSet && channelB.Value == null)
                throw new ArgumentNullException(nameof(channelB), "Property is not nullable for class ChannelManagement.");

            if (txRxMode.IsSet && txRxMode.Value == null)
                throw new ArgumentNullException(nameof(txRxMode), "Property is not nullable for class ChannelManagement.");

            if (lowPower.IsSet && lowPower.Value == null)
                throw new ArgumentNullException(nameof(lowPower), "Property is not nullable for class ChannelManagement.");

            if (area.IsSet && area.Value == null)
                throw new ArgumentNullException(nameof(area), "Property is not nullable for class ChannelManagement.");

            if (unicast.IsSet && unicast.Value == null)
                throw new ArgumentNullException(nameof(unicast), "Property is not nullable for class ChannelManagement.");

            if (isAddressed.IsSet && isAddressed.Value == null)
                throw new ArgumentNullException(nameof(isAddressed), "Property is not nullable for class ChannelManagement.");

            if (bwA.IsSet && bwA.Value == null)
                throw new ArgumentNullException(nameof(bwA), "Property is not nullable for class ChannelManagement.");

            if (bwB.IsSet && bwB.Value == null)
                throw new ArgumentNullException(nameof(bwB), "Property is not nullable for class ChannelManagement.");

            if (transitionalZoneSize.IsSet && transitionalZoneSize.Value == null)
                throw new ArgumentNullException(nameof(transitionalZoneSize), "Property is not nullable for class ChannelManagement.");

            if (spare4.IsSet && spare4.Value == null)
                throw new ArgumentNullException(nameof(spare4), "Property is not nullable for class ChannelManagement.");

            return new ChannelManagement(messageID.Value!.Value!, repeatIndicator.Value!.Value!, userID.Value!.Value!, valid.Value!.Value!, spare1.Value!.Value!, channelA.Value!.Value!, channelB.Value!.Value!, txRxMode.Value!.Value!, lowPower.Value!.Value!, area.Value!, unicast.Value!, isAddressed.Value!.Value!, bwA.Value!.Value!, bwB.Value!.Value!, transitionalZoneSize.Value!.Value!, spare4.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="ChannelManagement" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="channelManagement"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ChannelManagement channelManagement, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, channelManagement, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ChannelManagement" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="channelManagement"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ChannelManagement channelManagement, JsonSerializerOptions jsonSerializerOptions)
        {
            if (channelManagement.Area == null)
                throw new ArgumentNullException(nameof(channelManagement.Area), "Property is required for class ChannelManagement.");

            if (channelManagement.Unicast == null)
                throw new ArgumentNullException(nameof(channelManagement.Unicast), "Property is required for class ChannelManagement.");

            writer.WriteNumber("MessageID", channelManagement.MessageID);

            writer.WriteNumber("RepeatIndicator", channelManagement.RepeatIndicator);

            writer.WriteNumber("UserID", channelManagement.UserID);

            writer.WriteBoolean("Valid", channelManagement.Valid);

            writer.WriteNumber("Spare1", channelManagement.Spare1);

            writer.WriteNumber("ChannelA", channelManagement.ChannelA);

            writer.WriteNumber("ChannelB", channelManagement.ChannelB);

            writer.WriteNumber("TxRxMode", channelManagement.TxRxMode);

            writer.WriteBoolean("LowPower", channelManagement.LowPower);

            writer.WritePropertyName("Area");
            JsonSerializer.Serialize(writer, channelManagement.Area, jsonSerializerOptions);
            writer.WritePropertyName("Unicast");
            JsonSerializer.Serialize(writer, channelManagement.Unicast, jsonSerializerOptions);
            writer.WriteBoolean("IsAddressed", channelManagement.IsAddressed);

            writer.WriteBoolean("BwA", channelManagement.BwA);

            writer.WriteBoolean("BwB", channelManagement.BwB);

            writer.WriteNumber("TransitionalZoneSize", channelManagement.TransitionalZoneSize);

            writer.WriteNumber("Spare4", channelManagement.Spare4);
        }
    }
}
