// <auto-generated>
/*
 * Ais-Stream WebsocketObjects
 *
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// DataLinkManagementMessageData
    /// </summary>
    public partial class DataLinkManagementMessageData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DataLinkManagementMessageData" /> class.
        /// </summary>
        /// <param name="var0">var0</param>
        /// <param name="var1">var1</param>
        /// <param name="var2">var2</param>
        /// <param name="var3">var3</param>
        [JsonConstructor]
        public DataLinkManagementMessageData(DataLinkManagementMessageData0 var0, DataLinkManagementMessageData0 var1, DataLinkManagementMessageData0 var2, DataLinkManagementMessageData0 var3)
        {
            Var0 = var0;
            Var1 = var1;
            Var2 = var2;
            Var3 = var3;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Var0
        /// </summary>
        [JsonPropertyName("0")]
        public DataLinkManagementMessageData0 Var0 { get; set; }

        /// <summary>
        /// Gets or Sets Var1
        /// </summary>
        [JsonPropertyName("1")]
        public DataLinkManagementMessageData0 Var1 { get; set; }

        /// <summary>
        /// Gets or Sets Var2
        /// </summary>
        [JsonPropertyName("2")]
        public DataLinkManagementMessageData0 Var2 { get; set; }

        /// <summary>
        /// Gets or Sets Var3
        /// </summary>
        [JsonPropertyName("3")]
        public DataLinkManagementMessageData0 Var3 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DataLinkManagementMessageData {\n");
            sb.Append("  Var0: ").Append(Var0).Append("\n");
            sb.Append("  Var1: ").Append(Var1).Append("\n");
            sb.Append("  Var2: ").Append(Var2).Append("\n");
            sb.Append("  Var3: ").Append(Var3).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DataLinkManagementMessageData" />
    /// </summary>
    public class DataLinkManagementMessageDataJsonConverter : JsonConverter<DataLinkManagementMessageData>
    {
        /// <summary>
        /// Deserializes json to <see cref="DataLinkManagementMessageData" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DataLinkManagementMessageData Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<DataLinkManagementMessageData0?> var0 = default;
            Option<DataLinkManagementMessageData0?> var1 = default;
            Option<DataLinkManagementMessageData0?> var2 = default;
            Option<DataLinkManagementMessageData0?> var3 = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "0":
                            var0 = new Option<DataLinkManagementMessageData0?>(JsonSerializer.Deserialize<DataLinkManagementMessageData0>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "1":
                            var1 = new Option<DataLinkManagementMessageData0?>(JsonSerializer.Deserialize<DataLinkManagementMessageData0>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "2":
                            var2 = new Option<DataLinkManagementMessageData0?>(JsonSerializer.Deserialize<DataLinkManagementMessageData0>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "3":
                            var3 = new Option<DataLinkManagementMessageData0?>(JsonSerializer.Deserialize<DataLinkManagementMessageData0>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!var0.IsSet)
                throw new ArgumentException("Property is required for class DataLinkManagementMessageData.", nameof(var0));

            if (!var1.IsSet)
                throw new ArgumentException("Property is required for class DataLinkManagementMessageData.", nameof(var1));

            if (!var2.IsSet)
                throw new ArgumentException("Property is required for class DataLinkManagementMessageData.", nameof(var2));

            if (!var3.IsSet)
                throw new ArgumentException("Property is required for class DataLinkManagementMessageData.", nameof(var3));

            if (var0.IsSet && var0.Value == null)
                throw new ArgumentNullException(nameof(var0), "Property is not nullable for class DataLinkManagementMessageData.");

            if (var1.IsSet && var1.Value == null)
                throw new ArgumentNullException(nameof(var1), "Property is not nullable for class DataLinkManagementMessageData.");

            if (var2.IsSet && var2.Value == null)
                throw new ArgumentNullException(nameof(var2), "Property is not nullable for class DataLinkManagementMessageData.");

            if (var3.IsSet && var3.Value == null)
                throw new ArgumentNullException(nameof(var3), "Property is not nullable for class DataLinkManagementMessageData.");

            return new DataLinkManagementMessageData(var0.Value!, var1.Value!, var2.Value!, var3.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="DataLinkManagementMessageData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dataLinkManagementMessageData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, DataLinkManagementMessageData dataLinkManagementMessageData, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, dataLinkManagementMessageData, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DataLinkManagementMessageData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dataLinkManagementMessageData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, DataLinkManagementMessageData dataLinkManagementMessageData, JsonSerializerOptions jsonSerializerOptions)
        {
            if (dataLinkManagementMessageData.Var0 == null)
                throw new ArgumentNullException(nameof(dataLinkManagementMessageData.Var0), "Property is required for class DataLinkManagementMessageData.");

            if (dataLinkManagementMessageData.Var1 == null)
                throw new ArgumentNullException(nameof(dataLinkManagementMessageData.Var1), "Property is required for class DataLinkManagementMessageData.");

            if (dataLinkManagementMessageData.Var2 == null)
                throw new ArgumentNullException(nameof(dataLinkManagementMessageData.Var2), "Property is required for class DataLinkManagementMessageData.");

            if (dataLinkManagementMessageData.Var3 == null)
                throw new ArgumentNullException(nameof(dataLinkManagementMessageData.Var3), "Property is required for class DataLinkManagementMessageData.");

            writer.WritePropertyName("0");
            JsonSerializer.Serialize(writer, dataLinkManagementMessageData.Var0, jsonSerializerOptions);
            writer.WritePropertyName("1");
            JsonSerializer.Serialize(writer, dataLinkManagementMessageData.Var1, jsonSerializerOptions);
            writer.WritePropertyName("2");
            JsonSerializer.Serialize(writer, dataLinkManagementMessageData.Var2, jsonSerializerOptions);
            writer.WritePropertyName("3");
            JsonSerializer.Serialize(writer, dataLinkManagementMessageData.Var3, jsonSerializerOptions);
        }
    }
}
