// <auto-generated>
/*
 * Ais-Stream WebsocketObjects
 *
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// GroupAssignmentCommand
    /// </summary>
    public partial class GroupAssignmentCommand : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GroupAssignmentCommand" /> class.
        /// </summary>
        /// <param name="messageID">messageID</param>
        /// <param name="repeatIndicator">repeatIndicator</param>
        /// <param name="userID">userID</param>
        /// <param name="valid">valid</param>
        /// <param name="spare1">spare1</param>
        /// <param name="longitude1">longitude1</param>
        /// <param name="latitude1">latitude1</param>
        /// <param name="longitude2">longitude2</param>
        /// <param name="latitude2">latitude2</param>
        /// <param name="stationType">stationType</param>
        /// <param name="shipType">shipType</param>
        /// <param name="spare2">spare2</param>
        /// <param name="txRxMode">txRxMode</param>
        /// <param name="reportingInterval">reportingInterval</param>
        /// <param name="quietTime">quietTime</param>
        /// <param name="spare3">spare3</param>
        [JsonConstructor]
        public GroupAssignmentCommand(int messageID, int repeatIndicator, int userID, bool valid, int spare1, double longitude1, double latitude1, double longitude2, double latitude2, int stationType, int shipType, int spare2, int txRxMode, int reportingInterval, int quietTime, int spare3)
        {
            MessageID = messageID;
            RepeatIndicator = repeatIndicator;
            UserID = userID;
            Valid = valid;
            Spare1 = spare1;
            Longitude1 = longitude1;
            Latitude1 = latitude1;
            Longitude2 = longitude2;
            Latitude2 = latitude2;
            StationType = stationType;
            ShipType = shipType;
            Spare2 = spare2;
            TxRxMode = txRxMode;
            ReportingInterval = reportingInterval;
            QuietTime = quietTime;
            Spare3 = spare3;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets MessageID
        /// </summary>
        [JsonPropertyName("MessageID")]
        public int MessageID { get; set; }

        /// <summary>
        /// Gets or Sets RepeatIndicator
        /// </summary>
        [JsonPropertyName("RepeatIndicator")]
        public int RepeatIndicator { get; set; }

        /// <summary>
        /// Gets or Sets UserID
        /// </summary>
        [JsonPropertyName("UserID")]
        public int UserID { get; set; }

        /// <summary>
        /// Gets or Sets Valid
        /// </summary>
        [JsonPropertyName("Valid")]
        public bool Valid { get; set; }

        /// <summary>
        /// Gets or Sets Spare1
        /// </summary>
        [JsonPropertyName("Spare1")]
        public int Spare1 { get; set; }

        /// <summary>
        /// Gets or Sets Longitude1
        /// </summary>
        [JsonPropertyName("Longitude1")]
        public double Longitude1 { get; set; }

        /// <summary>
        /// Gets or Sets Latitude1
        /// </summary>
        [JsonPropertyName("Latitude1")]
        public double Latitude1 { get; set; }

        /// <summary>
        /// Gets or Sets Longitude2
        /// </summary>
        [JsonPropertyName("Longitude2")]
        public double Longitude2 { get; set; }

        /// <summary>
        /// Gets or Sets Latitude2
        /// </summary>
        [JsonPropertyName("Latitude2")]
        public double Latitude2 { get; set; }

        /// <summary>
        /// Gets or Sets StationType
        /// </summary>
        [JsonPropertyName("StationType")]
        public int StationType { get; set; }

        /// <summary>
        /// Gets or Sets ShipType
        /// </summary>
        [JsonPropertyName("ShipType")]
        public int ShipType { get; set; }

        /// <summary>
        /// Gets or Sets Spare2
        /// </summary>
        [JsonPropertyName("Spare2")]
        public int Spare2 { get; set; }

        /// <summary>
        /// Gets or Sets TxRxMode
        /// </summary>
        [JsonPropertyName("TxRxMode")]
        public int TxRxMode { get; set; }

        /// <summary>
        /// Gets or Sets ReportingInterval
        /// </summary>
        [JsonPropertyName("ReportingInterval")]
        public int ReportingInterval { get; set; }

        /// <summary>
        /// Gets or Sets QuietTime
        /// </summary>
        [JsonPropertyName("QuietTime")]
        public int QuietTime { get; set; }

        /// <summary>
        /// Gets or Sets Spare3
        /// </summary>
        [JsonPropertyName("Spare3")]
        public int Spare3 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GroupAssignmentCommand {\n");
            sb.Append("  MessageID: ").Append(MessageID).Append("\n");
            sb.Append("  RepeatIndicator: ").Append(RepeatIndicator).Append("\n");
            sb.Append("  UserID: ").Append(UserID).Append("\n");
            sb.Append("  Valid: ").Append(Valid).Append("\n");
            sb.Append("  Spare1: ").Append(Spare1).Append("\n");
            sb.Append("  Longitude1: ").Append(Longitude1).Append("\n");
            sb.Append("  Latitude1: ").Append(Latitude1).Append("\n");
            sb.Append("  Longitude2: ").Append(Longitude2).Append("\n");
            sb.Append("  Latitude2: ").Append(Latitude2).Append("\n");
            sb.Append("  StationType: ").Append(StationType).Append("\n");
            sb.Append("  ShipType: ").Append(ShipType).Append("\n");
            sb.Append("  Spare2: ").Append(Spare2).Append("\n");
            sb.Append("  TxRxMode: ").Append(TxRxMode).Append("\n");
            sb.Append("  ReportingInterval: ").Append(ReportingInterval).Append("\n");
            sb.Append("  QuietTime: ").Append(QuietTime).Append("\n");
            sb.Append("  Spare3: ").Append(Spare3).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GroupAssignmentCommand" />
    /// </summary>
    public class GroupAssignmentCommandJsonConverter : JsonConverter<GroupAssignmentCommand>
    {
        /// <summary>
        /// Deserializes json to <see cref="GroupAssignmentCommand" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GroupAssignmentCommand Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> messageID = default;
            Option<int?> repeatIndicator = default;
            Option<int?> userID = default;
            Option<bool?> valid = default;
            Option<int?> spare1 = default;
            Option<double?> longitude1 = default;
            Option<double?> latitude1 = default;
            Option<double?> longitude2 = default;
            Option<double?> latitude2 = default;
            Option<int?> stationType = default;
            Option<int?> shipType = default;
            Option<int?> spare2 = default;
            Option<int?> txRxMode = default;
            Option<int?> reportingInterval = default;
            Option<int?> quietTime = default;
            Option<int?> spare3 = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "MessageID":
                            messageID = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "RepeatIndicator":
                            repeatIndicator = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "UserID":
                            userID = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "Valid":
                            valid = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "Spare1":
                            spare1 = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "Longitude1":
                            longitude1 = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "Latitude1":
                            latitude1 = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "Longitude2":
                            longitude2 = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "Latitude2":
                            latitude2 = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "StationType":
                            stationType = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "ShipType":
                            shipType = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "Spare2":
                            spare2 = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "TxRxMode":
                            txRxMode = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "ReportingInterval":
                            reportingInterval = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "QuietTime":
                            quietTime = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "Spare3":
                            spare3 = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!messageID.IsSet)
                throw new ArgumentException("Property is required for class GroupAssignmentCommand.", nameof(messageID));

            if (!repeatIndicator.IsSet)
                throw new ArgumentException("Property is required for class GroupAssignmentCommand.", nameof(repeatIndicator));

            if (!userID.IsSet)
                throw new ArgumentException("Property is required for class GroupAssignmentCommand.", nameof(userID));

            if (!valid.IsSet)
                throw new ArgumentException("Property is required for class GroupAssignmentCommand.", nameof(valid));

            if (!spare1.IsSet)
                throw new ArgumentException("Property is required for class GroupAssignmentCommand.", nameof(spare1));

            if (!longitude1.IsSet)
                throw new ArgumentException("Property is required for class GroupAssignmentCommand.", nameof(longitude1));

            if (!latitude1.IsSet)
                throw new ArgumentException("Property is required for class GroupAssignmentCommand.", nameof(latitude1));

            if (!longitude2.IsSet)
                throw new ArgumentException("Property is required for class GroupAssignmentCommand.", nameof(longitude2));

            if (!latitude2.IsSet)
                throw new ArgumentException("Property is required for class GroupAssignmentCommand.", nameof(latitude2));

            if (!stationType.IsSet)
                throw new ArgumentException("Property is required for class GroupAssignmentCommand.", nameof(stationType));

            if (!shipType.IsSet)
                throw new ArgumentException("Property is required for class GroupAssignmentCommand.", nameof(shipType));

            if (!spare2.IsSet)
                throw new ArgumentException("Property is required for class GroupAssignmentCommand.", nameof(spare2));

            if (!txRxMode.IsSet)
                throw new ArgumentException("Property is required for class GroupAssignmentCommand.", nameof(txRxMode));

            if (!reportingInterval.IsSet)
                throw new ArgumentException("Property is required for class GroupAssignmentCommand.", nameof(reportingInterval));

            if (!quietTime.IsSet)
                throw new ArgumentException("Property is required for class GroupAssignmentCommand.", nameof(quietTime));

            if (!spare3.IsSet)
                throw new ArgumentException("Property is required for class GroupAssignmentCommand.", nameof(spare3));

            if (messageID.IsSet && messageID.Value == null)
                throw new ArgumentNullException(nameof(messageID), "Property is not nullable for class GroupAssignmentCommand.");

            if (repeatIndicator.IsSet && repeatIndicator.Value == null)
                throw new ArgumentNullException(nameof(repeatIndicator), "Property is not nullable for class GroupAssignmentCommand.");

            if (userID.IsSet && userID.Value == null)
                throw new ArgumentNullException(nameof(userID), "Property is not nullable for class GroupAssignmentCommand.");

            if (valid.IsSet && valid.Value == null)
                throw new ArgumentNullException(nameof(valid), "Property is not nullable for class GroupAssignmentCommand.");

            if (spare1.IsSet && spare1.Value == null)
                throw new ArgumentNullException(nameof(spare1), "Property is not nullable for class GroupAssignmentCommand.");

            if (longitude1.IsSet && longitude1.Value == null)
                throw new ArgumentNullException(nameof(longitude1), "Property is not nullable for class GroupAssignmentCommand.");

            if (latitude1.IsSet && latitude1.Value == null)
                throw new ArgumentNullException(nameof(latitude1), "Property is not nullable for class GroupAssignmentCommand.");

            if (longitude2.IsSet && longitude2.Value == null)
                throw new ArgumentNullException(nameof(longitude2), "Property is not nullable for class GroupAssignmentCommand.");

            if (latitude2.IsSet && latitude2.Value == null)
                throw new ArgumentNullException(nameof(latitude2), "Property is not nullable for class GroupAssignmentCommand.");

            if (stationType.IsSet && stationType.Value == null)
                throw new ArgumentNullException(nameof(stationType), "Property is not nullable for class GroupAssignmentCommand.");

            if (shipType.IsSet && shipType.Value == null)
                throw new ArgumentNullException(nameof(shipType), "Property is not nullable for class GroupAssignmentCommand.");

            if (spare2.IsSet && spare2.Value == null)
                throw new ArgumentNullException(nameof(spare2), "Property is not nullable for class GroupAssignmentCommand.");

            if (txRxMode.IsSet && txRxMode.Value == null)
                throw new ArgumentNullException(nameof(txRxMode), "Property is not nullable for class GroupAssignmentCommand.");

            if (reportingInterval.IsSet && reportingInterval.Value == null)
                throw new ArgumentNullException(nameof(reportingInterval), "Property is not nullable for class GroupAssignmentCommand.");

            if (quietTime.IsSet && quietTime.Value == null)
                throw new ArgumentNullException(nameof(quietTime), "Property is not nullable for class GroupAssignmentCommand.");

            if (spare3.IsSet && spare3.Value == null)
                throw new ArgumentNullException(nameof(spare3), "Property is not nullable for class GroupAssignmentCommand.");

            return new GroupAssignmentCommand(messageID.Value!.Value!, repeatIndicator.Value!.Value!, userID.Value!.Value!, valid.Value!.Value!, spare1.Value!.Value!, longitude1.Value!.Value!, latitude1.Value!.Value!, longitude2.Value!.Value!, latitude2.Value!.Value!, stationType.Value!.Value!, shipType.Value!.Value!, spare2.Value!.Value!, txRxMode.Value!.Value!, reportingInterval.Value!.Value!, quietTime.Value!.Value!, spare3.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="GroupAssignmentCommand" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="groupAssignmentCommand"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GroupAssignmentCommand groupAssignmentCommand, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, groupAssignmentCommand, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GroupAssignmentCommand" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="groupAssignmentCommand"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GroupAssignmentCommand groupAssignmentCommand, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("MessageID", groupAssignmentCommand.MessageID);

            writer.WriteNumber("RepeatIndicator", groupAssignmentCommand.RepeatIndicator);

            writer.WriteNumber("UserID", groupAssignmentCommand.UserID);

            writer.WriteBoolean("Valid", groupAssignmentCommand.Valid);

            writer.WriteNumber("Spare1", groupAssignmentCommand.Spare1);

            writer.WriteNumber("Longitude1", groupAssignmentCommand.Longitude1);

            writer.WriteNumber("Latitude1", groupAssignmentCommand.Latitude1);

            writer.WriteNumber("Longitude2", groupAssignmentCommand.Longitude2);

            writer.WriteNumber("Latitude2", groupAssignmentCommand.Latitude2);

            writer.WriteNumber("StationType", groupAssignmentCommand.StationType);

            writer.WriteNumber("ShipType", groupAssignmentCommand.ShipType);

            writer.WriteNumber("Spare2", groupAssignmentCommand.Spare2);

            writer.WriteNumber("TxRxMode", groupAssignmentCommand.TxRxMode);

            writer.WriteNumber("ReportingInterval", groupAssignmentCommand.ReportingInterval);

            writer.WriteNumber("QuietTime", groupAssignmentCommand.QuietTime);

            writer.WriteNumber("Spare3", groupAssignmentCommand.Spare3);
        }
    }
}
