// <auto-generated>
/*
 * Ais-Stream WebsocketObjects
 *
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// InterrogationStation2
    /// </summary>
    public partial class InterrogationStation2 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InterrogationStation2" /> class.
        /// </summary>
        /// <param name="valid">valid</param>
        /// <param name="spare1">spare1</param>
        /// <param name="stationID">stationID</param>
        /// <param name="messageID">messageID</param>
        /// <param name="slotOffset">slotOffset</param>
        /// <param name="spare2">spare2</param>
        [JsonConstructor]
        public InterrogationStation2(bool valid, int spare1, int stationID, int messageID, int slotOffset, int spare2)
        {
            Valid = valid;
            Spare1 = spare1;
            StationID = stationID;
            MessageID = messageID;
            SlotOffset = slotOffset;
            Spare2 = spare2;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Valid
        /// </summary>
        [JsonPropertyName("Valid")]
        public bool Valid { get; set; }

        /// <summary>
        /// Gets or Sets Spare1
        /// </summary>
        [JsonPropertyName("Spare1")]
        public int Spare1 { get; set; }

        /// <summary>
        /// Gets or Sets StationID
        /// </summary>
        [JsonPropertyName("StationID")]
        public int StationID { get; set; }

        /// <summary>
        /// Gets or Sets MessageID
        /// </summary>
        [JsonPropertyName("MessageID")]
        public int MessageID { get; set; }

        /// <summary>
        /// Gets or Sets SlotOffset
        /// </summary>
        [JsonPropertyName("SlotOffset")]
        public int SlotOffset { get; set; }

        /// <summary>
        /// Gets or Sets Spare2
        /// </summary>
        [JsonPropertyName("Spare2")]
        public int Spare2 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InterrogationStation2 {\n");
            sb.Append("  Valid: ").Append(Valid).Append("\n");
            sb.Append("  Spare1: ").Append(Spare1).Append("\n");
            sb.Append("  StationID: ").Append(StationID).Append("\n");
            sb.Append("  MessageID: ").Append(MessageID).Append("\n");
            sb.Append("  SlotOffset: ").Append(SlotOffset).Append("\n");
            sb.Append("  Spare2: ").Append(Spare2).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="InterrogationStation2" />
    /// </summary>
    public class InterrogationStation2JsonConverter : JsonConverter<InterrogationStation2>
    {
        /// <summary>
        /// Deserializes json to <see cref="InterrogationStation2" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override InterrogationStation2 Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> valid = default;
            Option<int?> spare1 = default;
            Option<int?> stationID = default;
            Option<int?> messageID = default;
            Option<int?> slotOffset = default;
            Option<int?> spare2 = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "Valid":
                            valid = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "Spare1":
                            spare1 = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "StationID":
                            stationID = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "MessageID":
                            messageID = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "SlotOffset":
                            slotOffset = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "Spare2":
                            spare2 = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!valid.IsSet)
                throw new ArgumentException("Property is required for class InterrogationStation2.", nameof(valid));

            if (!spare1.IsSet)
                throw new ArgumentException("Property is required for class InterrogationStation2.", nameof(spare1));

            if (!stationID.IsSet)
                throw new ArgumentException("Property is required for class InterrogationStation2.", nameof(stationID));

            if (!messageID.IsSet)
                throw new ArgumentException("Property is required for class InterrogationStation2.", nameof(messageID));

            if (!slotOffset.IsSet)
                throw new ArgumentException("Property is required for class InterrogationStation2.", nameof(slotOffset));

            if (!spare2.IsSet)
                throw new ArgumentException("Property is required for class InterrogationStation2.", nameof(spare2));

            if (valid.IsSet && valid.Value == null)
                throw new ArgumentNullException(nameof(valid), "Property is not nullable for class InterrogationStation2.");

            if (spare1.IsSet && spare1.Value == null)
                throw new ArgumentNullException(nameof(spare1), "Property is not nullable for class InterrogationStation2.");

            if (stationID.IsSet && stationID.Value == null)
                throw new ArgumentNullException(nameof(stationID), "Property is not nullable for class InterrogationStation2.");

            if (messageID.IsSet && messageID.Value == null)
                throw new ArgumentNullException(nameof(messageID), "Property is not nullable for class InterrogationStation2.");

            if (slotOffset.IsSet && slotOffset.Value == null)
                throw new ArgumentNullException(nameof(slotOffset), "Property is not nullable for class InterrogationStation2.");

            if (spare2.IsSet && spare2.Value == null)
                throw new ArgumentNullException(nameof(spare2), "Property is not nullable for class InterrogationStation2.");

            return new InterrogationStation2(valid.Value!.Value!, spare1.Value!.Value!, stationID.Value!.Value!, messageID.Value!.Value!, slotOffset.Value!.Value!, spare2.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="InterrogationStation2" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="interrogationStation2"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, InterrogationStation2 interrogationStation2, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, interrogationStation2, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="InterrogationStation2" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="interrogationStation2"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, InterrogationStation2 interrogationStation2, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteBoolean("Valid", interrogationStation2.Valid);

            writer.WriteNumber("Spare1", interrogationStation2.Spare1);

            writer.WriteNumber("StationID", interrogationStation2.StationID);

            writer.WriteNumber("MessageID", interrogationStation2.MessageID);

            writer.WriteNumber("SlotOffset", interrogationStation2.SlotOffset);

            writer.WriteNumber("Spare2", interrogationStation2.Spare2);
        }
    }
}
