// <auto-generated>
/*
 * Ais-Stream WebsocketObjects
 *
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ShipStaticDataDimension
    /// </summary>
    public partial class ShipStaticDataDimension : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ShipStaticDataDimension" /> class.
        /// </summary>
        /// <param name="a">a</param>
        /// <param name="b">b</param>
        /// <param name="c">c</param>
        /// <param name="d">d</param>
        [JsonConstructor]
        public ShipStaticDataDimension(int a, int b, int c, int d)
        {
            A = a;
            B = b;
            C = c;
            D = d;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets A
        /// </summary>
        [JsonPropertyName("A")]
        public int A { get; set; }

        /// <summary>
        /// Gets or Sets B
        /// </summary>
        [JsonPropertyName("B")]
        public int B { get; set; }

        /// <summary>
        /// Gets or Sets C
        /// </summary>
        [JsonPropertyName("C")]
        public int C { get; set; }

        /// <summary>
        /// Gets or Sets D
        /// </summary>
        [JsonPropertyName("D")]
        public int D { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ShipStaticDataDimension {\n");
            sb.Append("  A: ").Append(A).Append("\n");
            sb.Append("  B: ").Append(B).Append("\n");
            sb.Append("  C: ").Append(C).Append("\n");
            sb.Append("  D: ").Append(D).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ShipStaticDataDimension" />
    /// </summary>
    public class ShipStaticDataDimensionJsonConverter : JsonConverter<ShipStaticDataDimension>
    {
        /// <summary>
        /// Deserializes json to <see cref="ShipStaticDataDimension" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ShipStaticDataDimension Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> a = default;
            Option<int?> b = default;
            Option<int?> c = default;
            Option<int?> d = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "A":
                            a = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "B":
                            b = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "C":
                            c = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "D":
                            d = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!a.IsSet)
                throw new ArgumentException("Property is required for class ShipStaticDataDimension.", nameof(a));

            if (!b.IsSet)
                throw new ArgumentException("Property is required for class ShipStaticDataDimension.", nameof(b));

            if (!c.IsSet)
                throw new ArgumentException("Property is required for class ShipStaticDataDimension.", nameof(c));

            if (!d.IsSet)
                throw new ArgumentException("Property is required for class ShipStaticDataDimension.", nameof(d));

            if (a.IsSet && a.Value == null)
                throw new ArgumentNullException(nameof(a), "Property is not nullable for class ShipStaticDataDimension.");

            if (b.IsSet && b.Value == null)
                throw new ArgumentNullException(nameof(b), "Property is not nullable for class ShipStaticDataDimension.");

            if (c.IsSet && c.Value == null)
                throw new ArgumentNullException(nameof(c), "Property is not nullable for class ShipStaticDataDimension.");

            if (d.IsSet && d.Value == null)
                throw new ArgumentNullException(nameof(d), "Property is not nullable for class ShipStaticDataDimension.");

            return new ShipStaticDataDimension(a.Value!.Value!, b.Value!.Value!, c.Value!.Value!, d.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="ShipStaticDataDimension" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="shipStaticDataDimension"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ShipStaticDataDimension shipStaticDataDimension, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, shipStaticDataDimension, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ShipStaticDataDimension" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="shipStaticDataDimension"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ShipStaticDataDimension shipStaticDataDimension, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("A", shipStaticDataDimension.A);

            writer.WriteNumber("B", shipStaticDataDimension.B);

            writer.WriteNumber("C", shipStaticDataDimension.C);

            writer.WriteNumber("D", shipStaticDataDimension.D);
        }
    }
}
