// <auto-generated>
/*
 * Ais-Stream WebsocketObjects
 *
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// StandardClassBPositionReport
    /// </summary>
    public partial class StandardClassBPositionReport : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StandardClassBPositionReport" /> class.
        /// </summary>
        /// <param name="messageID">messageID</param>
        /// <param name="repeatIndicator">repeatIndicator</param>
        /// <param name="userID">userID</param>
        /// <param name="valid">valid</param>
        /// <param name="spare1">spare1</param>
        /// <param name="sog">sog</param>
        /// <param name="positionAccuracy">positionAccuracy</param>
        /// <param name="longitude">longitude</param>
        /// <param name="latitude">latitude</param>
        /// <param name="cog">cog</param>
        /// <param name="trueHeading">trueHeading</param>
        /// <param name="timestamp">timestamp</param>
        /// <param name="spare2">spare2</param>
        /// <param name="classBUnit">classBUnit</param>
        /// <param name="classBDisplay">classBDisplay</param>
        /// <param name="classBDsc">classBDsc</param>
        /// <param name="classBBand">classBBand</param>
        /// <param name="classBMsg22">classBMsg22</param>
        /// <param name="assignedMode">assignedMode</param>
        /// <param name="raim">raim</param>
        /// <param name="communicationStateIsItdma">communicationStateIsItdma</param>
        /// <param name="communicationState">communicationState</param>
        [JsonConstructor]
        public StandardClassBPositionReport(int messageID, int repeatIndicator, int userID, bool valid, int spare1, double sog, bool positionAccuracy, double longitude, double latitude, double cog, int trueHeading, int timestamp, int spare2, bool classBUnit, bool classBDisplay, bool classBDsc, bool classBBand, bool classBMsg22, bool assignedMode, bool raim, bool communicationStateIsItdma, int communicationState)
        {
            MessageID = messageID;
            RepeatIndicator = repeatIndicator;
            UserID = userID;
            Valid = valid;
            Spare1 = spare1;
            Sog = sog;
            PositionAccuracy = positionAccuracy;
            Longitude = longitude;
            Latitude = latitude;
            Cog = cog;
            TrueHeading = trueHeading;
            Timestamp = timestamp;
            Spare2 = spare2;
            ClassBUnit = classBUnit;
            ClassBDisplay = classBDisplay;
            ClassBDsc = classBDsc;
            ClassBBand = classBBand;
            ClassBMsg22 = classBMsg22;
            AssignedMode = assignedMode;
            Raim = raim;
            CommunicationStateIsItdma = communicationStateIsItdma;
            CommunicationState = communicationState;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets MessageID
        /// </summary>
        [JsonPropertyName("MessageID")]
        public int MessageID { get; set; }

        /// <summary>
        /// Gets or Sets RepeatIndicator
        /// </summary>
        [JsonPropertyName("RepeatIndicator")]
        public int RepeatIndicator { get; set; }

        /// <summary>
        /// Gets or Sets UserID
        /// </summary>
        [JsonPropertyName("UserID")]
        public int UserID { get; set; }

        /// <summary>
        /// Gets or Sets Valid
        /// </summary>
        [JsonPropertyName("Valid")]
        public bool Valid { get; set; }

        /// <summary>
        /// Gets or Sets Spare1
        /// </summary>
        [JsonPropertyName("Spare1")]
        public int Spare1 { get; set; }

        /// <summary>
        /// Gets or Sets Sog
        /// </summary>
        [JsonPropertyName("Sog")]
        public double Sog { get; set; }

        /// <summary>
        /// Gets or Sets PositionAccuracy
        /// </summary>
        [JsonPropertyName("PositionAccuracy")]
        public bool PositionAccuracy { get; set; }

        /// <summary>
        /// Gets or Sets Longitude
        /// </summary>
        [JsonPropertyName("Longitude")]
        public double Longitude { get; set; }

        /// <summary>
        /// Gets or Sets Latitude
        /// </summary>
        [JsonPropertyName("Latitude")]
        public double Latitude { get; set; }

        /// <summary>
        /// Gets or Sets Cog
        /// </summary>
        [JsonPropertyName("Cog")]
        public double Cog { get; set; }

        /// <summary>
        /// Gets or Sets TrueHeading
        /// </summary>
        [JsonPropertyName("TrueHeading")]
        public int TrueHeading { get; set; }

        /// <summary>
        /// Gets or Sets Timestamp
        /// </summary>
        [JsonPropertyName("Timestamp")]
        public int Timestamp { get; set; }

        /// <summary>
        /// Gets or Sets Spare2
        /// </summary>
        [JsonPropertyName("Spare2")]
        public int Spare2 { get; set; }

        /// <summary>
        /// Gets or Sets ClassBUnit
        /// </summary>
        [JsonPropertyName("ClassBUnit")]
        public bool ClassBUnit { get; set; }

        /// <summary>
        /// Gets or Sets ClassBDisplay
        /// </summary>
        [JsonPropertyName("ClassBDisplay")]
        public bool ClassBDisplay { get; set; }

        /// <summary>
        /// Gets or Sets ClassBDsc
        /// </summary>
        [JsonPropertyName("ClassBDsc")]
        public bool ClassBDsc { get; set; }

        /// <summary>
        /// Gets or Sets ClassBBand
        /// </summary>
        [JsonPropertyName("ClassBBand")]
        public bool ClassBBand { get; set; }

        /// <summary>
        /// Gets or Sets ClassBMsg22
        /// </summary>
        [JsonPropertyName("ClassBMsg22")]
        public bool ClassBMsg22 { get; set; }

        /// <summary>
        /// Gets or Sets AssignedMode
        /// </summary>
        [JsonPropertyName("AssignedMode")]
        public bool AssignedMode { get; set; }

        /// <summary>
        /// Gets or Sets Raim
        /// </summary>
        [JsonPropertyName("Raim")]
        public bool Raim { get; set; }

        /// <summary>
        /// Gets or Sets CommunicationStateIsItdma
        /// </summary>
        [JsonPropertyName("CommunicationStateIsItdma")]
        public bool CommunicationStateIsItdma { get; set; }

        /// <summary>
        /// Gets or Sets CommunicationState
        /// </summary>
        [JsonPropertyName("CommunicationState")]
        public int CommunicationState { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StandardClassBPositionReport {\n");
            sb.Append("  MessageID: ").Append(MessageID).Append("\n");
            sb.Append("  RepeatIndicator: ").Append(RepeatIndicator).Append("\n");
            sb.Append("  UserID: ").Append(UserID).Append("\n");
            sb.Append("  Valid: ").Append(Valid).Append("\n");
            sb.Append("  Spare1: ").Append(Spare1).Append("\n");
            sb.Append("  Sog: ").Append(Sog).Append("\n");
            sb.Append("  PositionAccuracy: ").Append(PositionAccuracy).Append("\n");
            sb.Append("  Longitude: ").Append(Longitude).Append("\n");
            sb.Append("  Latitude: ").Append(Latitude).Append("\n");
            sb.Append("  Cog: ").Append(Cog).Append("\n");
            sb.Append("  TrueHeading: ").Append(TrueHeading).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  Spare2: ").Append(Spare2).Append("\n");
            sb.Append("  ClassBUnit: ").Append(ClassBUnit).Append("\n");
            sb.Append("  ClassBDisplay: ").Append(ClassBDisplay).Append("\n");
            sb.Append("  ClassBDsc: ").Append(ClassBDsc).Append("\n");
            sb.Append("  ClassBBand: ").Append(ClassBBand).Append("\n");
            sb.Append("  ClassBMsg22: ").Append(ClassBMsg22).Append("\n");
            sb.Append("  AssignedMode: ").Append(AssignedMode).Append("\n");
            sb.Append("  Raim: ").Append(Raim).Append("\n");
            sb.Append("  CommunicationStateIsItdma: ").Append(CommunicationStateIsItdma).Append("\n");
            sb.Append("  CommunicationState: ").Append(CommunicationState).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="StandardClassBPositionReport" />
    /// </summary>
    public class StandardClassBPositionReportJsonConverter : JsonConverter<StandardClassBPositionReport>
    {
        /// <summary>
        /// Deserializes json to <see cref="StandardClassBPositionReport" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override StandardClassBPositionReport Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> messageID = default;
            Option<int?> repeatIndicator = default;
            Option<int?> userID = default;
            Option<bool?> valid = default;
            Option<int?> spare1 = default;
            Option<double?> sog = default;
            Option<bool?> positionAccuracy = default;
            Option<double?> longitude = default;
            Option<double?> latitude = default;
            Option<double?> cog = default;
            Option<int?> trueHeading = default;
            Option<int?> timestamp = default;
            Option<int?> spare2 = default;
            Option<bool?> classBUnit = default;
            Option<bool?> classBDisplay = default;
            Option<bool?> classBDsc = default;
            Option<bool?> classBBand = default;
            Option<bool?> classBMsg22 = default;
            Option<bool?> assignedMode = default;
            Option<bool?> raim = default;
            Option<bool?> communicationStateIsItdma = default;
            Option<int?> communicationState = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "MessageID":
                            messageID = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "RepeatIndicator":
                            repeatIndicator = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "UserID":
                            userID = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "Valid":
                            valid = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "Spare1":
                            spare1 = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "Sog":
                            sog = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "PositionAccuracy":
                            positionAccuracy = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "Longitude":
                            longitude = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "Latitude":
                            latitude = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "Cog":
                            cog = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "TrueHeading":
                            trueHeading = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "Timestamp":
                            timestamp = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "Spare2":
                            spare2 = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "ClassBUnit":
                            classBUnit = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "ClassBDisplay":
                            classBDisplay = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "ClassBDsc":
                            classBDsc = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "ClassBBand":
                            classBBand = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "ClassBMsg22":
                            classBMsg22 = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "AssignedMode":
                            assignedMode = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "Raim":
                            raim = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "CommunicationStateIsItdma":
                            communicationStateIsItdma = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "CommunicationState":
                            communicationState = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!messageID.IsSet)
                throw new ArgumentException("Property is required for class StandardClassBPositionReport.", nameof(messageID));

            if (!repeatIndicator.IsSet)
                throw new ArgumentException("Property is required for class StandardClassBPositionReport.", nameof(repeatIndicator));

            if (!userID.IsSet)
                throw new ArgumentException("Property is required for class StandardClassBPositionReport.", nameof(userID));

            if (!valid.IsSet)
                throw new ArgumentException("Property is required for class StandardClassBPositionReport.", nameof(valid));

            if (!spare1.IsSet)
                throw new ArgumentException("Property is required for class StandardClassBPositionReport.", nameof(spare1));

            if (!sog.IsSet)
                throw new ArgumentException("Property is required for class StandardClassBPositionReport.", nameof(sog));

            if (!positionAccuracy.IsSet)
                throw new ArgumentException("Property is required for class StandardClassBPositionReport.", nameof(positionAccuracy));

            if (!longitude.IsSet)
                throw new ArgumentException("Property is required for class StandardClassBPositionReport.", nameof(longitude));

            if (!latitude.IsSet)
                throw new ArgumentException("Property is required for class StandardClassBPositionReport.", nameof(latitude));

            if (!cog.IsSet)
                throw new ArgumentException("Property is required for class StandardClassBPositionReport.", nameof(cog));

            if (!trueHeading.IsSet)
                throw new ArgumentException("Property is required for class StandardClassBPositionReport.", nameof(trueHeading));

            if (!timestamp.IsSet)
                throw new ArgumentException("Property is required for class StandardClassBPositionReport.", nameof(timestamp));

            if (!spare2.IsSet)
                throw new ArgumentException("Property is required for class StandardClassBPositionReport.", nameof(spare2));

            if (!classBUnit.IsSet)
                throw new ArgumentException("Property is required for class StandardClassBPositionReport.", nameof(classBUnit));

            if (!classBDisplay.IsSet)
                throw new ArgumentException("Property is required for class StandardClassBPositionReport.", nameof(classBDisplay));

            if (!classBDsc.IsSet)
                throw new ArgumentException("Property is required for class StandardClassBPositionReport.", nameof(classBDsc));

            if (!classBBand.IsSet)
                throw new ArgumentException("Property is required for class StandardClassBPositionReport.", nameof(classBBand));

            if (!classBMsg22.IsSet)
                throw new ArgumentException("Property is required for class StandardClassBPositionReport.", nameof(classBMsg22));

            if (!assignedMode.IsSet)
                throw new ArgumentException("Property is required for class StandardClassBPositionReport.", nameof(assignedMode));

            if (!raim.IsSet)
                throw new ArgumentException("Property is required for class StandardClassBPositionReport.", nameof(raim));

            if (!communicationStateIsItdma.IsSet)
                throw new ArgumentException("Property is required for class StandardClassBPositionReport.", nameof(communicationStateIsItdma));

            if (!communicationState.IsSet)
                throw new ArgumentException("Property is required for class StandardClassBPositionReport.", nameof(communicationState));

            if (messageID.IsSet && messageID.Value == null)
                throw new ArgumentNullException(nameof(messageID), "Property is not nullable for class StandardClassBPositionReport.");

            if (repeatIndicator.IsSet && repeatIndicator.Value == null)
                throw new ArgumentNullException(nameof(repeatIndicator), "Property is not nullable for class StandardClassBPositionReport.");

            if (userID.IsSet && userID.Value == null)
                throw new ArgumentNullException(nameof(userID), "Property is not nullable for class StandardClassBPositionReport.");

            if (valid.IsSet && valid.Value == null)
                throw new ArgumentNullException(nameof(valid), "Property is not nullable for class StandardClassBPositionReport.");

            if (spare1.IsSet && spare1.Value == null)
                throw new ArgumentNullException(nameof(spare1), "Property is not nullable for class StandardClassBPositionReport.");

            if (sog.IsSet && sog.Value == null)
                throw new ArgumentNullException(nameof(sog), "Property is not nullable for class StandardClassBPositionReport.");

            if (positionAccuracy.IsSet && positionAccuracy.Value == null)
                throw new ArgumentNullException(nameof(positionAccuracy), "Property is not nullable for class StandardClassBPositionReport.");

            if (longitude.IsSet && longitude.Value == null)
                throw new ArgumentNullException(nameof(longitude), "Property is not nullable for class StandardClassBPositionReport.");

            if (latitude.IsSet && latitude.Value == null)
                throw new ArgumentNullException(nameof(latitude), "Property is not nullable for class StandardClassBPositionReport.");

            if (cog.IsSet && cog.Value == null)
                throw new ArgumentNullException(nameof(cog), "Property is not nullable for class StandardClassBPositionReport.");

            if (trueHeading.IsSet && trueHeading.Value == null)
                throw new ArgumentNullException(nameof(trueHeading), "Property is not nullable for class StandardClassBPositionReport.");

            if (timestamp.IsSet && timestamp.Value == null)
                throw new ArgumentNullException(nameof(timestamp), "Property is not nullable for class StandardClassBPositionReport.");

            if (spare2.IsSet && spare2.Value == null)
                throw new ArgumentNullException(nameof(spare2), "Property is not nullable for class StandardClassBPositionReport.");

            if (classBUnit.IsSet && classBUnit.Value == null)
                throw new ArgumentNullException(nameof(classBUnit), "Property is not nullable for class StandardClassBPositionReport.");

            if (classBDisplay.IsSet && classBDisplay.Value == null)
                throw new ArgumentNullException(nameof(classBDisplay), "Property is not nullable for class StandardClassBPositionReport.");

            if (classBDsc.IsSet && classBDsc.Value == null)
                throw new ArgumentNullException(nameof(classBDsc), "Property is not nullable for class StandardClassBPositionReport.");

            if (classBBand.IsSet && classBBand.Value == null)
                throw new ArgumentNullException(nameof(classBBand), "Property is not nullable for class StandardClassBPositionReport.");

            if (classBMsg22.IsSet && classBMsg22.Value == null)
                throw new ArgumentNullException(nameof(classBMsg22), "Property is not nullable for class StandardClassBPositionReport.");

            if (assignedMode.IsSet && assignedMode.Value == null)
                throw new ArgumentNullException(nameof(assignedMode), "Property is not nullable for class StandardClassBPositionReport.");

            if (raim.IsSet && raim.Value == null)
                throw new ArgumentNullException(nameof(raim), "Property is not nullable for class StandardClassBPositionReport.");

            if (communicationStateIsItdma.IsSet && communicationStateIsItdma.Value == null)
                throw new ArgumentNullException(nameof(communicationStateIsItdma), "Property is not nullable for class StandardClassBPositionReport.");

            if (communicationState.IsSet && communicationState.Value == null)
                throw new ArgumentNullException(nameof(communicationState), "Property is not nullable for class StandardClassBPositionReport.");

            return new StandardClassBPositionReport(messageID.Value!.Value!, repeatIndicator.Value!.Value!, userID.Value!.Value!, valid.Value!.Value!, spare1.Value!.Value!, sog.Value!.Value!, positionAccuracy.Value!.Value!, longitude.Value!.Value!, latitude.Value!.Value!, cog.Value!.Value!, trueHeading.Value!.Value!, timestamp.Value!.Value!, spare2.Value!.Value!, classBUnit.Value!.Value!, classBDisplay.Value!.Value!, classBDsc.Value!.Value!, classBBand.Value!.Value!, classBMsg22.Value!.Value!, assignedMode.Value!.Value!, raim.Value!.Value!, communicationStateIsItdma.Value!.Value!, communicationState.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="StandardClassBPositionReport" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="standardClassBPositionReport"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, StandardClassBPositionReport standardClassBPositionReport, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, standardClassBPositionReport, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="StandardClassBPositionReport" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="standardClassBPositionReport"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, StandardClassBPositionReport standardClassBPositionReport, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("MessageID", standardClassBPositionReport.MessageID);

            writer.WriteNumber("RepeatIndicator", standardClassBPositionReport.RepeatIndicator);

            writer.WriteNumber("UserID", standardClassBPositionReport.UserID);

            writer.WriteBoolean("Valid", standardClassBPositionReport.Valid);

            writer.WriteNumber("Spare1", standardClassBPositionReport.Spare1);

            writer.WriteNumber("Sog", standardClassBPositionReport.Sog);

            writer.WriteBoolean("PositionAccuracy", standardClassBPositionReport.PositionAccuracy);

            writer.WriteNumber("Longitude", standardClassBPositionReport.Longitude);

            writer.WriteNumber("Latitude", standardClassBPositionReport.Latitude);

            writer.WriteNumber("Cog", standardClassBPositionReport.Cog);

            writer.WriteNumber("TrueHeading", standardClassBPositionReport.TrueHeading);

            writer.WriteNumber("Timestamp", standardClassBPositionReport.Timestamp);

            writer.WriteNumber("Spare2", standardClassBPositionReport.Spare2);

            writer.WriteBoolean("ClassBUnit", standardClassBPositionReport.ClassBUnit);

            writer.WriteBoolean("ClassBDisplay", standardClassBPositionReport.ClassBDisplay);

            writer.WriteBoolean("ClassBDsc", standardClassBPositionReport.ClassBDsc);

            writer.WriteBoolean("ClassBBand", standardClassBPositionReport.ClassBBand);

            writer.WriteBoolean("ClassBMsg22", standardClassBPositionReport.ClassBMsg22);

            writer.WriteBoolean("AssignedMode", standardClassBPositionReport.AssignedMode);

            writer.WriteBoolean("Raim", standardClassBPositionReport.Raim);

            writer.WriteBoolean("CommunicationStateIsItdma", standardClassBPositionReport.CommunicationStateIsItdma);

            writer.WriteNumber("CommunicationState", standardClassBPositionReport.CommunicationState);
        }
    }
}
