/*
 * Ais-Stream WebsocketObjects
 *
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Net.Http;
using Microsoft.Extensions.DependencyInjection;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Client
{
    /// <summary>
    /// Provides hosting configuration for Org.OpenAPITools
    /// </summary>
    public class HostConfiguration
    {
        private readonly IServiceCollection _services;
        private readonly JsonSerializerOptions _jsonOptions = new JsonSerializerOptions();

        internal bool HttpClientsAdded { get; private set; }

        /// <summary>
        /// Instantiates the class 
        /// </summary>
        /// <param name="services"></param>
        public HostConfiguration(IServiceCollection services)
        {
            _services = services;
            _jsonOptions.Converters.Add(new JsonStringEnumConverter());
            _jsonOptions.Converters.Add(new DateTimeJsonConverter());
            _jsonOptions.Converters.Add(new DateTimeNullableJsonConverter());
            _jsonOptions.Converters.Add(new DateOnlyJsonConverter());
            _jsonOptions.Converters.Add(new DateOnlyNullableJsonConverter());
            _jsonOptions.Converters.Add(new AddressedBinaryMessageJsonConverter());
            _jsonOptions.Converters.Add(new AddressedBinaryMessageApplicationIDJsonConverter());
            _jsonOptions.Converters.Add(new AddressedSafetyMessageJsonConverter());
            _jsonOptions.Converters.Add(new AidsToNavigationReportJsonConverter());
            _jsonOptions.Converters.Add(new AisMessageTypesJsonConverter());
            _jsonOptions.Converters.Add(new AisMessageTypesNullableJsonConverter());
            _jsonOptions.Converters.Add(new AisStreamMessageJsonConverter());
            _jsonOptions.Converters.Add(new AisStreamMessageMessageJsonConverter());
            _jsonOptions.Converters.Add(new AssignedModeCommandJsonConverter());
            _jsonOptions.Converters.Add(new AssignedModeCommandCommandsJsonConverter());
            _jsonOptions.Converters.Add(new AssignedModeCommandCommands0JsonConverter());
            _jsonOptions.Converters.Add(new BaseStationReportJsonConverter());
            _jsonOptions.Converters.Add(new BinaryAcknowledgeJsonConverter());
            _jsonOptions.Converters.Add(new BinaryAcknowledgeDestinationsJsonConverter());
            _jsonOptions.Converters.Add(new BinaryAcknowledgeDestinations0JsonConverter());
            _jsonOptions.Converters.Add(new BinaryBroadcastMessageJsonConverter());
            _jsonOptions.Converters.Add(new ChannelManagementJsonConverter());
            _jsonOptions.Converters.Add(new ChannelManagementAreaJsonConverter());
            _jsonOptions.Converters.Add(new ChannelManagementUnicastJsonConverter());
            _jsonOptions.Converters.Add(new CoordinatedUTCInquiryJsonConverter());
            _jsonOptions.Converters.Add(new DataLinkManagementMessageJsonConverter());
            _jsonOptions.Converters.Add(new DataLinkManagementMessageDataJsonConverter());
            _jsonOptions.Converters.Add(new DataLinkManagementMessageData0JsonConverter());
            _jsonOptions.Converters.Add(new ErrorJsonConverter());
            _jsonOptions.Converters.Add(new ExtendedClassBPositionReportJsonConverter());
            _jsonOptions.Converters.Add(new GnssBroadcastBinaryMessageJsonConverter());
            _jsonOptions.Converters.Add(new GroupAssignmentCommandJsonConverter());
            _jsonOptions.Converters.Add(new InterrogationJsonConverter());
            _jsonOptions.Converters.Add(new InterrogationStation1Msg1JsonConverter());
            _jsonOptions.Converters.Add(new InterrogationStation1Msg2JsonConverter());
            _jsonOptions.Converters.Add(new InterrogationStation2JsonConverter());
            _jsonOptions.Converters.Add(new LongRangeAisBroadcastMessageJsonConverter());
            _jsonOptions.Converters.Add(new MultiSlotBinaryMessageJsonConverter());
            _jsonOptions.Converters.Add(new PositionReportJsonConverter());
            _jsonOptions.Converters.Add(new SafetyBroadcastMessageJsonConverter());
            _jsonOptions.Converters.Add(new ShipStaticDataJsonConverter());
            _jsonOptions.Converters.Add(new ShipStaticDataDimensionJsonConverter());
            _jsonOptions.Converters.Add(new ShipStaticDataEtaJsonConverter());
            _jsonOptions.Converters.Add(new SingleSlotBinaryMessageJsonConverter());
            _jsonOptions.Converters.Add(new StandardClassBPositionReportJsonConverter());
            _jsonOptions.Converters.Add(new StandardSearchAndRescueAircraftReportJsonConverter());
            _jsonOptions.Converters.Add(new StaticDataReportJsonConverter());
            _jsonOptions.Converters.Add(new StaticDataReportReportAJsonConverter());
            _jsonOptions.Converters.Add(new StaticDataReportReportBJsonConverter());
            _jsonOptions.Converters.Add(new SubscriptionMessageJsonConverter());
            _jsonOptions.Converters.Add(new UnknownMessageJsonConverter());
            JsonSerializerOptionsProvider jsonSerializerOptionsProvider = new(_jsonOptions);
            _services.AddSingleton(jsonSerializerOptionsProvider);
            _services.AddSingleton<IApiFactory, ApiFactory>();
        }

        /// <summary>
        /// Configures the HttpClients.
        /// </summary>
        /// <param name="client"></param>
        /// <param name="builder"></param>
        /// <returns></returns>
        public HostConfiguration AddApiHttpClients
        (
            Action<HttpClient>? client = null, Action<IHttpClientBuilder>? builder = null)
        {
            if (client == null)
                client = c => c.BaseAddress = new Uri(ClientUtils.BASE_ADDRESS);

            List<IHttpClientBuilder> builders = new List<IHttpClientBuilder>();

            
            if (builder != null)
                foreach (IHttpClientBuilder instance in builders)
                    builder(instance);

            HttpClientsAdded = true;

            return this;
        }

        /// <summary>
        /// Configures the JsonSerializerSettings
        /// </summary>
        /// <param name="options"></param>
        /// <returns></returns>
        public HostConfiguration ConfigureJsonOptions(Action<JsonSerializerOptions> options)
        {
            options(_jsonOptions);

            return this;
        }

        /// <summary>
        /// Adds tokens to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <param name="token"></param>
        /// <returns></returns>
        public HostConfiguration AddTokens<TTokenBase>(TTokenBase token) where TTokenBase : TokenBase
        {
            return AddTokens(new TTokenBase[]{ token });
        }

        /// <summary>
        /// Adds tokens to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <param name="tokens"></param>
        /// <returns></returns>
        public HostConfiguration AddTokens<TTokenBase>(IEnumerable<TTokenBase> tokens) where TTokenBase : TokenBase
        {
            TokenContainer<TTokenBase> container = new TokenContainer<TTokenBase>(tokens);
            _services.AddSingleton(services => container);

            return this;
        }

        /// <summary>
        /// Adds a token provider to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenProvider"></typeparam>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <returns></returns>
        public HostConfiguration UseProvider<TTokenProvider, TTokenBase>() 
            where TTokenProvider : TokenProvider<TTokenBase>
            where TTokenBase : TokenBase
        {
            _services.AddSingleton<TTokenProvider>();
            _services.AddSingleton<TokenProvider<TTokenBase>>(services => services.GetRequiredService<TTokenProvider>());

            return this;
        }
    }
}
