// <auto-generated>
/*
 * Ais-Stream WebsocketObjects
 *
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// AddressedSafetyMessage
    /// </summary>
    public partial class AddressedSafetyMessage : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddressedSafetyMessage" /> class.
        /// </summary>
        /// <param name="messageID">messageID</param>
        /// <param name="repeatIndicator">repeatIndicator</param>
        /// <param name="userID">userID</param>
        /// <param name="valid">valid</param>
        /// <param name="sequenceinteger">sequenceinteger</param>
        /// <param name="destinationID">destinationID</param>
        /// <param name="retransmission">retransmission</param>
        /// <param name="spare">spare</param>
        /// <param name="text">text</param>
        [JsonConstructor]
        public AddressedSafetyMessage(int messageID, int repeatIndicator, int userID, bool valid, int sequenceinteger, int destinationID, bool retransmission, bool spare, string text)
        {
            MessageID = messageID;
            RepeatIndicator = repeatIndicator;
            UserID = userID;
            Valid = valid;
            Sequenceinteger = sequenceinteger;
            DestinationID = destinationID;
            Retransmission = retransmission;
            Spare = spare;
            Text = text;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets MessageID
        /// </summary>
        [JsonPropertyName("MessageID")]
        public int MessageID { get; set; }

        /// <summary>
        /// Gets or Sets RepeatIndicator
        /// </summary>
        [JsonPropertyName("RepeatIndicator")]
        public int RepeatIndicator { get; set; }

        /// <summary>
        /// Gets or Sets UserID
        /// </summary>
        [JsonPropertyName("UserID")]
        public int UserID { get; set; }

        /// <summary>
        /// Gets or Sets Valid
        /// </summary>
        [JsonPropertyName("Valid")]
        public bool Valid { get; set; }

        /// <summary>
        /// Gets or Sets Sequenceinteger
        /// </summary>
        [JsonPropertyName("Sequenceinteger")]
        public int Sequenceinteger { get; set; }

        /// <summary>
        /// Gets or Sets DestinationID
        /// </summary>
        [JsonPropertyName("DestinationID")]
        public int DestinationID { get; set; }

        /// <summary>
        /// Gets or Sets Retransmission
        /// </summary>
        [JsonPropertyName("Retransmission")]
        public bool Retransmission { get; set; }

        /// <summary>
        /// Gets or Sets Spare
        /// </summary>
        [JsonPropertyName("Spare")]
        public bool Spare { get; set; }

        /// <summary>
        /// Gets or Sets Text
        /// </summary>
        [JsonPropertyName("Text")]
        public string Text { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AddressedSafetyMessage {\n");
            sb.Append("  MessageID: ").Append(MessageID).Append("\n");
            sb.Append("  RepeatIndicator: ").Append(RepeatIndicator).Append("\n");
            sb.Append("  UserID: ").Append(UserID).Append("\n");
            sb.Append("  Valid: ").Append(Valid).Append("\n");
            sb.Append("  Sequenceinteger: ").Append(Sequenceinteger).Append("\n");
            sb.Append("  DestinationID: ").Append(DestinationID).Append("\n");
            sb.Append("  Retransmission: ").Append(Retransmission).Append("\n");
            sb.Append("  Spare: ").Append(Spare).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AddressedSafetyMessage" />
    /// </summary>
    public class AddressedSafetyMessageJsonConverter : JsonConverter<AddressedSafetyMessage>
    {
        /// <summary>
        /// Deserializes json to <see cref="AddressedSafetyMessage" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AddressedSafetyMessage Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> messageID = default;
            Option<int?> repeatIndicator = default;
            Option<int?> userID = default;
            Option<bool?> valid = default;
            Option<int?> sequenceinteger = default;
            Option<int?> destinationID = default;
            Option<bool?> retransmission = default;
            Option<bool?> spare = default;
            Option<string?> text = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "MessageID":
                            messageID = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "RepeatIndicator":
                            repeatIndicator = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "UserID":
                            userID = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "Valid":
                            valid = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "Sequenceinteger":
                            sequenceinteger = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "DestinationID":
                            destinationID = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "Retransmission":
                            retransmission = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "Spare":
                            spare = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "Text":
                            text = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!messageID.IsSet)
                throw new ArgumentException("Property is required for class AddressedSafetyMessage.", nameof(messageID));

            if (!repeatIndicator.IsSet)
                throw new ArgumentException("Property is required for class AddressedSafetyMessage.", nameof(repeatIndicator));

            if (!userID.IsSet)
                throw new ArgumentException("Property is required for class AddressedSafetyMessage.", nameof(userID));

            if (!valid.IsSet)
                throw new ArgumentException("Property is required for class AddressedSafetyMessage.", nameof(valid));

            if (!sequenceinteger.IsSet)
                throw new ArgumentException("Property is required for class AddressedSafetyMessage.", nameof(sequenceinteger));

            if (!destinationID.IsSet)
                throw new ArgumentException("Property is required for class AddressedSafetyMessage.", nameof(destinationID));

            if (!retransmission.IsSet)
                throw new ArgumentException("Property is required for class AddressedSafetyMessage.", nameof(retransmission));

            if (!spare.IsSet)
                throw new ArgumentException("Property is required for class AddressedSafetyMessage.", nameof(spare));

            if (!text.IsSet)
                throw new ArgumentException("Property is required for class AddressedSafetyMessage.", nameof(text));

            if (messageID.IsSet && messageID.Value == null)
                throw new ArgumentNullException(nameof(messageID), "Property is not nullable for class AddressedSafetyMessage.");

            if (repeatIndicator.IsSet && repeatIndicator.Value == null)
                throw new ArgumentNullException(nameof(repeatIndicator), "Property is not nullable for class AddressedSafetyMessage.");

            if (userID.IsSet && userID.Value == null)
                throw new ArgumentNullException(nameof(userID), "Property is not nullable for class AddressedSafetyMessage.");

            if (valid.IsSet && valid.Value == null)
                throw new ArgumentNullException(nameof(valid), "Property is not nullable for class AddressedSafetyMessage.");

            if (sequenceinteger.IsSet && sequenceinteger.Value == null)
                throw new ArgumentNullException(nameof(sequenceinteger), "Property is not nullable for class AddressedSafetyMessage.");

            if (destinationID.IsSet && destinationID.Value == null)
                throw new ArgumentNullException(nameof(destinationID), "Property is not nullable for class AddressedSafetyMessage.");

            if (retransmission.IsSet && retransmission.Value == null)
                throw new ArgumentNullException(nameof(retransmission), "Property is not nullable for class AddressedSafetyMessage.");

            if (spare.IsSet && spare.Value == null)
                throw new ArgumentNullException(nameof(spare), "Property is not nullable for class AddressedSafetyMessage.");

            if (text.IsSet && text.Value == null)
                throw new ArgumentNullException(nameof(text), "Property is not nullable for class AddressedSafetyMessage.");

            return new AddressedSafetyMessage(messageID.Value!.Value!, repeatIndicator.Value!.Value!, userID.Value!.Value!, valid.Value!.Value!, sequenceinteger.Value!.Value!, destinationID.Value!.Value!, retransmission.Value!.Value!, spare.Value!.Value!, text.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="AddressedSafetyMessage" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="addressedSafetyMessage"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AddressedSafetyMessage addressedSafetyMessage, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, addressedSafetyMessage, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AddressedSafetyMessage" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="addressedSafetyMessage"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AddressedSafetyMessage addressedSafetyMessage, JsonSerializerOptions jsonSerializerOptions)
        {
            if (addressedSafetyMessage.Text == null)
                throw new ArgumentNullException(nameof(addressedSafetyMessage.Text), "Property is required for class AddressedSafetyMessage.");

            writer.WriteNumber("MessageID", addressedSafetyMessage.MessageID);

            writer.WriteNumber("RepeatIndicator", addressedSafetyMessage.RepeatIndicator);

            writer.WriteNumber("UserID", addressedSafetyMessage.UserID);

            writer.WriteBoolean("Valid", addressedSafetyMessage.Valid);

            writer.WriteNumber("Sequenceinteger", addressedSafetyMessage.Sequenceinteger);

            writer.WriteNumber("DestinationID", addressedSafetyMessage.DestinationID);

            writer.WriteBoolean("Retransmission", addressedSafetyMessage.Retransmission);

            writer.WriteBoolean("Spare", addressedSafetyMessage.Spare);

            writer.WriteString("Text", addressedSafetyMessage.Text);
        }
    }
}
