// <auto-generated>
/*
 * Ais-Stream WebsocketObjects
 *
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// AidsToNavigationReport
    /// </summary>
    public partial class AidsToNavigationReport : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AidsToNavigationReport" /> class.
        /// </summary>
        /// <param name="messageID">messageID</param>
        /// <param name="repeatIndicator">repeatIndicator</param>
        /// <param name="userID">userID</param>
        /// <param name="valid">valid</param>
        /// <param name="type">type</param>
        /// <param name="name">name</param>
        /// <param name="positionAccuracy">positionAccuracy</param>
        /// <param name="longitude">longitude</param>
        /// <param name="latitude">latitude</param>
        /// <param name="dimension">dimension</param>
        /// <param name="fixtype">fixtype</param>
        /// <param name="timestamp">timestamp</param>
        /// <param name="offPosition">offPosition</param>
        /// <param name="atoN">atoN</param>
        /// <param name="raim">raim</param>
        /// <param name="virtualAtoN">virtualAtoN</param>
        /// <param name="assignedMode">assignedMode</param>
        /// <param name="spare">spare</param>
        /// <param name="nameExtension">nameExtension</param>
        [JsonConstructor]
        public AidsToNavigationReport(int messageID, int repeatIndicator, int userID, bool valid, int type, string name, bool positionAccuracy, double longitude, double latitude, ShipStaticDataDimension dimension, int fixtype, int timestamp, bool offPosition, int atoN, bool raim, bool virtualAtoN, bool assignedMode, bool spare, string nameExtension)
        {
            MessageID = messageID;
            RepeatIndicator = repeatIndicator;
            UserID = userID;
            Valid = valid;
            Type = type;
            Name = name;
            PositionAccuracy = positionAccuracy;
            Longitude = longitude;
            Latitude = latitude;
            Dimension = dimension;
            Fixtype = fixtype;
            Timestamp = timestamp;
            OffPosition = offPosition;
            AtoN = atoN;
            Raim = raim;
            VirtualAtoN = virtualAtoN;
            AssignedMode = assignedMode;
            Spare = spare;
            NameExtension = nameExtension;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets MessageID
        /// </summary>
        [JsonPropertyName("MessageID")]
        public int MessageID { get; set; }

        /// <summary>
        /// Gets or Sets RepeatIndicator
        /// </summary>
        [JsonPropertyName("RepeatIndicator")]
        public int RepeatIndicator { get; set; }

        /// <summary>
        /// Gets or Sets UserID
        /// </summary>
        [JsonPropertyName("UserID")]
        public int UserID { get; set; }

        /// <summary>
        /// Gets or Sets Valid
        /// </summary>
        [JsonPropertyName("Valid")]
        public bool Valid { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("Type")]
        public int Type { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("Name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets PositionAccuracy
        /// </summary>
        [JsonPropertyName("PositionAccuracy")]
        public bool PositionAccuracy { get; set; }

        /// <summary>
        /// Gets or Sets Longitude
        /// </summary>
        [JsonPropertyName("Longitude")]
        public double Longitude { get; set; }

        /// <summary>
        /// Gets or Sets Latitude
        /// </summary>
        [JsonPropertyName("Latitude")]
        public double Latitude { get; set; }

        /// <summary>
        /// Gets or Sets Dimension
        /// </summary>
        [JsonPropertyName("Dimension")]
        public ShipStaticDataDimension Dimension { get; set; }

        /// <summary>
        /// Gets or Sets Fixtype
        /// </summary>
        [JsonPropertyName("Fixtype")]
        public int Fixtype { get; set; }

        /// <summary>
        /// Gets or Sets Timestamp
        /// </summary>
        [JsonPropertyName("Timestamp")]
        public int Timestamp { get; set; }

        /// <summary>
        /// Gets or Sets OffPosition
        /// </summary>
        [JsonPropertyName("OffPosition")]
        public bool OffPosition { get; set; }

        /// <summary>
        /// Gets or Sets AtoN
        /// </summary>
        [JsonPropertyName("AtoN")]
        public int AtoN { get; set; }

        /// <summary>
        /// Gets or Sets Raim
        /// </summary>
        [JsonPropertyName("Raim")]
        public bool Raim { get; set; }

        /// <summary>
        /// Gets or Sets VirtualAtoN
        /// </summary>
        [JsonPropertyName("VirtualAtoN")]
        public bool VirtualAtoN { get; set; }

        /// <summary>
        /// Gets or Sets AssignedMode
        /// </summary>
        [JsonPropertyName("AssignedMode")]
        public bool AssignedMode { get; set; }

        /// <summary>
        /// Gets or Sets Spare
        /// </summary>
        [JsonPropertyName("Spare")]
        public bool Spare { get; set; }

        /// <summary>
        /// Gets or Sets NameExtension
        /// </summary>
        [JsonPropertyName("NameExtension")]
        public string NameExtension { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AidsToNavigationReport {\n");
            sb.Append("  MessageID: ").Append(MessageID).Append("\n");
            sb.Append("  RepeatIndicator: ").Append(RepeatIndicator).Append("\n");
            sb.Append("  UserID: ").Append(UserID).Append("\n");
            sb.Append("  Valid: ").Append(Valid).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  PositionAccuracy: ").Append(PositionAccuracy).Append("\n");
            sb.Append("  Longitude: ").Append(Longitude).Append("\n");
            sb.Append("  Latitude: ").Append(Latitude).Append("\n");
            sb.Append("  Dimension: ").Append(Dimension).Append("\n");
            sb.Append("  Fixtype: ").Append(Fixtype).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  OffPosition: ").Append(OffPosition).Append("\n");
            sb.Append("  AtoN: ").Append(AtoN).Append("\n");
            sb.Append("  Raim: ").Append(Raim).Append("\n");
            sb.Append("  VirtualAtoN: ").Append(VirtualAtoN).Append("\n");
            sb.Append("  AssignedMode: ").Append(AssignedMode).Append("\n");
            sb.Append("  Spare: ").Append(Spare).Append("\n");
            sb.Append("  NameExtension: ").Append(NameExtension).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AidsToNavigationReport" />
    /// </summary>
    public class AidsToNavigationReportJsonConverter : JsonConverter<AidsToNavigationReport>
    {
        /// <summary>
        /// Deserializes json to <see cref="AidsToNavigationReport" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AidsToNavigationReport Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> messageID = default;
            Option<int?> repeatIndicator = default;
            Option<int?> userID = default;
            Option<bool?> valid = default;
            Option<int?> type = default;
            Option<string?> name = default;
            Option<bool?> positionAccuracy = default;
            Option<double?> longitude = default;
            Option<double?> latitude = default;
            Option<ShipStaticDataDimension?> dimension = default;
            Option<int?> fixtype = default;
            Option<int?> timestamp = default;
            Option<bool?> offPosition = default;
            Option<int?> atoN = default;
            Option<bool?> raim = default;
            Option<bool?> virtualAtoN = default;
            Option<bool?> assignedMode = default;
            Option<bool?> spare = default;
            Option<string?> nameExtension = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "MessageID":
                            messageID = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "RepeatIndicator":
                            repeatIndicator = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "UserID":
                            userID = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "Valid":
                            valid = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "Type":
                            type = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "Name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "PositionAccuracy":
                            positionAccuracy = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "Longitude":
                            longitude = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "Latitude":
                            latitude = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "Dimension":
                            dimension = new Option<ShipStaticDataDimension?>(JsonSerializer.Deserialize<ShipStaticDataDimension>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "Fixtype":
                            fixtype = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "Timestamp":
                            timestamp = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "OffPosition":
                            offPosition = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "AtoN":
                            atoN = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "Raim":
                            raim = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "VirtualAtoN":
                            virtualAtoN = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "AssignedMode":
                            assignedMode = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "Spare":
                            spare = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "NameExtension":
                            nameExtension = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!messageID.IsSet)
                throw new ArgumentException("Property is required for class AidsToNavigationReport.", nameof(messageID));

            if (!repeatIndicator.IsSet)
                throw new ArgumentException("Property is required for class AidsToNavigationReport.", nameof(repeatIndicator));

            if (!userID.IsSet)
                throw new ArgumentException("Property is required for class AidsToNavigationReport.", nameof(userID));

            if (!valid.IsSet)
                throw new ArgumentException("Property is required for class AidsToNavigationReport.", nameof(valid));

            if (!type.IsSet)
                throw new ArgumentException("Property is required for class AidsToNavigationReport.", nameof(type));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class AidsToNavigationReport.", nameof(name));

            if (!positionAccuracy.IsSet)
                throw new ArgumentException("Property is required for class AidsToNavigationReport.", nameof(positionAccuracy));

            if (!longitude.IsSet)
                throw new ArgumentException("Property is required for class AidsToNavigationReport.", nameof(longitude));

            if (!latitude.IsSet)
                throw new ArgumentException("Property is required for class AidsToNavigationReport.", nameof(latitude));

            if (!dimension.IsSet)
                throw new ArgumentException("Property is required for class AidsToNavigationReport.", nameof(dimension));

            if (!fixtype.IsSet)
                throw new ArgumentException("Property is required for class AidsToNavigationReport.", nameof(fixtype));

            if (!timestamp.IsSet)
                throw new ArgumentException("Property is required for class AidsToNavigationReport.", nameof(timestamp));

            if (!offPosition.IsSet)
                throw new ArgumentException("Property is required for class AidsToNavigationReport.", nameof(offPosition));

            if (!atoN.IsSet)
                throw new ArgumentException("Property is required for class AidsToNavigationReport.", nameof(atoN));

            if (!raim.IsSet)
                throw new ArgumentException("Property is required for class AidsToNavigationReport.", nameof(raim));

            if (!virtualAtoN.IsSet)
                throw new ArgumentException("Property is required for class AidsToNavigationReport.", nameof(virtualAtoN));

            if (!assignedMode.IsSet)
                throw new ArgumentException("Property is required for class AidsToNavigationReport.", nameof(assignedMode));

            if (!spare.IsSet)
                throw new ArgumentException("Property is required for class AidsToNavigationReport.", nameof(spare));

            if (!nameExtension.IsSet)
                throw new ArgumentException("Property is required for class AidsToNavigationReport.", nameof(nameExtension));

            if (messageID.IsSet && messageID.Value == null)
                throw new ArgumentNullException(nameof(messageID), "Property is not nullable for class AidsToNavigationReport.");

            if (repeatIndicator.IsSet && repeatIndicator.Value == null)
                throw new ArgumentNullException(nameof(repeatIndicator), "Property is not nullable for class AidsToNavigationReport.");

            if (userID.IsSet && userID.Value == null)
                throw new ArgumentNullException(nameof(userID), "Property is not nullable for class AidsToNavigationReport.");

            if (valid.IsSet && valid.Value == null)
                throw new ArgumentNullException(nameof(valid), "Property is not nullable for class AidsToNavigationReport.");

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class AidsToNavigationReport.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class AidsToNavigationReport.");

            if (positionAccuracy.IsSet && positionAccuracy.Value == null)
                throw new ArgumentNullException(nameof(positionAccuracy), "Property is not nullable for class AidsToNavigationReport.");

            if (longitude.IsSet && longitude.Value == null)
                throw new ArgumentNullException(nameof(longitude), "Property is not nullable for class AidsToNavigationReport.");

            if (latitude.IsSet && latitude.Value == null)
                throw new ArgumentNullException(nameof(latitude), "Property is not nullable for class AidsToNavigationReport.");

            if (dimension.IsSet && dimension.Value == null)
                throw new ArgumentNullException(nameof(dimension), "Property is not nullable for class AidsToNavigationReport.");

            if (fixtype.IsSet && fixtype.Value == null)
                throw new ArgumentNullException(nameof(fixtype), "Property is not nullable for class AidsToNavigationReport.");

            if (timestamp.IsSet && timestamp.Value == null)
                throw new ArgumentNullException(nameof(timestamp), "Property is not nullable for class AidsToNavigationReport.");

            if (offPosition.IsSet && offPosition.Value == null)
                throw new ArgumentNullException(nameof(offPosition), "Property is not nullable for class AidsToNavigationReport.");

            if (atoN.IsSet && atoN.Value == null)
                throw new ArgumentNullException(nameof(atoN), "Property is not nullable for class AidsToNavigationReport.");

            if (raim.IsSet && raim.Value == null)
                throw new ArgumentNullException(nameof(raim), "Property is not nullable for class AidsToNavigationReport.");

            if (virtualAtoN.IsSet && virtualAtoN.Value == null)
                throw new ArgumentNullException(nameof(virtualAtoN), "Property is not nullable for class AidsToNavigationReport.");

            if (assignedMode.IsSet && assignedMode.Value == null)
                throw new ArgumentNullException(nameof(assignedMode), "Property is not nullable for class AidsToNavigationReport.");

            if (spare.IsSet && spare.Value == null)
                throw new ArgumentNullException(nameof(spare), "Property is not nullable for class AidsToNavigationReport.");

            if (nameExtension.IsSet && nameExtension.Value == null)
                throw new ArgumentNullException(nameof(nameExtension), "Property is not nullable for class AidsToNavigationReport.");

            return new AidsToNavigationReport(messageID.Value!.Value!, repeatIndicator.Value!.Value!, userID.Value!.Value!, valid.Value!.Value!, type.Value!.Value!, name.Value!, positionAccuracy.Value!.Value!, longitude.Value!.Value!, latitude.Value!.Value!, dimension.Value!, fixtype.Value!.Value!, timestamp.Value!.Value!, offPosition.Value!.Value!, atoN.Value!.Value!, raim.Value!.Value!, virtualAtoN.Value!.Value!, assignedMode.Value!.Value!, spare.Value!.Value!, nameExtension.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="AidsToNavigationReport" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="aidsToNavigationReport"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AidsToNavigationReport aidsToNavigationReport, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, aidsToNavigationReport, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AidsToNavigationReport" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="aidsToNavigationReport"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AidsToNavigationReport aidsToNavigationReport, JsonSerializerOptions jsonSerializerOptions)
        {
            if (aidsToNavigationReport.Name == null)
                throw new ArgumentNullException(nameof(aidsToNavigationReport.Name), "Property is required for class AidsToNavigationReport.");

            if (aidsToNavigationReport.Dimension == null)
                throw new ArgumentNullException(nameof(aidsToNavigationReport.Dimension), "Property is required for class AidsToNavigationReport.");

            if (aidsToNavigationReport.NameExtension == null)
                throw new ArgumentNullException(nameof(aidsToNavigationReport.NameExtension), "Property is required for class AidsToNavigationReport.");

            writer.WriteNumber("MessageID", aidsToNavigationReport.MessageID);

            writer.WriteNumber("RepeatIndicator", aidsToNavigationReport.RepeatIndicator);

            writer.WriteNumber("UserID", aidsToNavigationReport.UserID);

            writer.WriteBoolean("Valid", aidsToNavigationReport.Valid);

            writer.WriteNumber("Type", aidsToNavigationReport.Type);

            writer.WriteString("Name", aidsToNavigationReport.Name);

            writer.WriteBoolean("PositionAccuracy", aidsToNavigationReport.PositionAccuracy);

            writer.WriteNumber("Longitude", aidsToNavigationReport.Longitude);

            writer.WriteNumber("Latitude", aidsToNavigationReport.Latitude);

            writer.WritePropertyName("Dimension");
            JsonSerializer.Serialize(writer, aidsToNavigationReport.Dimension, jsonSerializerOptions);
            writer.WriteNumber("Fixtype", aidsToNavigationReport.Fixtype);

            writer.WriteNumber("Timestamp", aidsToNavigationReport.Timestamp);

            writer.WriteBoolean("OffPosition", aidsToNavigationReport.OffPosition);

            writer.WriteNumber("AtoN", aidsToNavigationReport.AtoN);

            writer.WriteBoolean("Raim", aidsToNavigationReport.Raim);

            writer.WriteBoolean("VirtualAtoN", aidsToNavigationReport.VirtualAtoN);

            writer.WriteBoolean("AssignedMode", aidsToNavigationReport.AssignedMode);

            writer.WriteBoolean("Spare", aidsToNavigationReport.Spare);

            writer.WriteString("NameExtension", aidsToNavigationReport.NameExtension);
        }
    }
}
