// <auto-generated>
/*
 * Ais-Stream WebsocketObjects
 *
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// AisStreamMessageMessage
    /// </summary>
    public partial class AisStreamMessageMessage : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AisStreamMessageMessage" /> class.
        /// </summary>
        /// <param name="positionReport">positionReport</param>
        /// <param name="unknownMessage">unknownMessage</param>
        /// <param name="addressedSafetyMessage">addressedSafetyMessage</param>
        /// <param name="addressedBinaryMessage">addressedBinaryMessage</param>
        /// <param name="aidsToNavigationReport">aidsToNavigationReport</param>
        /// <param name="assignedModeCommand">assignedModeCommand</param>
        /// <param name="baseStationReport">baseStationReport</param>
        /// <param name="binaryAcknowledge">binaryAcknowledge</param>
        /// <param name="binaryBroadcastMessage">binaryBroadcastMessage</param>
        /// <param name="channelManagement">channelManagement</param>
        /// <param name="coordinatedUTCInquiry">coordinatedUTCInquiry</param>
        /// <param name="dataLinkManagementMessage">dataLinkManagementMessage</param>
        /// <param name="dataLinkManagementMessageData">dataLinkManagementMessageData</param>
        /// <param name="extendedClassBPositionReport">extendedClassBPositionReport</param>
        /// <param name="gnssBroadcastBinaryMessage">gnssBroadcastBinaryMessage</param>
        /// <param name="groupAssignmentCommand">groupAssignmentCommand</param>
        /// <param name="interrogation">interrogation</param>
        /// <param name="longRangeAisBroadcastMessage">longRangeAisBroadcastMessage</param>
        /// <param name="multiSlotBinaryMessage">multiSlotBinaryMessage</param>
        /// <param name="safetyBroadcastMessage">safetyBroadcastMessage</param>
        /// <param name="shipStaticData">shipStaticData</param>
        /// <param name="singleSlotBinaryMessage">singleSlotBinaryMessage</param>
        /// <param name="standardClassBPositionReport">standardClassBPositionReport</param>
        /// <param name="standardSearchAndRescueAircraftReport">standardSearchAndRescueAircraftReport</param>
        /// <param name="staticDataReport">staticDataReport</param>
        [JsonConstructor]
        public AisStreamMessageMessage(Option<PositionReport?> positionReport = default, Option<UnknownMessage?> unknownMessage = default, Option<AddressedSafetyMessage?> addressedSafetyMessage = default, Option<AddressedBinaryMessage?> addressedBinaryMessage = default, Option<AidsToNavigationReport?> aidsToNavigationReport = default, Option<AssignedModeCommand?> assignedModeCommand = default, Option<BaseStationReport?> baseStationReport = default, Option<BinaryAcknowledge?> binaryAcknowledge = default, Option<BinaryBroadcastMessage?> binaryBroadcastMessage = default, Option<ChannelManagement?> channelManagement = default, Option<CoordinatedUTCInquiry?> coordinatedUTCInquiry = default, Option<DataLinkManagementMessage?> dataLinkManagementMessage = default, Option<DataLinkManagementMessageData?> dataLinkManagementMessageData = default, Option<ExtendedClassBPositionReport?> extendedClassBPositionReport = default, Option<GnssBroadcastBinaryMessage?> gnssBroadcastBinaryMessage = default, Option<GroupAssignmentCommand?> groupAssignmentCommand = default, Option<Interrogation?> interrogation = default, Option<LongRangeAisBroadcastMessage?> longRangeAisBroadcastMessage = default, Option<MultiSlotBinaryMessage?> multiSlotBinaryMessage = default, Option<SafetyBroadcastMessage?> safetyBroadcastMessage = default, Option<ShipStaticData?> shipStaticData = default, Option<SingleSlotBinaryMessage?> singleSlotBinaryMessage = default, Option<StandardClassBPositionReport?> standardClassBPositionReport = default, Option<StandardSearchAndRescueAircraftReport?> standardSearchAndRescueAircraftReport = default, Option<StaticDataReport?> staticDataReport = default)
        {
            PositionReportOption = positionReport;
            UnknownMessageOption = unknownMessage;
            AddressedSafetyMessageOption = addressedSafetyMessage;
            AddressedBinaryMessageOption = addressedBinaryMessage;
            AidsToNavigationReportOption = aidsToNavigationReport;
            AssignedModeCommandOption = assignedModeCommand;
            BaseStationReportOption = baseStationReport;
            BinaryAcknowledgeOption = binaryAcknowledge;
            BinaryBroadcastMessageOption = binaryBroadcastMessage;
            ChannelManagementOption = channelManagement;
            CoordinatedUTCInquiryOption = coordinatedUTCInquiry;
            DataLinkManagementMessageOption = dataLinkManagementMessage;
            DataLinkManagementMessageDataOption = dataLinkManagementMessageData;
            ExtendedClassBPositionReportOption = extendedClassBPositionReport;
            GnssBroadcastBinaryMessageOption = gnssBroadcastBinaryMessage;
            GroupAssignmentCommandOption = groupAssignmentCommand;
            InterrogationOption = interrogation;
            LongRangeAisBroadcastMessageOption = longRangeAisBroadcastMessage;
            MultiSlotBinaryMessageOption = multiSlotBinaryMessage;
            SafetyBroadcastMessageOption = safetyBroadcastMessage;
            ShipStaticDataOption = shipStaticData;
            SingleSlotBinaryMessageOption = singleSlotBinaryMessage;
            StandardClassBPositionReportOption = standardClassBPositionReport;
            StandardSearchAndRescueAircraftReportOption = standardSearchAndRescueAircraftReport;
            StaticDataReportOption = staticDataReport;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of PositionReport
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<PositionReport?> PositionReportOption { get; private set; }

        /// <summary>
        /// Gets or Sets PositionReport
        /// </summary>
        [JsonPropertyName("PositionReport")]
        public PositionReport? PositionReport { get { return this.PositionReportOption; } set { this.PositionReportOption = new(value); } }

        /// <summary>
        /// Used to track the state of UnknownMessage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<UnknownMessage?> UnknownMessageOption { get; private set; }

        /// <summary>
        /// Gets or Sets UnknownMessage
        /// </summary>
        [JsonPropertyName("UnknownMessage")]
        public UnknownMessage? UnknownMessage { get { return this.UnknownMessageOption; } set { this.UnknownMessageOption = new(value); } }

        /// <summary>
        /// Used to track the state of AddressedSafetyMessage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<AddressedSafetyMessage?> AddressedSafetyMessageOption { get; private set; }

        /// <summary>
        /// Gets or Sets AddressedSafetyMessage
        /// </summary>
        [JsonPropertyName("AddressedSafetyMessage")]
        public AddressedSafetyMessage? AddressedSafetyMessage { get { return this.AddressedSafetyMessageOption; } set { this.AddressedSafetyMessageOption = new(value); } }

        /// <summary>
        /// Used to track the state of AddressedBinaryMessage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<AddressedBinaryMessage?> AddressedBinaryMessageOption { get; private set; }

        /// <summary>
        /// Gets or Sets AddressedBinaryMessage
        /// </summary>
        [JsonPropertyName("AddressedBinaryMessage")]
        public AddressedBinaryMessage? AddressedBinaryMessage { get { return this.AddressedBinaryMessageOption; } set { this.AddressedBinaryMessageOption = new(value); } }

        /// <summary>
        /// Used to track the state of AidsToNavigationReport
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<AidsToNavigationReport?> AidsToNavigationReportOption { get; private set; }

        /// <summary>
        /// Gets or Sets AidsToNavigationReport
        /// </summary>
        [JsonPropertyName("AidsToNavigationReport")]
        public AidsToNavigationReport? AidsToNavigationReport { get { return this.AidsToNavigationReportOption; } set { this.AidsToNavigationReportOption = new(value); } }

        /// <summary>
        /// Used to track the state of AssignedModeCommand
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<AssignedModeCommand?> AssignedModeCommandOption { get; private set; }

        /// <summary>
        /// Gets or Sets AssignedModeCommand
        /// </summary>
        [JsonPropertyName("AssignedModeCommand")]
        public AssignedModeCommand? AssignedModeCommand { get { return this.AssignedModeCommandOption; } set { this.AssignedModeCommandOption = new(value); } }

        /// <summary>
        /// Used to track the state of BaseStationReport
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<BaseStationReport?> BaseStationReportOption { get; private set; }

        /// <summary>
        /// Gets or Sets BaseStationReport
        /// </summary>
        [JsonPropertyName("BaseStationReport")]
        public BaseStationReport? BaseStationReport { get { return this.BaseStationReportOption; } set { this.BaseStationReportOption = new(value); } }

        /// <summary>
        /// Used to track the state of BinaryAcknowledge
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<BinaryAcknowledge?> BinaryAcknowledgeOption { get; private set; }

        /// <summary>
        /// Gets or Sets BinaryAcknowledge
        /// </summary>
        [JsonPropertyName("BinaryAcknowledge")]
        public BinaryAcknowledge? BinaryAcknowledge { get { return this.BinaryAcknowledgeOption; } set { this.BinaryAcknowledgeOption = new(value); } }

        /// <summary>
        /// Used to track the state of BinaryBroadcastMessage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<BinaryBroadcastMessage?> BinaryBroadcastMessageOption { get; private set; }

        /// <summary>
        /// Gets or Sets BinaryBroadcastMessage
        /// </summary>
        [JsonPropertyName("BinaryBroadcastMessage")]
        public BinaryBroadcastMessage? BinaryBroadcastMessage { get { return this.BinaryBroadcastMessageOption; } set { this.BinaryBroadcastMessageOption = new(value); } }

        /// <summary>
        /// Used to track the state of ChannelManagement
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ChannelManagement?> ChannelManagementOption { get; private set; }

        /// <summary>
        /// Gets or Sets ChannelManagement
        /// </summary>
        [JsonPropertyName("ChannelManagement")]
        public ChannelManagement? ChannelManagement { get { return this.ChannelManagementOption; } set { this.ChannelManagementOption = new(value); } }

        /// <summary>
        /// Used to track the state of CoordinatedUTCInquiry
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<CoordinatedUTCInquiry?> CoordinatedUTCInquiryOption { get; private set; }

        /// <summary>
        /// Gets or Sets CoordinatedUTCInquiry
        /// </summary>
        [JsonPropertyName("CoordinatedUTCInquiry")]
        public CoordinatedUTCInquiry? CoordinatedUTCInquiry { get { return this.CoordinatedUTCInquiryOption; } set { this.CoordinatedUTCInquiryOption = new(value); } }

        /// <summary>
        /// Used to track the state of DataLinkManagementMessage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DataLinkManagementMessage?> DataLinkManagementMessageOption { get; private set; }

        /// <summary>
        /// Gets or Sets DataLinkManagementMessage
        /// </summary>
        [JsonPropertyName("DataLinkManagementMessage")]
        public DataLinkManagementMessage? DataLinkManagementMessage { get { return this.DataLinkManagementMessageOption; } set { this.DataLinkManagementMessageOption = new(value); } }

        /// <summary>
        /// Used to track the state of DataLinkManagementMessageData
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DataLinkManagementMessageData?> DataLinkManagementMessageDataOption { get; private set; }

        /// <summary>
        /// Gets or Sets DataLinkManagementMessageData
        /// </summary>
        [JsonPropertyName("DataLinkManagementMessageData")]
        public DataLinkManagementMessageData? DataLinkManagementMessageData { get { return this.DataLinkManagementMessageDataOption; } set { this.DataLinkManagementMessageDataOption = new(value); } }

        /// <summary>
        /// Used to track the state of ExtendedClassBPositionReport
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ExtendedClassBPositionReport?> ExtendedClassBPositionReportOption { get; private set; }

        /// <summary>
        /// Gets or Sets ExtendedClassBPositionReport
        /// </summary>
        [JsonPropertyName("ExtendedClassBPositionReport")]
        public ExtendedClassBPositionReport? ExtendedClassBPositionReport { get { return this.ExtendedClassBPositionReportOption; } set { this.ExtendedClassBPositionReportOption = new(value); } }

        /// <summary>
        /// Used to track the state of GnssBroadcastBinaryMessage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<GnssBroadcastBinaryMessage?> GnssBroadcastBinaryMessageOption { get; private set; }

        /// <summary>
        /// Gets or Sets GnssBroadcastBinaryMessage
        /// </summary>
        [JsonPropertyName("GnssBroadcastBinaryMessage")]
        public GnssBroadcastBinaryMessage? GnssBroadcastBinaryMessage { get { return this.GnssBroadcastBinaryMessageOption; } set { this.GnssBroadcastBinaryMessageOption = new(value); } }

        /// <summary>
        /// Used to track the state of GroupAssignmentCommand
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<GroupAssignmentCommand?> GroupAssignmentCommandOption { get; private set; }

        /// <summary>
        /// Gets or Sets GroupAssignmentCommand
        /// </summary>
        [JsonPropertyName("GroupAssignmentCommand")]
        public GroupAssignmentCommand? GroupAssignmentCommand { get { return this.GroupAssignmentCommandOption; } set { this.GroupAssignmentCommandOption = new(value); } }

        /// <summary>
        /// Used to track the state of Interrogation
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Interrogation?> InterrogationOption { get; private set; }

        /// <summary>
        /// Gets or Sets Interrogation
        /// </summary>
        [JsonPropertyName("Interrogation")]
        public Interrogation? Interrogation { get { return this.InterrogationOption; } set { this.InterrogationOption = new(value); } }

        /// <summary>
        /// Used to track the state of LongRangeAisBroadcastMessage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<LongRangeAisBroadcastMessage?> LongRangeAisBroadcastMessageOption { get; private set; }

        /// <summary>
        /// Gets or Sets LongRangeAisBroadcastMessage
        /// </summary>
        [JsonPropertyName("LongRangeAisBroadcastMessage")]
        public LongRangeAisBroadcastMessage? LongRangeAisBroadcastMessage { get { return this.LongRangeAisBroadcastMessageOption; } set { this.LongRangeAisBroadcastMessageOption = new(value); } }

        /// <summary>
        /// Used to track the state of MultiSlotBinaryMessage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<MultiSlotBinaryMessage?> MultiSlotBinaryMessageOption { get; private set; }

        /// <summary>
        /// Gets or Sets MultiSlotBinaryMessage
        /// </summary>
        [JsonPropertyName("MultiSlotBinaryMessage")]
        public MultiSlotBinaryMessage? MultiSlotBinaryMessage { get { return this.MultiSlotBinaryMessageOption; } set { this.MultiSlotBinaryMessageOption = new(value); } }

        /// <summary>
        /// Used to track the state of SafetyBroadcastMessage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<SafetyBroadcastMessage?> SafetyBroadcastMessageOption { get; private set; }

        /// <summary>
        /// Gets or Sets SafetyBroadcastMessage
        /// </summary>
        [JsonPropertyName("SafetyBroadcastMessage")]
        public SafetyBroadcastMessage? SafetyBroadcastMessage { get { return this.SafetyBroadcastMessageOption; } set { this.SafetyBroadcastMessageOption = new(value); } }

        /// <summary>
        /// Used to track the state of ShipStaticData
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ShipStaticData?> ShipStaticDataOption { get; private set; }

        /// <summary>
        /// Gets or Sets ShipStaticData
        /// </summary>
        [JsonPropertyName("ShipStaticData")]
        public ShipStaticData? ShipStaticData { get { return this.ShipStaticDataOption; } set { this.ShipStaticDataOption = new(value); } }

        /// <summary>
        /// Used to track the state of SingleSlotBinaryMessage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<SingleSlotBinaryMessage?> SingleSlotBinaryMessageOption { get; private set; }

        /// <summary>
        /// Gets or Sets SingleSlotBinaryMessage
        /// </summary>
        [JsonPropertyName("SingleSlotBinaryMessage")]
        public SingleSlotBinaryMessage? SingleSlotBinaryMessage { get { return this.SingleSlotBinaryMessageOption; } set { this.SingleSlotBinaryMessageOption = new(value); } }

        /// <summary>
        /// Used to track the state of StandardClassBPositionReport
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<StandardClassBPositionReport?> StandardClassBPositionReportOption { get; private set; }

        /// <summary>
        /// Gets or Sets StandardClassBPositionReport
        /// </summary>
        [JsonPropertyName("StandardClassBPositionReport")]
        public StandardClassBPositionReport? StandardClassBPositionReport { get { return this.StandardClassBPositionReportOption; } set { this.StandardClassBPositionReportOption = new(value); } }

        /// <summary>
        /// Used to track the state of StandardSearchAndRescueAircraftReport
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<StandardSearchAndRescueAircraftReport?> StandardSearchAndRescueAircraftReportOption { get; private set; }

        /// <summary>
        /// Gets or Sets StandardSearchAndRescueAircraftReport
        /// </summary>
        [JsonPropertyName("StandardSearchAndRescueAircraftReport")]
        public StandardSearchAndRescueAircraftReport? StandardSearchAndRescueAircraftReport { get { return this.StandardSearchAndRescueAircraftReportOption; } set { this.StandardSearchAndRescueAircraftReportOption = new(value); } }

        /// <summary>
        /// Used to track the state of StaticDataReport
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<StaticDataReport?> StaticDataReportOption { get; private set; }

        /// <summary>
        /// Gets or Sets StaticDataReport
        /// </summary>
        [JsonPropertyName("StaticDataReport")]
        public StaticDataReport? StaticDataReport { get { return this.StaticDataReportOption; } set { this.StaticDataReportOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AisStreamMessageMessage {\n");
            sb.Append("  PositionReport: ").Append(PositionReport).Append("\n");
            sb.Append("  UnknownMessage: ").Append(UnknownMessage).Append("\n");
            sb.Append("  AddressedSafetyMessage: ").Append(AddressedSafetyMessage).Append("\n");
            sb.Append("  AddressedBinaryMessage: ").Append(AddressedBinaryMessage).Append("\n");
            sb.Append("  AidsToNavigationReport: ").Append(AidsToNavigationReport).Append("\n");
            sb.Append("  AssignedModeCommand: ").Append(AssignedModeCommand).Append("\n");
            sb.Append("  BaseStationReport: ").Append(BaseStationReport).Append("\n");
            sb.Append("  BinaryAcknowledge: ").Append(BinaryAcknowledge).Append("\n");
            sb.Append("  BinaryBroadcastMessage: ").Append(BinaryBroadcastMessage).Append("\n");
            sb.Append("  ChannelManagement: ").Append(ChannelManagement).Append("\n");
            sb.Append("  CoordinatedUTCInquiry: ").Append(CoordinatedUTCInquiry).Append("\n");
            sb.Append("  DataLinkManagementMessage: ").Append(DataLinkManagementMessage).Append("\n");
            sb.Append("  DataLinkManagementMessageData: ").Append(DataLinkManagementMessageData).Append("\n");
            sb.Append("  ExtendedClassBPositionReport: ").Append(ExtendedClassBPositionReport).Append("\n");
            sb.Append("  GnssBroadcastBinaryMessage: ").Append(GnssBroadcastBinaryMessage).Append("\n");
            sb.Append("  GroupAssignmentCommand: ").Append(GroupAssignmentCommand).Append("\n");
            sb.Append("  Interrogation: ").Append(Interrogation).Append("\n");
            sb.Append("  LongRangeAisBroadcastMessage: ").Append(LongRangeAisBroadcastMessage).Append("\n");
            sb.Append("  MultiSlotBinaryMessage: ").Append(MultiSlotBinaryMessage).Append("\n");
            sb.Append("  SafetyBroadcastMessage: ").Append(SafetyBroadcastMessage).Append("\n");
            sb.Append("  ShipStaticData: ").Append(ShipStaticData).Append("\n");
            sb.Append("  SingleSlotBinaryMessage: ").Append(SingleSlotBinaryMessage).Append("\n");
            sb.Append("  StandardClassBPositionReport: ").Append(StandardClassBPositionReport).Append("\n");
            sb.Append("  StandardSearchAndRescueAircraftReport: ").Append(StandardSearchAndRescueAircraftReport).Append("\n");
            sb.Append("  StaticDataReport: ").Append(StaticDataReport).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AisStreamMessageMessage" />
    /// </summary>
    public class AisStreamMessageMessageJsonConverter : JsonConverter<AisStreamMessageMessage>
    {
        /// <summary>
        /// Deserializes json to <see cref="AisStreamMessageMessage" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AisStreamMessageMessage Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<PositionReport?> positionReport = default;
            Option<UnknownMessage?> unknownMessage = default;
            Option<AddressedSafetyMessage?> addressedSafetyMessage = default;
            Option<AddressedBinaryMessage?> addressedBinaryMessage = default;
            Option<AidsToNavigationReport?> aidsToNavigationReport = default;
            Option<AssignedModeCommand?> assignedModeCommand = default;
            Option<BaseStationReport?> baseStationReport = default;
            Option<BinaryAcknowledge?> binaryAcknowledge = default;
            Option<BinaryBroadcastMessage?> binaryBroadcastMessage = default;
            Option<ChannelManagement?> channelManagement = default;
            Option<CoordinatedUTCInquiry?> coordinatedUTCInquiry = default;
            Option<DataLinkManagementMessage?> dataLinkManagementMessage = default;
            Option<DataLinkManagementMessageData?> dataLinkManagementMessageData = default;
            Option<ExtendedClassBPositionReport?> extendedClassBPositionReport = default;
            Option<GnssBroadcastBinaryMessage?> gnssBroadcastBinaryMessage = default;
            Option<GroupAssignmentCommand?> groupAssignmentCommand = default;
            Option<Interrogation?> interrogation = default;
            Option<LongRangeAisBroadcastMessage?> longRangeAisBroadcastMessage = default;
            Option<MultiSlotBinaryMessage?> multiSlotBinaryMessage = default;
            Option<SafetyBroadcastMessage?> safetyBroadcastMessage = default;
            Option<ShipStaticData?> shipStaticData = default;
            Option<SingleSlotBinaryMessage?> singleSlotBinaryMessage = default;
            Option<StandardClassBPositionReport?> standardClassBPositionReport = default;
            Option<StandardSearchAndRescueAircraftReport?> standardSearchAndRescueAircraftReport = default;
            Option<StaticDataReport?> staticDataReport = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "PositionReport":
                            positionReport = new Option<PositionReport?>(JsonSerializer.Deserialize<PositionReport>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "UnknownMessage":
                            unknownMessage = new Option<UnknownMessage?>(JsonSerializer.Deserialize<UnknownMessage>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "AddressedSafetyMessage":
                            addressedSafetyMessage = new Option<AddressedSafetyMessage?>(JsonSerializer.Deserialize<AddressedSafetyMessage>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "AddressedBinaryMessage":
                            addressedBinaryMessage = new Option<AddressedBinaryMessage?>(JsonSerializer.Deserialize<AddressedBinaryMessage>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "AidsToNavigationReport":
                            aidsToNavigationReport = new Option<AidsToNavigationReport?>(JsonSerializer.Deserialize<AidsToNavigationReport>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "AssignedModeCommand":
                            assignedModeCommand = new Option<AssignedModeCommand?>(JsonSerializer.Deserialize<AssignedModeCommand>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "BaseStationReport":
                            baseStationReport = new Option<BaseStationReport?>(JsonSerializer.Deserialize<BaseStationReport>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "BinaryAcknowledge":
                            binaryAcknowledge = new Option<BinaryAcknowledge?>(JsonSerializer.Deserialize<BinaryAcknowledge>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "BinaryBroadcastMessage":
                            binaryBroadcastMessage = new Option<BinaryBroadcastMessage?>(JsonSerializer.Deserialize<BinaryBroadcastMessage>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "ChannelManagement":
                            channelManagement = new Option<ChannelManagement?>(JsonSerializer.Deserialize<ChannelManagement>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "CoordinatedUTCInquiry":
                            coordinatedUTCInquiry = new Option<CoordinatedUTCInquiry?>(JsonSerializer.Deserialize<CoordinatedUTCInquiry>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "DataLinkManagementMessage":
                            dataLinkManagementMessage = new Option<DataLinkManagementMessage?>(JsonSerializer.Deserialize<DataLinkManagementMessage>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "DataLinkManagementMessageData":
                            dataLinkManagementMessageData = new Option<DataLinkManagementMessageData?>(JsonSerializer.Deserialize<DataLinkManagementMessageData>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "ExtendedClassBPositionReport":
                            extendedClassBPositionReport = new Option<ExtendedClassBPositionReport?>(JsonSerializer.Deserialize<ExtendedClassBPositionReport>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "GnssBroadcastBinaryMessage":
                            gnssBroadcastBinaryMessage = new Option<GnssBroadcastBinaryMessage?>(JsonSerializer.Deserialize<GnssBroadcastBinaryMessage>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "GroupAssignmentCommand":
                            groupAssignmentCommand = new Option<GroupAssignmentCommand?>(JsonSerializer.Deserialize<GroupAssignmentCommand>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "Interrogation":
                            interrogation = new Option<Interrogation?>(JsonSerializer.Deserialize<Interrogation>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "LongRangeAisBroadcastMessage":
                            longRangeAisBroadcastMessage = new Option<LongRangeAisBroadcastMessage?>(JsonSerializer.Deserialize<LongRangeAisBroadcastMessage>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "MultiSlotBinaryMessage":
                            multiSlotBinaryMessage = new Option<MultiSlotBinaryMessage?>(JsonSerializer.Deserialize<MultiSlotBinaryMessage>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "SafetyBroadcastMessage":
                            safetyBroadcastMessage = new Option<SafetyBroadcastMessage?>(JsonSerializer.Deserialize<SafetyBroadcastMessage>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "ShipStaticData":
                            shipStaticData = new Option<ShipStaticData?>(JsonSerializer.Deserialize<ShipStaticData>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "SingleSlotBinaryMessage":
                            singleSlotBinaryMessage = new Option<SingleSlotBinaryMessage?>(JsonSerializer.Deserialize<SingleSlotBinaryMessage>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "StandardClassBPositionReport":
                            standardClassBPositionReport = new Option<StandardClassBPositionReport?>(JsonSerializer.Deserialize<StandardClassBPositionReport>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "StandardSearchAndRescueAircraftReport":
                            standardSearchAndRescueAircraftReport = new Option<StandardSearchAndRescueAircraftReport?>(JsonSerializer.Deserialize<StandardSearchAndRescueAircraftReport>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "StaticDataReport":
                            staticDataReport = new Option<StaticDataReport?>(JsonSerializer.Deserialize<StaticDataReport>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (positionReport.IsSet && positionReport.Value == null)
                throw new ArgumentNullException(nameof(positionReport), "Property is not nullable for class AisStreamMessageMessage.");

            if (unknownMessage.IsSet && unknownMessage.Value == null)
                throw new ArgumentNullException(nameof(unknownMessage), "Property is not nullable for class AisStreamMessageMessage.");

            if (addressedSafetyMessage.IsSet && addressedSafetyMessage.Value == null)
                throw new ArgumentNullException(nameof(addressedSafetyMessage), "Property is not nullable for class AisStreamMessageMessage.");

            if (addressedBinaryMessage.IsSet && addressedBinaryMessage.Value == null)
                throw new ArgumentNullException(nameof(addressedBinaryMessage), "Property is not nullable for class AisStreamMessageMessage.");

            if (aidsToNavigationReport.IsSet && aidsToNavigationReport.Value == null)
                throw new ArgumentNullException(nameof(aidsToNavigationReport), "Property is not nullable for class AisStreamMessageMessage.");

            if (assignedModeCommand.IsSet && assignedModeCommand.Value == null)
                throw new ArgumentNullException(nameof(assignedModeCommand), "Property is not nullable for class AisStreamMessageMessage.");

            if (baseStationReport.IsSet && baseStationReport.Value == null)
                throw new ArgumentNullException(nameof(baseStationReport), "Property is not nullable for class AisStreamMessageMessage.");

            if (binaryAcknowledge.IsSet && binaryAcknowledge.Value == null)
                throw new ArgumentNullException(nameof(binaryAcknowledge), "Property is not nullable for class AisStreamMessageMessage.");

            if (binaryBroadcastMessage.IsSet && binaryBroadcastMessage.Value == null)
                throw new ArgumentNullException(nameof(binaryBroadcastMessage), "Property is not nullable for class AisStreamMessageMessage.");

            if (channelManagement.IsSet && channelManagement.Value == null)
                throw new ArgumentNullException(nameof(channelManagement), "Property is not nullable for class AisStreamMessageMessage.");

            if (coordinatedUTCInquiry.IsSet && coordinatedUTCInquiry.Value == null)
                throw new ArgumentNullException(nameof(coordinatedUTCInquiry), "Property is not nullable for class AisStreamMessageMessage.");

            if (dataLinkManagementMessage.IsSet && dataLinkManagementMessage.Value == null)
                throw new ArgumentNullException(nameof(dataLinkManagementMessage), "Property is not nullable for class AisStreamMessageMessage.");

            if (dataLinkManagementMessageData.IsSet && dataLinkManagementMessageData.Value == null)
                throw new ArgumentNullException(nameof(dataLinkManagementMessageData), "Property is not nullable for class AisStreamMessageMessage.");

            if (extendedClassBPositionReport.IsSet && extendedClassBPositionReport.Value == null)
                throw new ArgumentNullException(nameof(extendedClassBPositionReport), "Property is not nullable for class AisStreamMessageMessage.");

            if (gnssBroadcastBinaryMessage.IsSet && gnssBroadcastBinaryMessage.Value == null)
                throw new ArgumentNullException(nameof(gnssBroadcastBinaryMessage), "Property is not nullable for class AisStreamMessageMessage.");

            if (groupAssignmentCommand.IsSet && groupAssignmentCommand.Value == null)
                throw new ArgumentNullException(nameof(groupAssignmentCommand), "Property is not nullable for class AisStreamMessageMessage.");

            if (interrogation.IsSet && interrogation.Value == null)
                throw new ArgumentNullException(nameof(interrogation), "Property is not nullable for class AisStreamMessageMessage.");

            if (longRangeAisBroadcastMessage.IsSet && longRangeAisBroadcastMessage.Value == null)
                throw new ArgumentNullException(nameof(longRangeAisBroadcastMessage), "Property is not nullable for class AisStreamMessageMessage.");

            if (multiSlotBinaryMessage.IsSet && multiSlotBinaryMessage.Value == null)
                throw new ArgumentNullException(nameof(multiSlotBinaryMessage), "Property is not nullable for class AisStreamMessageMessage.");

            if (safetyBroadcastMessage.IsSet && safetyBroadcastMessage.Value == null)
                throw new ArgumentNullException(nameof(safetyBroadcastMessage), "Property is not nullable for class AisStreamMessageMessage.");

            if (shipStaticData.IsSet && shipStaticData.Value == null)
                throw new ArgumentNullException(nameof(shipStaticData), "Property is not nullable for class AisStreamMessageMessage.");

            if (singleSlotBinaryMessage.IsSet && singleSlotBinaryMessage.Value == null)
                throw new ArgumentNullException(nameof(singleSlotBinaryMessage), "Property is not nullable for class AisStreamMessageMessage.");

            if (standardClassBPositionReport.IsSet && standardClassBPositionReport.Value == null)
                throw new ArgumentNullException(nameof(standardClassBPositionReport), "Property is not nullable for class AisStreamMessageMessage.");

            if (standardSearchAndRescueAircraftReport.IsSet && standardSearchAndRescueAircraftReport.Value == null)
                throw new ArgumentNullException(nameof(standardSearchAndRescueAircraftReport), "Property is not nullable for class AisStreamMessageMessage.");

            if (staticDataReport.IsSet && staticDataReport.Value == null)
                throw new ArgumentNullException(nameof(staticDataReport), "Property is not nullable for class AisStreamMessageMessage.");

            return new AisStreamMessageMessage(positionReport, unknownMessage, addressedSafetyMessage, addressedBinaryMessage, aidsToNavigationReport, assignedModeCommand, baseStationReport, binaryAcknowledge, binaryBroadcastMessage, channelManagement, coordinatedUTCInquiry, dataLinkManagementMessage, dataLinkManagementMessageData, extendedClassBPositionReport, gnssBroadcastBinaryMessage, groupAssignmentCommand, interrogation, longRangeAisBroadcastMessage, multiSlotBinaryMessage, safetyBroadcastMessage, shipStaticData, singleSlotBinaryMessage, standardClassBPositionReport, standardSearchAndRescueAircraftReport, staticDataReport);
        }

        /// <summary>
        /// Serializes a <see cref="AisStreamMessageMessage" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="aisStreamMessageMessage"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AisStreamMessageMessage aisStreamMessageMessage, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, aisStreamMessageMessage, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AisStreamMessageMessage" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="aisStreamMessageMessage"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AisStreamMessageMessage aisStreamMessageMessage, JsonSerializerOptions jsonSerializerOptions)
        {
            if (aisStreamMessageMessage.PositionReportOption.IsSet && aisStreamMessageMessage.PositionReport == null)
                throw new ArgumentNullException(nameof(aisStreamMessageMessage.PositionReport), "Property is required for class AisStreamMessageMessage.");

            if (aisStreamMessageMessage.UnknownMessageOption.IsSet && aisStreamMessageMessage.UnknownMessage == null)
                throw new ArgumentNullException(nameof(aisStreamMessageMessage.UnknownMessage), "Property is required for class AisStreamMessageMessage.");

            if (aisStreamMessageMessage.AddressedSafetyMessageOption.IsSet && aisStreamMessageMessage.AddressedSafetyMessage == null)
                throw new ArgumentNullException(nameof(aisStreamMessageMessage.AddressedSafetyMessage), "Property is required for class AisStreamMessageMessage.");

            if (aisStreamMessageMessage.AddressedBinaryMessageOption.IsSet && aisStreamMessageMessage.AddressedBinaryMessage == null)
                throw new ArgumentNullException(nameof(aisStreamMessageMessage.AddressedBinaryMessage), "Property is required for class AisStreamMessageMessage.");

            if (aisStreamMessageMessage.AidsToNavigationReportOption.IsSet && aisStreamMessageMessage.AidsToNavigationReport == null)
                throw new ArgumentNullException(nameof(aisStreamMessageMessage.AidsToNavigationReport), "Property is required for class AisStreamMessageMessage.");

            if (aisStreamMessageMessage.AssignedModeCommandOption.IsSet && aisStreamMessageMessage.AssignedModeCommand == null)
                throw new ArgumentNullException(nameof(aisStreamMessageMessage.AssignedModeCommand), "Property is required for class AisStreamMessageMessage.");

            if (aisStreamMessageMessage.BaseStationReportOption.IsSet && aisStreamMessageMessage.BaseStationReport == null)
                throw new ArgumentNullException(nameof(aisStreamMessageMessage.BaseStationReport), "Property is required for class AisStreamMessageMessage.");

            if (aisStreamMessageMessage.BinaryAcknowledgeOption.IsSet && aisStreamMessageMessage.BinaryAcknowledge == null)
                throw new ArgumentNullException(nameof(aisStreamMessageMessage.BinaryAcknowledge), "Property is required for class AisStreamMessageMessage.");

            if (aisStreamMessageMessage.BinaryBroadcastMessageOption.IsSet && aisStreamMessageMessage.BinaryBroadcastMessage == null)
                throw new ArgumentNullException(nameof(aisStreamMessageMessage.BinaryBroadcastMessage), "Property is required for class AisStreamMessageMessage.");

            if (aisStreamMessageMessage.ChannelManagementOption.IsSet && aisStreamMessageMessage.ChannelManagement == null)
                throw new ArgumentNullException(nameof(aisStreamMessageMessage.ChannelManagement), "Property is required for class AisStreamMessageMessage.");

            if (aisStreamMessageMessage.CoordinatedUTCInquiryOption.IsSet && aisStreamMessageMessage.CoordinatedUTCInquiry == null)
                throw new ArgumentNullException(nameof(aisStreamMessageMessage.CoordinatedUTCInquiry), "Property is required for class AisStreamMessageMessage.");

            if (aisStreamMessageMessage.DataLinkManagementMessageOption.IsSet && aisStreamMessageMessage.DataLinkManagementMessage == null)
                throw new ArgumentNullException(nameof(aisStreamMessageMessage.DataLinkManagementMessage), "Property is required for class AisStreamMessageMessage.");

            if (aisStreamMessageMessage.DataLinkManagementMessageDataOption.IsSet && aisStreamMessageMessage.DataLinkManagementMessageData == null)
                throw new ArgumentNullException(nameof(aisStreamMessageMessage.DataLinkManagementMessageData), "Property is required for class AisStreamMessageMessage.");

            if (aisStreamMessageMessage.ExtendedClassBPositionReportOption.IsSet && aisStreamMessageMessage.ExtendedClassBPositionReport == null)
                throw new ArgumentNullException(nameof(aisStreamMessageMessage.ExtendedClassBPositionReport), "Property is required for class AisStreamMessageMessage.");

            if (aisStreamMessageMessage.GnssBroadcastBinaryMessageOption.IsSet && aisStreamMessageMessage.GnssBroadcastBinaryMessage == null)
                throw new ArgumentNullException(nameof(aisStreamMessageMessage.GnssBroadcastBinaryMessage), "Property is required for class AisStreamMessageMessage.");

            if (aisStreamMessageMessage.GroupAssignmentCommandOption.IsSet && aisStreamMessageMessage.GroupAssignmentCommand == null)
                throw new ArgumentNullException(nameof(aisStreamMessageMessage.GroupAssignmentCommand), "Property is required for class AisStreamMessageMessage.");

            if (aisStreamMessageMessage.InterrogationOption.IsSet && aisStreamMessageMessage.Interrogation == null)
                throw new ArgumentNullException(nameof(aisStreamMessageMessage.Interrogation), "Property is required for class AisStreamMessageMessage.");

            if (aisStreamMessageMessage.LongRangeAisBroadcastMessageOption.IsSet && aisStreamMessageMessage.LongRangeAisBroadcastMessage == null)
                throw new ArgumentNullException(nameof(aisStreamMessageMessage.LongRangeAisBroadcastMessage), "Property is required for class AisStreamMessageMessage.");

            if (aisStreamMessageMessage.MultiSlotBinaryMessageOption.IsSet && aisStreamMessageMessage.MultiSlotBinaryMessage == null)
                throw new ArgumentNullException(nameof(aisStreamMessageMessage.MultiSlotBinaryMessage), "Property is required for class AisStreamMessageMessage.");

            if (aisStreamMessageMessage.SafetyBroadcastMessageOption.IsSet && aisStreamMessageMessage.SafetyBroadcastMessage == null)
                throw new ArgumentNullException(nameof(aisStreamMessageMessage.SafetyBroadcastMessage), "Property is required for class AisStreamMessageMessage.");

            if (aisStreamMessageMessage.ShipStaticDataOption.IsSet && aisStreamMessageMessage.ShipStaticData == null)
                throw new ArgumentNullException(nameof(aisStreamMessageMessage.ShipStaticData), "Property is required for class AisStreamMessageMessage.");

            if (aisStreamMessageMessage.SingleSlotBinaryMessageOption.IsSet && aisStreamMessageMessage.SingleSlotBinaryMessage == null)
                throw new ArgumentNullException(nameof(aisStreamMessageMessage.SingleSlotBinaryMessage), "Property is required for class AisStreamMessageMessage.");

            if (aisStreamMessageMessage.StandardClassBPositionReportOption.IsSet && aisStreamMessageMessage.StandardClassBPositionReport == null)
                throw new ArgumentNullException(nameof(aisStreamMessageMessage.StandardClassBPositionReport), "Property is required for class AisStreamMessageMessage.");

            if (aisStreamMessageMessage.StandardSearchAndRescueAircraftReportOption.IsSet && aisStreamMessageMessage.StandardSearchAndRescueAircraftReport == null)
                throw new ArgumentNullException(nameof(aisStreamMessageMessage.StandardSearchAndRescueAircraftReport), "Property is required for class AisStreamMessageMessage.");

            if (aisStreamMessageMessage.StaticDataReportOption.IsSet && aisStreamMessageMessage.StaticDataReport == null)
                throw new ArgumentNullException(nameof(aisStreamMessageMessage.StaticDataReport), "Property is required for class AisStreamMessageMessage.");

            if (aisStreamMessageMessage.PositionReportOption.IsSet)
            {
                writer.WritePropertyName("PositionReport");
                JsonSerializer.Serialize(writer, aisStreamMessageMessage.PositionReport, jsonSerializerOptions);
            }
            if (aisStreamMessageMessage.UnknownMessageOption.IsSet)
            {
                writer.WritePropertyName("UnknownMessage");
                JsonSerializer.Serialize(writer, aisStreamMessageMessage.UnknownMessage, jsonSerializerOptions);
            }
            if (aisStreamMessageMessage.AddressedSafetyMessageOption.IsSet)
            {
                writer.WritePropertyName("AddressedSafetyMessage");
                JsonSerializer.Serialize(writer, aisStreamMessageMessage.AddressedSafetyMessage, jsonSerializerOptions);
            }
            if (aisStreamMessageMessage.AddressedBinaryMessageOption.IsSet)
            {
                writer.WritePropertyName("AddressedBinaryMessage");
                JsonSerializer.Serialize(writer, aisStreamMessageMessage.AddressedBinaryMessage, jsonSerializerOptions);
            }
            if (aisStreamMessageMessage.AidsToNavigationReportOption.IsSet)
            {
                writer.WritePropertyName("AidsToNavigationReport");
                JsonSerializer.Serialize(writer, aisStreamMessageMessage.AidsToNavigationReport, jsonSerializerOptions);
            }
            if (aisStreamMessageMessage.AssignedModeCommandOption.IsSet)
            {
                writer.WritePropertyName("AssignedModeCommand");
                JsonSerializer.Serialize(writer, aisStreamMessageMessage.AssignedModeCommand, jsonSerializerOptions);
            }
            if (aisStreamMessageMessage.BaseStationReportOption.IsSet)
            {
                writer.WritePropertyName("BaseStationReport");
                JsonSerializer.Serialize(writer, aisStreamMessageMessage.BaseStationReport, jsonSerializerOptions);
            }
            if (aisStreamMessageMessage.BinaryAcknowledgeOption.IsSet)
            {
                writer.WritePropertyName("BinaryAcknowledge");
                JsonSerializer.Serialize(writer, aisStreamMessageMessage.BinaryAcknowledge, jsonSerializerOptions);
            }
            if (aisStreamMessageMessage.BinaryBroadcastMessageOption.IsSet)
            {
                writer.WritePropertyName("BinaryBroadcastMessage");
                JsonSerializer.Serialize(writer, aisStreamMessageMessage.BinaryBroadcastMessage, jsonSerializerOptions);
            }
            if (aisStreamMessageMessage.ChannelManagementOption.IsSet)
            {
                writer.WritePropertyName("ChannelManagement");
                JsonSerializer.Serialize(writer, aisStreamMessageMessage.ChannelManagement, jsonSerializerOptions);
            }
            if (aisStreamMessageMessage.CoordinatedUTCInquiryOption.IsSet)
            {
                writer.WritePropertyName("CoordinatedUTCInquiry");
                JsonSerializer.Serialize(writer, aisStreamMessageMessage.CoordinatedUTCInquiry, jsonSerializerOptions);
            }
            if (aisStreamMessageMessage.DataLinkManagementMessageOption.IsSet)
            {
                writer.WritePropertyName("DataLinkManagementMessage");
                JsonSerializer.Serialize(writer, aisStreamMessageMessage.DataLinkManagementMessage, jsonSerializerOptions);
            }
            if (aisStreamMessageMessage.DataLinkManagementMessageDataOption.IsSet)
            {
                writer.WritePropertyName("DataLinkManagementMessageData");
                JsonSerializer.Serialize(writer, aisStreamMessageMessage.DataLinkManagementMessageData, jsonSerializerOptions);
            }
            if (aisStreamMessageMessage.ExtendedClassBPositionReportOption.IsSet)
            {
                writer.WritePropertyName("ExtendedClassBPositionReport");
                JsonSerializer.Serialize(writer, aisStreamMessageMessage.ExtendedClassBPositionReport, jsonSerializerOptions);
            }
            if (aisStreamMessageMessage.GnssBroadcastBinaryMessageOption.IsSet)
            {
                writer.WritePropertyName("GnssBroadcastBinaryMessage");
                JsonSerializer.Serialize(writer, aisStreamMessageMessage.GnssBroadcastBinaryMessage, jsonSerializerOptions);
            }
            if (aisStreamMessageMessage.GroupAssignmentCommandOption.IsSet)
            {
                writer.WritePropertyName("GroupAssignmentCommand");
                JsonSerializer.Serialize(writer, aisStreamMessageMessage.GroupAssignmentCommand, jsonSerializerOptions);
            }
            if (aisStreamMessageMessage.InterrogationOption.IsSet)
            {
                writer.WritePropertyName("Interrogation");
                JsonSerializer.Serialize(writer, aisStreamMessageMessage.Interrogation, jsonSerializerOptions);
            }
            if (aisStreamMessageMessage.LongRangeAisBroadcastMessageOption.IsSet)
            {
                writer.WritePropertyName("LongRangeAisBroadcastMessage");
                JsonSerializer.Serialize(writer, aisStreamMessageMessage.LongRangeAisBroadcastMessage, jsonSerializerOptions);
            }
            if (aisStreamMessageMessage.MultiSlotBinaryMessageOption.IsSet)
            {
                writer.WritePropertyName("MultiSlotBinaryMessage");
                JsonSerializer.Serialize(writer, aisStreamMessageMessage.MultiSlotBinaryMessage, jsonSerializerOptions);
            }
            if (aisStreamMessageMessage.SafetyBroadcastMessageOption.IsSet)
            {
                writer.WritePropertyName("SafetyBroadcastMessage");
                JsonSerializer.Serialize(writer, aisStreamMessageMessage.SafetyBroadcastMessage, jsonSerializerOptions);
            }
            if (aisStreamMessageMessage.ShipStaticDataOption.IsSet)
            {
                writer.WritePropertyName("ShipStaticData");
                JsonSerializer.Serialize(writer, aisStreamMessageMessage.ShipStaticData, jsonSerializerOptions);
            }
            if (aisStreamMessageMessage.SingleSlotBinaryMessageOption.IsSet)
            {
                writer.WritePropertyName("SingleSlotBinaryMessage");
                JsonSerializer.Serialize(writer, aisStreamMessageMessage.SingleSlotBinaryMessage, jsonSerializerOptions);
            }
            if (aisStreamMessageMessage.StandardClassBPositionReportOption.IsSet)
            {
                writer.WritePropertyName("StandardClassBPositionReport");
                JsonSerializer.Serialize(writer, aisStreamMessageMessage.StandardClassBPositionReport, jsonSerializerOptions);
            }
            if (aisStreamMessageMessage.StandardSearchAndRescueAircraftReportOption.IsSet)
            {
                writer.WritePropertyName("StandardSearchAndRescueAircraftReport");
                JsonSerializer.Serialize(writer, aisStreamMessageMessage.StandardSearchAndRescueAircraftReport, jsonSerializerOptions);
            }
            if (aisStreamMessageMessage.StaticDataReportOption.IsSet)
            {
                writer.WritePropertyName("StaticDataReport");
                JsonSerializer.Serialize(writer, aisStreamMessageMessage.StaticDataReport, jsonSerializerOptions);
            }
        }
    }
}
