// <auto-generated>
/*
 * Ais-Stream WebsocketObjects
 *
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// BinaryAcknowledgeDestinations0
    /// </summary>
    public partial class BinaryAcknowledgeDestinations0 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BinaryAcknowledgeDestinations0" /> class.
        /// </summary>
        /// <param name="valid">valid</param>
        /// <param name="destinationID">destinationID</param>
        /// <param name="sequenceinteger">sequenceinteger</param>
        [JsonConstructor]
        public BinaryAcknowledgeDestinations0(bool valid, int destinationID, int sequenceinteger)
        {
            Valid = valid;
            DestinationID = destinationID;
            Sequenceinteger = sequenceinteger;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Valid
        /// </summary>
        [JsonPropertyName("Valid")]
        public bool Valid { get; set; }

        /// <summary>
        /// Gets or Sets DestinationID
        /// </summary>
        [JsonPropertyName("DestinationID")]
        public int DestinationID { get; set; }

        /// <summary>
        /// Gets or Sets Sequenceinteger
        /// </summary>
        [JsonPropertyName("Sequenceinteger")]
        public int Sequenceinteger { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BinaryAcknowledgeDestinations0 {\n");
            sb.Append("  Valid: ").Append(Valid).Append("\n");
            sb.Append("  DestinationID: ").Append(DestinationID).Append("\n");
            sb.Append("  Sequenceinteger: ").Append(Sequenceinteger).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BinaryAcknowledgeDestinations0" />
    /// </summary>
    public class BinaryAcknowledgeDestinations0JsonConverter : JsonConverter<BinaryAcknowledgeDestinations0>
    {
        /// <summary>
        /// Deserializes json to <see cref="BinaryAcknowledgeDestinations0" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override BinaryAcknowledgeDestinations0 Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> valid = default;
            Option<int?> destinationID = default;
            Option<int?> sequenceinteger = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "Valid":
                            valid = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "DestinationID":
                            destinationID = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "Sequenceinteger":
                            sequenceinteger = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!valid.IsSet)
                throw new ArgumentException("Property is required for class BinaryAcknowledgeDestinations0.", nameof(valid));

            if (!destinationID.IsSet)
                throw new ArgumentException("Property is required for class BinaryAcknowledgeDestinations0.", nameof(destinationID));

            if (!sequenceinteger.IsSet)
                throw new ArgumentException("Property is required for class BinaryAcknowledgeDestinations0.", nameof(sequenceinteger));

            if (valid.IsSet && valid.Value == null)
                throw new ArgumentNullException(nameof(valid), "Property is not nullable for class BinaryAcknowledgeDestinations0.");

            if (destinationID.IsSet && destinationID.Value == null)
                throw new ArgumentNullException(nameof(destinationID), "Property is not nullable for class BinaryAcknowledgeDestinations0.");

            if (sequenceinteger.IsSet && sequenceinteger.Value == null)
                throw new ArgumentNullException(nameof(sequenceinteger), "Property is not nullable for class BinaryAcknowledgeDestinations0.");

            return new BinaryAcknowledgeDestinations0(valid.Value!.Value!, destinationID.Value!.Value!, sequenceinteger.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="BinaryAcknowledgeDestinations0" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="binaryAcknowledgeDestinations0"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, BinaryAcknowledgeDestinations0 binaryAcknowledgeDestinations0, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, binaryAcknowledgeDestinations0, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="BinaryAcknowledgeDestinations0" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="binaryAcknowledgeDestinations0"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, BinaryAcknowledgeDestinations0 binaryAcknowledgeDestinations0, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteBoolean("Valid", binaryAcknowledgeDestinations0.Valid);

            writer.WriteNumber("DestinationID", binaryAcknowledgeDestinations0.DestinationID);

            writer.WriteNumber("Sequenceinteger", binaryAcknowledgeDestinations0.Sequenceinteger);
        }
    }
}
