// <auto-generated>
/*
 * Ais-Stream WebsocketObjects
 *
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// BinaryBroadcastMessage
    /// </summary>
    public partial class BinaryBroadcastMessage : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BinaryBroadcastMessage" /> class.
        /// </summary>
        /// <param name="messageID">messageID</param>
        /// <param name="repeatIndicator">repeatIndicator</param>
        /// <param name="userID">userID</param>
        /// <param name="valid">valid</param>
        /// <param name="spare">spare</param>
        /// <param name="applicationID">applicationID</param>
        /// <param name="binaryData">binaryData</param>
        [JsonConstructor]
        public BinaryBroadcastMessage(int messageID, int repeatIndicator, int userID, bool valid, int spare, AddressedBinaryMessageApplicationID applicationID, string binaryData)
        {
            MessageID = messageID;
            RepeatIndicator = repeatIndicator;
            UserID = userID;
            Valid = valid;
            Spare = spare;
            ApplicationID = applicationID;
            BinaryData = binaryData;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets MessageID
        /// </summary>
        [JsonPropertyName("MessageID")]
        public int MessageID { get; set; }

        /// <summary>
        /// Gets or Sets RepeatIndicator
        /// </summary>
        [JsonPropertyName("RepeatIndicator")]
        public int RepeatIndicator { get; set; }

        /// <summary>
        /// Gets or Sets UserID
        /// </summary>
        [JsonPropertyName("UserID")]
        public int UserID { get; set; }

        /// <summary>
        /// Gets or Sets Valid
        /// </summary>
        [JsonPropertyName("Valid")]
        public bool Valid { get; set; }

        /// <summary>
        /// Gets or Sets Spare
        /// </summary>
        [JsonPropertyName("Spare")]
        public int Spare { get; set; }

        /// <summary>
        /// Gets or Sets ApplicationID
        /// </summary>
        [JsonPropertyName("ApplicationID")]
        public AddressedBinaryMessageApplicationID ApplicationID { get; set; }

        /// <summary>
        /// Gets or Sets BinaryData
        /// </summary>
        [JsonPropertyName("BinaryData")]
        public string BinaryData { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BinaryBroadcastMessage {\n");
            sb.Append("  MessageID: ").Append(MessageID).Append("\n");
            sb.Append("  RepeatIndicator: ").Append(RepeatIndicator).Append("\n");
            sb.Append("  UserID: ").Append(UserID).Append("\n");
            sb.Append("  Valid: ").Append(Valid).Append("\n");
            sb.Append("  Spare: ").Append(Spare).Append("\n");
            sb.Append("  ApplicationID: ").Append(ApplicationID).Append("\n");
            sb.Append("  BinaryData: ").Append(BinaryData).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BinaryBroadcastMessage" />
    /// </summary>
    public class BinaryBroadcastMessageJsonConverter : JsonConverter<BinaryBroadcastMessage>
    {
        /// <summary>
        /// Deserializes json to <see cref="BinaryBroadcastMessage" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override BinaryBroadcastMessage Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> messageID = default;
            Option<int?> repeatIndicator = default;
            Option<int?> userID = default;
            Option<bool?> valid = default;
            Option<int?> spare = default;
            Option<AddressedBinaryMessageApplicationID?> applicationID = default;
            Option<string?> binaryData = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "MessageID":
                            messageID = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "RepeatIndicator":
                            repeatIndicator = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "UserID":
                            userID = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "Valid":
                            valid = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "Spare":
                            spare = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "ApplicationID":
                            applicationID = new Option<AddressedBinaryMessageApplicationID?>(JsonSerializer.Deserialize<AddressedBinaryMessageApplicationID>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "BinaryData":
                            binaryData = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!messageID.IsSet)
                throw new ArgumentException("Property is required for class BinaryBroadcastMessage.", nameof(messageID));

            if (!repeatIndicator.IsSet)
                throw new ArgumentException("Property is required for class BinaryBroadcastMessage.", nameof(repeatIndicator));

            if (!userID.IsSet)
                throw new ArgumentException("Property is required for class BinaryBroadcastMessage.", nameof(userID));

            if (!valid.IsSet)
                throw new ArgumentException("Property is required for class BinaryBroadcastMessage.", nameof(valid));

            if (!spare.IsSet)
                throw new ArgumentException("Property is required for class BinaryBroadcastMessage.", nameof(spare));

            if (!applicationID.IsSet)
                throw new ArgumentException("Property is required for class BinaryBroadcastMessage.", nameof(applicationID));

            if (!binaryData.IsSet)
                throw new ArgumentException("Property is required for class BinaryBroadcastMessage.", nameof(binaryData));

            if (messageID.IsSet && messageID.Value == null)
                throw new ArgumentNullException(nameof(messageID), "Property is not nullable for class BinaryBroadcastMessage.");

            if (repeatIndicator.IsSet && repeatIndicator.Value == null)
                throw new ArgumentNullException(nameof(repeatIndicator), "Property is not nullable for class BinaryBroadcastMessage.");

            if (userID.IsSet && userID.Value == null)
                throw new ArgumentNullException(nameof(userID), "Property is not nullable for class BinaryBroadcastMessage.");

            if (valid.IsSet && valid.Value == null)
                throw new ArgumentNullException(nameof(valid), "Property is not nullable for class BinaryBroadcastMessage.");

            if (spare.IsSet && spare.Value == null)
                throw new ArgumentNullException(nameof(spare), "Property is not nullable for class BinaryBroadcastMessage.");

            if (applicationID.IsSet && applicationID.Value == null)
                throw new ArgumentNullException(nameof(applicationID), "Property is not nullable for class BinaryBroadcastMessage.");

            if (binaryData.IsSet && binaryData.Value == null)
                throw new ArgumentNullException(nameof(binaryData), "Property is not nullable for class BinaryBroadcastMessage.");

            return new BinaryBroadcastMessage(messageID.Value!.Value!, repeatIndicator.Value!.Value!, userID.Value!.Value!, valid.Value!.Value!, spare.Value!.Value!, applicationID.Value!, binaryData.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="BinaryBroadcastMessage" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="binaryBroadcastMessage"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, BinaryBroadcastMessage binaryBroadcastMessage, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, binaryBroadcastMessage, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="BinaryBroadcastMessage" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="binaryBroadcastMessage"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, BinaryBroadcastMessage binaryBroadcastMessage, JsonSerializerOptions jsonSerializerOptions)
        {
            if (binaryBroadcastMessage.ApplicationID == null)
                throw new ArgumentNullException(nameof(binaryBroadcastMessage.ApplicationID), "Property is required for class BinaryBroadcastMessage.");

            if (binaryBroadcastMessage.BinaryData == null)
                throw new ArgumentNullException(nameof(binaryBroadcastMessage.BinaryData), "Property is required for class BinaryBroadcastMessage.");

            writer.WriteNumber("MessageID", binaryBroadcastMessage.MessageID);

            writer.WriteNumber("RepeatIndicator", binaryBroadcastMessage.RepeatIndicator);

            writer.WriteNumber("UserID", binaryBroadcastMessage.UserID);

            writer.WriteBoolean("Valid", binaryBroadcastMessage.Valid);

            writer.WriteNumber("Spare", binaryBroadcastMessage.Spare);

            writer.WritePropertyName("ApplicationID");
            JsonSerializer.Serialize(writer, binaryBroadcastMessage.ApplicationID, jsonSerializerOptions);
            writer.WriteString("BinaryData", binaryBroadcastMessage.BinaryData);
        }
    }
}
