// <auto-generated>
/*
 * Ais-Stream WebsocketObjects
 *
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ChannelManagementUnicast
    /// </summary>
    public partial class ChannelManagementUnicast : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ChannelManagementUnicast" /> class.
        /// </summary>
        /// <param name="addressStation1">addressStation1</param>
        /// <param name="spare2">spare2</param>
        /// <param name="addressStation2">addressStation2</param>
        /// <param name="spare3">spare3</param>
        [JsonConstructor]
        public ChannelManagementUnicast(int addressStation1, int spare2, int addressStation2, int spare3)
        {
            AddressStation1 = addressStation1;
            Spare2 = spare2;
            AddressStation2 = addressStation2;
            Spare3 = spare3;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets AddressStation1
        /// </summary>
        [JsonPropertyName("AddressStation1")]
        public int AddressStation1 { get; set; }

        /// <summary>
        /// Gets or Sets Spare2
        /// </summary>
        [JsonPropertyName("Spare2")]
        public int Spare2 { get; set; }

        /// <summary>
        /// Gets or Sets AddressStation2
        /// </summary>
        [JsonPropertyName("AddressStation2")]
        public int AddressStation2 { get; set; }

        /// <summary>
        /// Gets or Sets Spare3
        /// </summary>
        [JsonPropertyName("Spare3")]
        public int Spare3 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ChannelManagementUnicast {\n");
            sb.Append("  AddressStation1: ").Append(AddressStation1).Append("\n");
            sb.Append("  Spare2: ").Append(Spare2).Append("\n");
            sb.Append("  AddressStation2: ").Append(AddressStation2).Append("\n");
            sb.Append("  Spare3: ").Append(Spare3).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ChannelManagementUnicast" />
    /// </summary>
    public class ChannelManagementUnicastJsonConverter : JsonConverter<ChannelManagementUnicast>
    {
        /// <summary>
        /// Deserializes json to <see cref="ChannelManagementUnicast" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ChannelManagementUnicast Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> addressStation1 = default;
            Option<int?> spare2 = default;
            Option<int?> addressStation2 = default;
            Option<int?> spare3 = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "AddressStation1":
                            addressStation1 = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "Spare2":
                            spare2 = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "AddressStation2":
                            addressStation2 = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "Spare3":
                            spare3 = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!addressStation1.IsSet)
                throw new ArgumentException("Property is required for class ChannelManagementUnicast.", nameof(addressStation1));

            if (!spare2.IsSet)
                throw new ArgumentException("Property is required for class ChannelManagementUnicast.", nameof(spare2));

            if (!addressStation2.IsSet)
                throw new ArgumentException("Property is required for class ChannelManagementUnicast.", nameof(addressStation2));

            if (!spare3.IsSet)
                throw new ArgumentException("Property is required for class ChannelManagementUnicast.", nameof(spare3));

            if (addressStation1.IsSet && addressStation1.Value == null)
                throw new ArgumentNullException(nameof(addressStation1), "Property is not nullable for class ChannelManagementUnicast.");

            if (spare2.IsSet && spare2.Value == null)
                throw new ArgumentNullException(nameof(spare2), "Property is not nullable for class ChannelManagementUnicast.");

            if (addressStation2.IsSet && addressStation2.Value == null)
                throw new ArgumentNullException(nameof(addressStation2), "Property is not nullable for class ChannelManagementUnicast.");

            if (spare3.IsSet && spare3.Value == null)
                throw new ArgumentNullException(nameof(spare3), "Property is not nullable for class ChannelManagementUnicast.");

            return new ChannelManagementUnicast(addressStation1.Value!.Value!, spare2.Value!.Value!, addressStation2.Value!.Value!, spare3.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="ChannelManagementUnicast" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="channelManagementUnicast"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ChannelManagementUnicast channelManagementUnicast, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, channelManagementUnicast, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ChannelManagementUnicast" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="channelManagementUnicast"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ChannelManagementUnicast channelManagementUnicast, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("AddressStation1", channelManagementUnicast.AddressStation1);

            writer.WriteNumber("Spare2", channelManagementUnicast.Spare2);

            writer.WriteNumber("AddressStation2", channelManagementUnicast.AddressStation2);

            writer.WriteNumber("Spare3", channelManagementUnicast.Spare3);
        }
    }
}
