// <auto-generated>
/*
 * Ais-Stream WebsocketObjects
 *
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ChannelManagementArea
    /// </summary>
    public partial class ChannelManagementArea : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ChannelManagementArea" /> class.
        /// </summary>
        /// <param name="longitude1">longitude1</param>
        /// <param name="latitude1">latitude1</param>
        /// <param name="longitude2">longitude2</param>
        /// <param name="latitude2">latitude2</param>
        [JsonConstructor]
        public ChannelManagementArea(double longitude1, double latitude1, double longitude2, double latitude2)
        {
            Longitude1 = longitude1;
            Latitude1 = latitude1;
            Longitude2 = longitude2;
            Latitude2 = latitude2;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Longitude1
        /// </summary>
        [JsonPropertyName("Longitude1")]
        public double Longitude1 { get; set; }

        /// <summary>
        /// Gets or Sets Latitude1
        /// </summary>
        [JsonPropertyName("Latitude1")]
        public double Latitude1 { get; set; }

        /// <summary>
        /// Gets or Sets Longitude2
        /// </summary>
        [JsonPropertyName("Longitude2")]
        public double Longitude2 { get; set; }

        /// <summary>
        /// Gets or Sets Latitude2
        /// </summary>
        [JsonPropertyName("Latitude2")]
        public double Latitude2 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ChannelManagementArea {\n");
            sb.Append("  Longitude1: ").Append(Longitude1).Append("\n");
            sb.Append("  Latitude1: ").Append(Latitude1).Append("\n");
            sb.Append("  Longitude2: ").Append(Longitude2).Append("\n");
            sb.Append("  Latitude2: ").Append(Latitude2).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ChannelManagementArea" />
    /// </summary>
    public class ChannelManagementAreaJsonConverter : JsonConverter<ChannelManagementArea>
    {
        /// <summary>
        /// Deserializes json to <see cref="ChannelManagementArea" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ChannelManagementArea Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<double?> longitude1 = default;
            Option<double?> latitude1 = default;
            Option<double?> longitude2 = default;
            Option<double?> latitude2 = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "Longitude1":
                            longitude1 = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "Latitude1":
                            latitude1 = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "Longitude2":
                            longitude2 = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "Latitude2":
                            latitude2 = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!longitude1.IsSet)
                throw new ArgumentException("Property is required for class ChannelManagementArea.", nameof(longitude1));

            if (!latitude1.IsSet)
                throw new ArgumentException("Property is required for class ChannelManagementArea.", nameof(latitude1));

            if (!longitude2.IsSet)
                throw new ArgumentException("Property is required for class ChannelManagementArea.", nameof(longitude2));

            if (!latitude2.IsSet)
                throw new ArgumentException("Property is required for class ChannelManagementArea.", nameof(latitude2));

            if (longitude1.IsSet && longitude1.Value == null)
                throw new ArgumentNullException(nameof(longitude1), "Property is not nullable for class ChannelManagementArea.");

            if (latitude1.IsSet && latitude1.Value == null)
                throw new ArgumentNullException(nameof(latitude1), "Property is not nullable for class ChannelManagementArea.");

            if (longitude2.IsSet && longitude2.Value == null)
                throw new ArgumentNullException(nameof(longitude2), "Property is not nullable for class ChannelManagementArea.");

            if (latitude2.IsSet && latitude2.Value == null)
                throw new ArgumentNullException(nameof(latitude2), "Property is not nullable for class ChannelManagementArea.");

            return new ChannelManagementArea(longitude1.Value!.Value!, latitude1.Value!.Value!, longitude2.Value!.Value!, latitude2.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="ChannelManagementArea" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="channelManagementArea"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ChannelManagementArea channelManagementArea, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, channelManagementArea, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ChannelManagementArea" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="channelManagementArea"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ChannelManagementArea channelManagementArea, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("Longitude1", channelManagementArea.Longitude1);

            writer.WriteNumber("Latitude1", channelManagementArea.Latitude1);

            writer.WriteNumber("Longitude2", channelManagementArea.Longitude2);

            writer.WriteNumber("Latitude2", channelManagementArea.Latitude2);
        }
    }
}
