// <auto-generated>
/*
 * Ais-Stream WebsocketObjects
 *
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// DataLinkManagementMessageData0
    /// </summary>
    public partial class DataLinkManagementMessageData0 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DataLinkManagementMessageData0" /> class.
        /// </summary>
        /// <param name="valid">valid</param>
        /// <param name="offset">offset</param>
        /// <param name="integerOfSlots">integerOfSlots</param>
        /// <param name="timeOut">timeOut</param>
        /// <param name="increment">increment</param>
        [JsonConstructor]
        public DataLinkManagementMessageData0(bool valid, int offset, int integerOfSlots, int timeOut, int increment)
        {
            Valid = valid;
            Offset = offset;
            IntegerOfSlots = integerOfSlots;
            TimeOut = timeOut;
            Increment = increment;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Valid
        /// </summary>
        [JsonPropertyName("Valid")]
        public bool Valid { get; set; }

        /// <summary>
        /// Gets or Sets Offset
        /// </summary>
        [JsonPropertyName("Offset")]
        public int Offset { get; set; }

        /// <summary>
        /// Gets or Sets IntegerOfSlots
        /// </summary>
        [JsonPropertyName("integerOfSlots")]
        public int IntegerOfSlots { get; set; }

        /// <summary>
        /// Gets or Sets TimeOut
        /// </summary>
        [JsonPropertyName("TimeOut")]
        public int TimeOut { get; set; }

        /// <summary>
        /// Gets or Sets Increment
        /// </summary>
        [JsonPropertyName("Increment")]
        public int Increment { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DataLinkManagementMessageData0 {\n");
            sb.Append("  Valid: ").Append(Valid).Append("\n");
            sb.Append("  Offset: ").Append(Offset).Append("\n");
            sb.Append("  IntegerOfSlots: ").Append(IntegerOfSlots).Append("\n");
            sb.Append("  TimeOut: ").Append(TimeOut).Append("\n");
            sb.Append("  Increment: ").Append(Increment).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DataLinkManagementMessageData0" />
    /// </summary>
    public class DataLinkManagementMessageData0JsonConverter : JsonConverter<DataLinkManagementMessageData0>
    {
        /// <summary>
        /// Deserializes json to <see cref="DataLinkManagementMessageData0" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DataLinkManagementMessageData0 Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> valid = default;
            Option<int?> offset = default;
            Option<int?> integerOfSlots = default;
            Option<int?> timeOut = default;
            Option<int?> increment = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "Valid":
                            valid = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "Offset":
                            offset = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "integerOfSlots":
                            integerOfSlots = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "TimeOut":
                            timeOut = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "Increment":
                            increment = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!valid.IsSet)
                throw new ArgumentException("Property is required for class DataLinkManagementMessageData0.", nameof(valid));

            if (!offset.IsSet)
                throw new ArgumentException("Property is required for class DataLinkManagementMessageData0.", nameof(offset));

            if (!integerOfSlots.IsSet)
                throw new ArgumentException("Property is required for class DataLinkManagementMessageData0.", nameof(integerOfSlots));

            if (!timeOut.IsSet)
                throw new ArgumentException("Property is required for class DataLinkManagementMessageData0.", nameof(timeOut));

            if (!increment.IsSet)
                throw new ArgumentException("Property is required for class DataLinkManagementMessageData0.", nameof(increment));

            if (valid.IsSet && valid.Value == null)
                throw new ArgumentNullException(nameof(valid), "Property is not nullable for class DataLinkManagementMessageData0.");

            if (offset.IsSet && offset.Value == null)
                throw new ArgumentNullException(nameof(offset), "Property is not nullable for class DataLinkManagementMessageData0.");

            if (integerOfSlots.IsSet && integerOfSlots.Value == null)
                throw new ArgumentNullException(nameof(integerOfSlots), "Property is not nullable for class DataLinkManagementMessageData0.");

            if (timeOut.IsSet && timeOut.Value == null)
                throw new ArgumentNullException(nameof(timeOut), "Property is not nullable for class DataLinkManagementMessageData0.");

            if (increment.IsSet && increment.Value == null)
                throw new ArgumentNullException(nameof(increment), "Property is not nullable for class DataLinkManagementMessageData0.");

            return new DataLinkManagementMessageData0(valid.Value!.Value!, offset.Value!.Value!, integerOfSlots.Value!.Value!, timeOut.Value!.Value!, increment.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="DataLinkManagementMessageData0" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dataLinkManagementMessageData0"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, DataLinkManagementMessageData0 dataLinkManagementMessageData0, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, dataLinkManagementMessageData0, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DataLinkManagementMessageData0" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dataLinkManagementMessageData0"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, DataLinkManagementMessageData0 dataLinkManagementMessageData0, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteBoolean("Valid", dataLinkManagementMessageData0.Valid);

            writer.WriteNumber("Offset", dataLinkManagementMessageData0.Offset);

            writer.WriteNumber("integerOfSlots", dataLinkManagementMessageData0.IntegerOfSlots);

            writer.WriteNumber("TimeOut", dataLinkManagementMessageData0.TimeOut);

            writer.WriteNumber("Increment", dataLinkManagementMessageData0.Increment);
        }
    }
}
