// <auto-generated>
/*
 * Ais-Stream WebsocketObjects
 *
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Interrogation
    /// </summary>
    public partial class Interrogation : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Interrogation" /> class.
        /// </summary>
        /// <param name="messageID">messageID</param>
        /// <param name="repeatIndicator">repeatIndicator</param>
        /// <param name="userID">userID</param>
        /// <param name="valid">valid</param>
        /// <param name="spare">spare</param>
        /// <param name="station1Msg1">station1Msg1</param>
        /// <param name="station1Msg2">station1Msg2</param>
        /// <param name="station2">station2</param>
        [JsonConstructor]
        public Interrogation(int messageID, int repeatIndicator, int userID, bool valid, int spare, InterrogationStation1Msg1 station1Msg1, InterrogationStation1Msg2 station1Msg2, InterrogationStation2 station2)
        {
            MessageID = messageID;
            RepeatIndicator = repeatIndicator;
            UserID = userID;
            Valid = valid;
            Spare = spare;
            Station1Msg1 = station1Msg1;
            Station1Msg2 = station1Msg2;
            Station2 = station2;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets MessageID
        /// </summary>
        [JsonPropertyName("MessageID")]
        public int MessageID { get; set; }

        /// <summary>
        /// Gets or Sets RepeatIndicator
        /// </summary>
        [JsonPropertyName("RepeatIndicator")]
        public int RepeatIndicator { get; set; }

        /// <summary>
        /// Gets or Sets UserID
        /// </summary>
        [JsonPropertyName("UserID")]
        public int UserID { get; set; }

        /// <summary>
        /// Gets or Sets Valid
        /// </summary>
        [JsonPropertyName("Valid")]
        public bool Valid { get; set; }

        /// <summary>
        /// Gets or Sets Spare
        /// </summary>
        [JsonPropertyName("Spare")]
        public int Spare { get; set; }

        /// <summary>
        /// Gets or Sets Station1Msg1
        /// </summary>
        [JsonPropertyName("Station1Msg1")]
        public InterrogationStation1Msg1 Station1Msg1 { get; set; }

        /// <summary>
        /// Gets or Sets Station1Msg2
        /// </summary>
        [JsonPropertyName("Station1Msg2")]
        public InterrogationStation1Msg2 Station1Msg2 { get; set; }

        /// <summary>
        /// Gets or Sets Station2
        /// </summary>
        [JsonPropertyName("Station2")]
        public InterrogationStation2 Station2 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Interrogation {\n");
            sb.Append("  MessageID: ").Append(MessageID).Append("\n");
            sb.Append("  RepeatIndicator: ").Append(RepeatIndicator).Append("\n");
            sb.Append("  UserID: ").Append(UserID).Append("\n");
            sb.Append("  Valid: ").Append(Valid).Append("\n");
            sb.Append("  Spare: ").Append(Spare).Append("\n");
            sb.Append("  Station1Msg1: ").Append(Station1Msg1).Append("\n");
            sb.Append("  Station1Msg2: ").Append(Station1Msg2).Append("\n");
            sb.Append("  Station2: ").Append(Station2).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Interrogation" />
    /// </summary>
    public class InterrogationJsonConverter : JsonConverter<Interrogation>
    {
        /// <summary>
        /// Deserializes json to <see cref="Interrogation" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Interrogation Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> messageID = default;
            Option<int?> repeatIndicator = default;
            Option<int?> userID = default;
            Option<bool?> valid = default;
            Option<int?> spare = default;
            Option<InterrogationStation1Msg1?> station1Msg1 = default;
            Option<InterrogationStation1Msg2?> station1Msg2 = default;
            Option<InterrogationStation2?> station2 = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "MessageID":
                            messageID = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "RepeatIndicator":
                            repeatIndicator = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "UserID":
                            userID = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "Valid":
                            valid = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "Spare":
                            spare = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "Station1Msg1":
                            station1Msg1 = new Option<InterrogationStation1Msg1?>(JsonSerializer.Deserialize<InterrogationStation1Msg1>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "Station1Msg2":
                            station1Msg2 = new Option<InterrogationStation1Msg2?>(JsonSerializer.Deserialize<InterrogationStation1Msg2>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "Station2":
                            station2 = new Option<InterrogationStation2?>(JsonSerializer.Deserialize<InterrogationStation2>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!messageID.IsSet)
                throw new ArgumentException("Property is required for class Interrogation.", nameof(messageID));

            if (!repeatIndicator.IsSet)
                throw new ArgumentException("Property is required for class Interrogation.", nameof(repeatIndicator));

            if (!userID.IsSet)
                throw new ArgumentException("Property is required for class Interrogation.", nameof(userID));

            if (!valid.IsSet)
                throw new ArgumentException("Property is required for class Interrogation.", nameof(valid));

            if (!spare.IsSet)
                throw new ArgumentException("Property is required for class Interrogation.", nameof(spare));

            if (!station1Msg1.IsSet)
                throw new ArgumentException("Property is required for class Interrogation.", nameof(station1Msg1));

            if (!station1Msg2.IsSet)
                throw new ArgumentException("Property is required for class Interrogation.", nameof(station1Msg2));

            if (!station2.IsSet)
                throw new ArgumentException("Property is required for class Interrogation.", nameof(station2));

            if (messageID.IsSet && messageID.Value == null)
                throw new ArgumentNullException(nameof(messageID), "Property is not nullable for class Interrogation.");

            if (repeatIndicator.IsSet && repeatIndicator.Value == null)
                throw new ArgumentNullException(nameof(repeatIndicator), "Property is not nullable for class Interrogation.");

            if (userID.IsSet && userID.Value == null)
                throw new ArgumentNullException(nameof(userID), "Property is not nullable for class Interrogation.");

            if (valid.IsSet && valid.Value == null)
                throw new ArgumentNullException(nameof(valid), "Property is not nullable for class Interrogation.");

            if (spare.IsSet && spare.Value == null)
                throw new ArgumentNullException(nameof(spare), "Property is not nullable for class Interrogation.");

            if (station1Msg1.IsSet && station1Msg1.Value == null)
                throw new ArgumentNullException(nameof(station1Msg1), "Property is not nullable for class Interrogation.");

            if (station1Msg2.IsSet && station1Msg2.Value == null)
                throw new ArgumentNullException(nameof(station1Msg2), "Property is not nullable for class Interrogation.");

            if (station2.IsSet && station2.Value == null)
                throw new ArgumentNullException(nameof(station2), "Property is not nullable for class Interrogation.");

            return new Interrogation(messageID.Value!.Value!, repeatIndicator.Value!.Value!, userID.Value!.Value!, valid.Value!.Value!, spare.Value!.Value!, station1Msg1.Value!, station1Msg2.Value!, station2.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="Interrogation" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="interrogation"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Interrogation interrogation, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, interrogation, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Interrogation" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="interrogation"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Interrogation interrogation, JsonSerializerOptions jsonSerializerOptions)
        {
            if (interrogation.Station1Msg1 == null)
                throw new ArgumentNullException(nameof(interrogation.Station1Msg1), "Property is required for class Interrogation.");

            if (interrogation.Station1Msg2 == null)
                throw new ArgumentNullException(nameof(interrogation.Station1Msg2), "Property is required for class Interrogation.");

            if (interrogation.Station2 == null)
                throw new ArgumentNullException(nameof(interrogation.Station2), "Property is required for class Interrogation.");

            writer.WriteNumber("MessageID", interrogation.MessageID);

            writer.WriteNumber("RepeatIndicator", interrogation.RepeatIndicator);

            writer.WriteNumber("UserID", interrogation.UserID);

            writer.WriteBoolean("Valid", interrogation.Valid);

            writer.WriteNumber("Spare", interrogation.Spare);

            writer.WritePropertyName("Station1Msg1");
            JsonSerializer.Serialize(writer, interrogation.Station1Msg1, jsonSerializerOptions);
            writer.WritePropertyName("Station1Msg2");
            JsonSerializer.Serialize(writer, interrogation.Station1Msg2, jsonSerializerOptions);
            writer.WritePropertyName("Station2");
            JsonSerializer.Serialize(writer, interrogation.Station2, jsonSerializerOptions);
        }
    }
}
