// <auto-generated>
/*
 * Ais-Stream WebsocketObjects
 *
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// LongRangeAisBroadcastMessage
    /// </summary>
    public partial class LongRangeAisBroadcastMessage : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LongRangeAisBroadcastMessage" /> class.
        /// </summary>
        /// <param name="messageID">messageID</param>
        /// <param name="repeatIndicator">repeatIndicator</param>
        /// <param name="userID">userID</param>
        /// <param name="valid">valid</param>
        /// <param name="positionAccuracy">positionAccuracy</param>
        /// <param name="raim">raim</param>
        /// <param name="navigationalStatus">navigationalStatus</param>
        /// <param name="longitude">longitude</param>
        /// <param name="latitude">latitude</param>
        /// <param name="sog">sog</param>
        /// <param name="cog">cog</param>
        /// <param name="positionLatency">positionLatency</param>
        /// <param name="spare">spare</param>
        [JsonConstructor]
        public LongRangeAisBroadcastMessage(int messageID, int repeatIndicator, int userID, bool valid, bool positionAccuracy, bool raim, int navigationalStatus, double longitude, double latitude, double sog, double cog, bool positionLatency, bool spare)
        {
            MessageID = messageID;
            RepeatIndicator = repeatIndicator;
            UserID = userID;
            Valid = valid;
            PositionAccuracy = positionAccuracy;
            Raim = raim;
            NavigationalStatus = navigationalStatus;
            Longitude = longitude;
            Latitude = latitude;
            Sog = sog;
            Cog = cog;
            PositionLatency = positionLatency;
            Spare = spare;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets MessageID
        /// </summary>
        [JsonPropertyName("MessageID")]
        public int MessageID { get; set; }

        /// <summary>
        /// Gets or Sets RepeatIndicator
        /// </summary>
        [JsonPropertyName("RepeatIndicator")]
        public int RepeatIndicator { get; set; }

        /// <summary>
        /// Gets or Sets UserID
        /// </summary>
        [JsonPropertyName("UserID")]
        public int UserID { get; set; }

        /// <summary>
        /// Gets or Sets Valid
        /// </summary>
        [JsonPropertyName("Valid")]
        public bool Valid { get; set; }

        /// <summary>
        /// Gets or Sets PositionAccuracy
        /// </summary>
        [JsonPropertyName("PositionAccuracy")]
        public bool PositionAccuracy { get; set; }

        /// <summary>
        /// Gets or Sets Raim
        /// </summary>
        [JsonPropertyName("Raim")]
        public bool Raim { get; set; }

        /// <summary>
        /// Gets or Sets NavigationalStatus
        /// </summary>
        [JsonPropertyName("NavigationalStatus")]
        public int NavigationalStatus { get; set; }

        /// <summary>
        /// Gets or Sets Longitude
        /// </summary>
        [JsonPropertyName("Longitude")]
        public double Longitude { get; set; }

        /// <summary>
        /// Gets or Sets Latitude
        /// </summary>
        [JsonPropertyName("Latitude")]
        public double Latitude { get; set; }

        /// <summary>
        /// Gets or Sets Sog
        /// </summary>
        [JsonPropertyName("Sog")]
        public double Sog { get; set; }

        /// <summary>
        /// Gets or Sets Cog
        /// </summary>
        [JsonPropertyName("Cog")]
        public double Cog { get; set; }

        /// <summary>
        /// Gets or Sets PositionLatency
        /// </summary>
        [JsonPropertyName("PositionLatency")]
        public bool PositionLatency { get; set; }

        /// <summary>
        /// Gets or Sets Spare
        /// </summary>
        [JsonPropertyName("Spare")]
        public bool Spare { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LongRangeAisBroadcastMessage {\n");
            sb.Append("  MessageID: ").Append(MessageID).Append("\n");
            sb.Append("  RepeatIndicator: ").Append(RepeatIndicator).Append("\n");
            sb.Append("  UserID: ").Append(UserID).Append("\n");
            sb.Append("  Valid: ").Append(Valid).Append("\n");
            sb.Append("  PositionAccuracy: ").Append(PositionAccuracy).Append("\n");
            sb.Append("  Raim: ").Append(Raim).Append("\n");
            sb.Append("  NavigationalStatus: ").Append(NavigationalStatus).Append("\n");
            sb.Append("  Longitude: ").Append(Longitude).Append("\n");
            sb.Append("  Latitude: ").Append(Latitude).Append("\n");
            sb.Append("  Sog: ").Append(Sog).Append("\n");
            sb.Append("  Cog: ").Append(Cog).Append("\n");
            sb.Append("  PositionLatency: ").Append(PositionLatency).Append("\n");
            sb.Append("  Spare: ").Append(Spare).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="LongRangeAisBroadcastMessage" />
    /// </summary>
    public class LongRangeAisBroadcastMessageJsonConverter : JsonConverter<LongRangeAisBroadcastMessage>
    {
        /// <summary>
        /// Deserializes json to <see cref="LongRangeAisBroadcastMessage" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override LongRangeAisBroadcastMessage Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> messageID = default;
            Option<int?> repeatIndicator = default;
            Option<int?> userID = default;
            Option<bool?> valid = default;
            Option<bool?> positionAccuracy = default;
            Option<bool?> raim = default;
            Option<int?> navigationalStatus = default;
            Option<double?> longitude = default;
            Option<double?> latitude = default;
            Option<double?> sog = default;
            Option<double?> cog = default;
            Option<bool?> positionLatency = default;
            Option<bool?> spare = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "MessageID":
                            messageID = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "RepeatIndicator":
                            repeatIndicator = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "UserID":
                            userID = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "Valid":
                            valid = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "PositionAccuracy":
                            positionAccuracy = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "Raim":
                            raim = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "NavigationalStatus":
                            navigationalStatus = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "Longitude":
                            longitude = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "Latitude":
                            latitude = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "Sog":
                            sog = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "Cog":
                            cog = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "PositionLatency":
                            positionLatency = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "Spare":
                            spare = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!messageID.IsSet)
                throw new ArgumentException("Property is required for class LongRangeAisBroadcastMessage.", nameof(messageID));

            if (!repeatIndicator.IsSet)
                throw new ArgumentException("Property is required for class LongRangeAisBroadcastMessage.", nameof(repeatIndicator));

            if (!userID.IsSet)
                throw new ArgumentException("Property is required for class LongRangeAisBroadcastMessage.", nameof(userID));

            if (!valid.IsSet)
                throw new ArgumentException("Property is required for class LongRangeAisBroadcastMessage.", nameof(valid));

            if (!positionAccuracy.IsSet)
                throw new ArgumentException("Property is required for class LongRangeAisBroadcastMessage.", nameof(positionAccuracy));

            if (!raim.IsSet)
                throw new ArgumentException("Property is required for class LongRangeAisBroadcastMessage.", nameof(raim));

            if (!navigationalStatus.IsSet)
                throw new ArgumentException("Property is required for class LongRangeAisBroadcastMessage.", nameof(navigationalStatus));

            if (!longitude.IsSet)
                throw new ArgumentException("Property is required for class LongRangeAisBroadcastMessage.", nameof(longitude));

            if (!latitude.IsSet)
                throw new ArgumentException("Property is required for class LongRangeAisBroadcastMessage.", nameof(latitude));

            if (!sog.IsSet)
                throw new ArgumentException("Property is required for class LongRangeAisBroadcastMessage.", nameof(sog));

            if (!cog.IsSet)
                throw new ArgumentException("Property is required for class LongRangeAisBroadcastMessage.", nameof(cog));

            if (!positionLatency.IsSet)
                throw new ArgumentException("Property is required for class LongRangeAisBroadcastMessage.", nameof(positionLatency));

            if (!spare.IsSet)
                throw new ArgumentException("Property is required for class LongRangeAisBroadcastMessage.", nameof(spare));

            if (messageID.IsSet && messageID.Value == null)
                throw new ArgumentNullException(nameof(messageID), "Property is not nullable for class LongRangeAisBroadcastMessage.");

            if (repeatIndicator.IsSet && repeatIndicator.Value == null)
                throw new ArgumentNullException(nameof(repeatIndicator), "Property is not nullable for class LongRangeAisBroadcastMessage.");

            if (userID.IsSet && userID.Value == null)
                throw new ArgumentNullException(nameof(userID), "Property is not nullable for class LongRangeAisBroadcastMessage.");

            if (valid.IsSet && valid.Value == null)
                throw new ArgumentNullException(nameof(valid), "Property is not nullable for class LongRangeAisBroadcastMessage.");

            if (positionAccuracy.IsSet && positionAccuracy.Value == null)
                throw new ArgumentNullException(nameof(positionAccuracy), "Property is not nullable for class LongRangeAisBroadcastMessage.");

            if (raim.IsSet && raim.Value == null)
                throw new ArgumentNullException(nameof(raim), "Property is not nullable for class LongRangeAisBroadcastMessage.");

            if (navigationalStatus.IsSet && navigationalStatus.Value == null)
                throw new ArgumentNullException(nameof(navigationalStatus), "Property is not nullable for class LongRangeAisBroadcastMessage.");

            if (longitude.IsSet && longitude.Value == null)
                throw new ArgumentNullException(nameof(longitude), "Property is not nullable for class LongRangeAisBroadcastMessage.");

            if (latitude.IsSet && latitude.Value == null)
                throw new ArgumentNullException(nameof(latitude), "Property is not nullable for class LongRangeAisBroadcastMessage.");

            if (sog.IsSet && sog.Value == null)
                throw new ArgumentNullException(nameof(sog), "Property is not nullable for class LongRangeAisBroadcastMessage.");

            if (cog.IsSet && cog.Value == null)
                throw new ArgumentNullException(nameof(cog), "Property is not nullable for class LongRangeAisBroadcastMessage.");

            if (positionLatency.IsSet && positionLatency.Value == null)
                throw new ArgumentNullException(nameof(positionLatency), "Property is not nullable for class LongRangeAisBroadcastMessage.");

            if (spare.IsSet && spare.Value == null)
                throw new ArgumentNullException(nameof(spare), "Property is not nullable for class LongRangeAisBroadcastMessage.");

            return new LongRangeAisBroadcastMessage(messageID.Value!.Value!, repeatIndicator.Value!.Value!, userID.Value!.Value!, valid.Value!.Value!, positionAccuracy.Value!.Value!, raim.Value!.Value!, navigationalStatus.Value!.Value!, longitude.Value!.Value!, latitude.Value!.Value!, sog.Value!.Value!, cog.Value!.Value!, positionLatency.Value!.Value!, spare.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="LongRangeAisBroadcastMessage" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="longRangeAisBroadcastMessage"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, LongRangeAisBroadcastMessage longRangeAisBroadcastMessage, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, longRangeAisBroadcastMessage, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="LongRangeAisBroadcastMessage" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="longRangeAisBroadcastMessage"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, LongRangeAisBroadcastMessage longRangeAisBroadcastMessage, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("MessageID", longRangeAisBroadcastMessage.MessageID);

            writer.WriteNumber("RepeatIndicator", longRangeAisBroadcastMessage.RepeatIndicator);

            writer.WriteNumber("UserID", longRangeAisBroadcastMessage.UserID);

            writer.WriteBoolean("Valid", longRangeAisBroadcastMessage.Valid);

            writer.WriteBoolean("PositionAccuracy", longRangeAisBroadcastMessage.PositionAccuracy);

            writer.WriteBoolean("Raim", longRangeAisBroadcastMessage.Raim);

            writer.WriteNumber("NavigationalStatus", longRangeAisBroadcastMessage.NavigationalStatus);

            writer.WriteNumber("Longitude", longRangeAisBroadcastMessage.Longitude);

            writer.WriteNumber("Latitude", longRangeAisBroadcastMessage.Latitude);

            writer.WriteNumber("Sog", longRangeAisBroadcastMessage.Sog);

            writer.WriteNumber("Cog", longRangeAisBroadcastMessage.Cog);

            writer.WriteBoolean("PositionLatency", longRangeAisBroadcastMessage.PositionLatency);

            writer.WriteBoolean("Spare", longRangeAisBroadcastMessage.Spare);
        }
    }
}
