// <auto-generated>
/*
 * Ais-Stream WebsocketObjects
 *
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// StandardSearchAndRescueAircraftReport
    /// </summary>
    public partial class StandardSearchAndRescueAircraftReport : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StandardSearchAndRescueAircraftReport" /> class.
        /// </summary>
        /// <param name="messageID">messageID</param>
        /// <param name="repeatIndicator">repeatIndicator</param>
        /// <param name="userID">userID</param>
        /// <param name="valid">valid</param>
        /// <param name="altitude">altitude</param>
        /// <param name="sog">sog</param>
        /// <param name="positionAccuracy">positionAccuracy</param>
        /// <param name="longitude">longitude</param>
        /// <param name="latitude">latitude</param>
        /// <param name="cog">cog</param>
        /// <param name="timestamp">timestamp</param>
        /// <param name="altFromBaro">altFromBaro</param>
        /// <param name="spare1">spare1</param>
        /// <param name="dte">dte</param>
        /// <param name="spare2">spare2</param>
        /// <param name="assignedMode">assignedMode</param>
        /// <param name="raim">raim</param>
        /// <param name="communicationStateIsItdma">communicationStateIsItdma</param>
        /// <param name="communicationState">communicationState</param>
        [JsonConstructor]
        public StandardSearchAndRescueAircraftReport(int messageID, int repeatIndicator, int userID, bool valid, int altitude, double sog, bool positionAccuracy, double longitude, double latitude, double cog, int timestamp, bool altFromBaro, int spare1, bool dte, int spare2, bool assignedMode, bool raim, bool communicationStateIsItdma, int communicationState)
        {
            MessageID = messageID;
            RepeatIndicator = repeatIndicator;
            UserID = userID;
            Valid = valid;
            Altitude = altitude;
            Sog = sog;
            PositionAccuracy = positionAccuracy;
            Longitude = longitude;
            Latitude = latitude;
            Cog = cog;
            Timestamp = timestamp;
            AltFromBaro = altFromBaro;
            Spare1 = spare1;
            Dte = dte;
            Spare2 = spare2;
            AssignedMode = assignedMode;
            Raim = raim;
            CommunicationStateIsItdma = communicationStateIsItdma;
            CommunicationState = communicationState;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets MessageID
        /// </summary>
        [JsonPropertyName("MessageID")]
        public int MessageID { get; set; }

        /// <summary>
        /// Gets or Sets RepeatIndicator
        /// </summary>
        [JsonPropertyName("RepeatIndicator")]
        public int RepeatIndicator { get; set; }

        /// <summary>
        /// Gets or Sets UserID
        /// </summary>
        [JsonPropertyName("UserID")]
        public int UserID { get; set; }

        /// <summary>
        /// Gets or Sets Valid
        /// </summary>
        [JsonPropertyName("Valid")]
        public bool Valid { get; set; }

        /// <summary>
        /// Gets or Sets Altitude
        /// </summary>
        [JsonPropertyName("Altitude")]
        public int Altitude { get; set; }

        /// <summary>
        /// Gets or Sets Sog
        /// </summary>
        [JsonPropertyName("Sog")]
        public double Sog { get; set; }

        /// <summary>
        /// Gets or Sets PositionAccuracy
        /// </summary>
        [JsonPropertyName("PositionAccuracy")]
        public bool PositionAccuracy { get; set; }

        /// <summary>
        /// Gets or Sets Longitude
        /// </summary>
        [JsonPropertyName("Longitude")]
        public double Longitude { get; set; }

        /// <summary>
        /// Gets or Sets Latitude
        /// </summary>
        [JsonPropertyName("Latitude")]
        public double Latitude { get; set; }

        /// <summary>
        /// Gets or Sets Cog
        /// </summary>
        [JsonPropertyName("Cog")]
        public double Cog { get; set; }

        /// <summary>
        /// Gets or Sets Timestamp
        /// </summary>
        [JsonPropertyName("Timestamp")]
        public int Timestamp { get; set; }

        /// <summary>
        /// Gets or Sets AltFromBaro
        /// </summary>
        [JsonPropertyName("AltFromBaro")]
        public bool AltFromBaro { get; set; }

        /// <summary>
        /// Gets or Sets Spare1
        /// </summary>
        [JsonPropertyName("Spare1")]
        public int Spare1 { get; set; }

        /// <summary>
        /// Gets or Sets Dte
        /// </summary>
        [JsonPropertyName("Dte")]
        public bool Dte { get; set; }

        /// <summary>
        /// Gets or Sets Spare2
        /// </summary>
        [JsonPropertyName("Spare2")]
        public int Spare2 { get; set; }

        /// <summary>
        /// Gets or Sets AssignedMode
        /// </summary>
        [JsonPropertyName("AssignedMode")]
        public bool AssignedMode { get; set; }

        /// <summary>
        /// Gets or Sets Raim
        /// </summary>
        [JsonPropertyName("Raim")]
        public bool Raim { get; set; }

        /// <summary>
        /// Gets or Sets CommunicationStateIsItdma
        /// </summary>
        [JsonPropertyName("CommunicationStateIsItdma")]
        public bool CommunicationStateIsItdma { get; set; }

        /// <summary>
        /// Gets or Sets CommunicationState
        /// </summary>
        [JsonPropertyName("CommunicationState")]
        public int CommunicationState { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StandardSearchAndRescueAircraftReport {\n");
            sb.Append("  MessageID: ").Append(MessageID).Append("\n");
            sb.Append("  RepeatIndicator: ").Append(RepeatIndicator).Append("\n");
            sb.Append("  UserID: ").Append(UserID).Append("\n");
            sb.Append("  Valid: ").Append(Valid).Append("\n");
            sb.Append("  Altitude: ").Append(Altitude).Append("\n");
            sb.Append("  Sog: ").Append(Sog).Append("\n");
            sb.Append("  PositionAccuracy: ").Append(PositionAccuracy).Append("\n");
            sb.Append("  Longitude: ").Append(Longitude).Append("\n");
            sb.Append("  Latitude: ").Append(Latitude).Append("\n");
            sb.Append("  Cog: ").Append(Cog).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  AltFromBaro: ").Append(AltFromBaro).Append("\n");
            sb.Append("  Spare1: ").Append(Spare1).Append("\n");
            sb.Append("  Dte: ").Append(Dte).Append("\n");
            sb.Append("  Spare2: ").Append(Spare2).Append("\n");
            sb.Append("  AssignedMode: ").Append(AssignedMode).Append("\n");
            sb.Append("  Raim: ").Append(Raim).Append("\n");
            sb.Append("  CommunicationStateIsItdma: ").Append(CommunicationStateIsItdma).Append("\n");
            sb.Append("  CommunicationState: ").Append(CommunicationState).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="StandardSearchAndRescueAircraftReport" />
    /// </summary>
    public class StandardSearchAndRescueAircraftReportJsonConverter : JsonConverter<StandardSearchAndRescueAircraftReport>
    {
        /// <summary>
        /// Deserializes json to <see cref="StandardSearchAndRescueAircraftReport" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override StandardSearchAndRescueAircraftReport Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> messageID = default;
            Option<int?> repeatIndicator = default;
            Option<int?> userID = default;
            Option<bool?> valid = default;
            Option<int?> altitude = default;
            Option<double?> sog = default;
            Option<bool?> positionAccuracy = default;
            Option<double?> longitude = default;
            Option<double?> latitude = default;
            Option<double?> cog = default;
            Option<int?> timestamp = default;
            Option<bool?> altFromBaro = default;
            Option<int?> spare1 = default;
            Option<bool?> dte = default;
            Option<int?> spare2 = default;
            Option<bool?> assignedMode = default;
            Option<bool?> raim = default;
            Option<bool?> communicationStateIsItdma = default;
            Option<int?> communicationState = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "MessageID":
                            messageID = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "RepeatIndicator":
                            repeatIndicator = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "UserID":
                            userID = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "Valid":
                            valid = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "Altitude":
                            altitude = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "Sog":
                            sog = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "PositionAccuracy":
                            positionAccuracy = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "Longitude":
                            longitude = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "Latitude":
                            latitude = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "Cog":
                            cog = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "Timestamp":
                            timestamp = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "AltFromBaro":
                            altFromBaro = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "Spare1":
                            spare1 = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "Dte":
                            dte = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "Spare2":
                            spare2 = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "AssignedMode":
                            assignedMode = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "Raim":
                            raim = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "CommunicationStateIsItdma":
                            communicationStateIsItdma = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "CommunicationState":
                            communicationState = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!messageID.IsSet)
                throw new ArgumentException("Property is required for class StandardSearchAndRescueAircraftReport.", nameof(messageID));

            if (!repeatIndicator.IsSet)
                throw new ArgumentException("Property is required for class StandardSearchAndRescueAircraftReport.", nameof(repeatIndicator));

            if (!userID.IsSet)
                throw new ArgumentException("Property is required for class StandardSearchAndRescueAircraftReport.", nameof(userID));

            if (!valid.IsSet)
                throw new ArgumentException("Property is required for class StandardSearchAndRescueAircraftReport.", nameof(valid));

            if (!altitude.IsSet)
                throw new ArgumentException("Property is required for class StandardSearchAndRescueAircraftReport.", nameof(altitude));

            if (!sog.IsSet)
                throw new ArgumentException("Property is required for class StandardSearchAndRescueAircraftReport.", nameof(sog));

            if (!positionAccuracy.IsSet)
                throw new ArgumentException("Property is required for class StandardSearchAndRescueAircraftReport.", nameof(positionAccuracy));

            if (!longitude.IsSet)
                throw new ArgumentException("Property is required for class StandardSearchAndRescueAircraftReport.", nameof(longitude));

            if (!latitude.IsSet)
                throw new ArgumentException("Property is required for class StandardSearchAndRescueAircraftReport.", nameof(latitude));

            if (!cog.IsSet)
                throw new ArgumentException("Property is required for class StandardSearchAndRescueAircraftReport.", nameof(cog));

            if (!timestamp.IsSet)
                throw new ArgumentException("Property is required for class StandardSearchAndRescueAircraftReport.", nameof(timestamp));

            if (!altFromBaro.IsSet)
                throw new ArgumentException("Property is required for class StandardSearchAndRescueAircraftReport.", nameof(altFromBaro));

            if (!spare1.IsSet)
                throw new ArgumentException("Property is required for class StandardSearchAndRescueAircraftReport.", nameof(spare1));

            if (!dte.IsSet)
                throw new ArgumentException("Property is required for class StandardSearchAndRescueAircraftReport.", nameof(dte));

            if (!spare2.IsSet)
                throw new ArgumentException("Property is required for class StandardSearchAndRescueAircraftReport.", nameof(spare2));

            if (!assignedMode.IsSet)
                throw new ArgumentException("Property is required for class StandardSearchAndRescueAircraftReport.", nameof(assignedMode));

            if (!raim.IsSet)
                throw new ArgumentException("Property is required for class StandardSearchAndRescueAircraftReport.", nameof(raim));

            if (!communicationStateIsItdma.IsSet)
                throw new ArgumentException("Property is required for class StandardSearchAndRescueAircraftReport.", nameof(communicationStateIsItdma));

            if (!communicationState.IsSet)
                throw new ArgumentException("Property is required for class StandardSearchAndRescueAircraftReport.", nameof(communicationState));

            if (messageID.IsSet && messageID.Value == null)
                throw new ArgumentNullException(nameof(messageID), "Property is not nullable for class StandardSearchAndRescueAircraftReport.");

            if (repeatIndicator.IsSet && repeatIndicator.Value == null)
                throw new ArgumentNullException(nameof(repeatIndicator), "Property is not nullable for class StandardSearchAndRescueAircraftReport.");

            if (userID.IsSet && userID.Value == null)
                throw new ArgumentNullException(nameof(userID), "Property is not nullable for class StandardSearchAndRescueAircraftReport.");

            if (valid.IsSet && valid.Value == null)
                throw new ArgumentNullException(nameof(valid), "Property is not nullable for class StandardSearchAndRescueAircraftReport.");

            if (altitude.IsSet && altitude.Value == null)
                throw new ArgumentNullException(nameof(altitude), "Property is not nullable for class StandardSearchAndRescueAircraftReport.");

            if (sog.IsSet && sog.Value == null)
                throw new ArgumentNullException(nameof(sog), "Property is not nullable for class StandardSearchAndRescueAircraftReport.");

            if (positionAccuracy.IsSet && positionAccuracy.Value == null)
                throw new ArgumentNullException(nameof(positionAccuracy), "Property is not nullable for class StandardSearchAndRescueAircraftReport.");

            if (longitude.IsSet && longitude.Value == null)
                throw new ArgumentNullException(nameof(longitude), "Property is not nullable for class StandardSearchAndRescueAircraftReport.");

            if (latitude.IsSet && latitude.Value == null)
                throw new ArgumentNullException(nameof(latitude), "Property is not nullable for class StandardSearchAndRescueAircraftReport.");

            if (cog.IsSet && cog.Value == null)
                throw new ArgumentNullException(nameof(cog), "Property is not nullable for class StandardSearchAndRescueAircraftReport.");

            if (timestamp.IsSet && timestamp.Value == null)
                throw new ArgumentNullException(nameof(timestamp), "Property is not nullable for class StandardSearchAndRescueAircraftReport.");

            if (altFromBaro.IsSet && altFromBaro.Value == null)
                throw new ArgumentNullException(nameof(altFromBaro), "Property is not nullable for class StandardSearchAndRescueAircraftReport.");

            if (spare1.IsSet && spare1.Value == null)
                throw new ArgumentNullException(nameof(spare1), "Property is not nullable for class StandardSearchAndRescueAircraftReport.");

            if (dte.IsSet && dte.Value == null)
                throw new ArgumentNullException(nameof(dte), "Property is not nullable for class StandardSearchAndRescueAircraftReport.");

            if (spare2.IsSet && spare2.Value == null)
                throw new ArgumentNullException(nameof(spare2), "Property is not nullable for class StandardSearchAndRescueAircraftReport.");

            if (assignedMode.IsSet && assignedMode.Value == null)
                throw new ArgumentNullException(nameof(assignedMode), "Property is not nullable for class StandardSearchAndRescueAircraftReport.");

            if (raim.IsSet && raim.Value == null)
                throw new ArgumentNullException(nameof(raim), "Property is not nullable for class StandardSearchAndRescueAircraftReport.");

            if (communicationStateIsItdma.IsSet && communicationStateIsItdma.Value == null)
                throw new ArgumentNullException(nameof(communicationStateIsItdma), "Property is not nullable for class StandardSearchAndRescueAircraftReport.");

            if (communicationState.IsSet && communicationState.Value == null)
                throw new ArgumentNullException(nameof(communicationState), "Property is not nullable for class StandardSearchAndRescueAircraftReport.");

            return new StandardSearchAndRescueAircraftReport(messageID.Value!.Value!, repeatIndicator.Value!.Value!, userID.Value!.Value!, valid.Value!.Value!, altitude.Value!.Value!, sog.Value!.Value!, positionAccuracy.Value!.Value!, longitude.Value!.Value!, latitude.Value!.Value!, cog.Value!.Value!, timestamp.Value!.Value!, altFromBaro.Value!.Value!, spare1.Value!.Value!, dte.Value!.Value!, spare2.Value!.Value!, assignedMode.Value!.Value!, raim.Value!.Value!, communicationStateIsItdma.Value!.Value!, communicationState.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="StandardSearchAndRescueAircraftReport" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="standardSearchAndRescueAircraftReport"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, StandardSearchAndRescueAircraftReport standardSearchAndRescueAircraftReport, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, standardSearchAndRescueAircraftReport, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="StandardSearchAndRescueAircraftReport" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="standardSearchAndRescueAircraftReport"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, StandardSearchAndRescueAircraftReport standardSearchAndRescueAircraftReport, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("MessageID", standardSearchAndRescueAircraftReport.MessageID);

            writer.WriteNumber("RepeatIndicator", standardSearchAndRescueAircraftReport.RepeatIndicator);

            writer.WriteNumber("UserID", standardSearchAndRescueAircraftReport.UserID);

            writer.WriteBoolean("Valid", standardSearchAndRescueAircraftReport.Valid);

            writer.WriteNumber("Altitude", standardSearchAndRescueAircraftReport.Altitude);

            writer.WriteNumber("Sog", standardSearchAndRescueAircraftReport.Sog);

            writer.WriteBoolean("PositionAccuracy", standardSearchAndRescueAircraftReport.PositionAccuracy);

            writer.WriteNumber("Longitude", standardSearchAndRescueAircraftReport.Longitude);

            writer.WriteNumber("Latitude", standardSearchAndRescueAircraftReport.Latitude);

            writer.WriteNumber("Cog", standardSearchAndRescueAircraftReport.Cog);

            writer.WriteNumber("Timestamp", standardSearchAndRescueAircraftReport.Timestamp);

            writer.WriteBoolean("AltFromBaro", standardSearchAndRescueAircraftReport.AltFromBaro);

            writer.WriteNumber("Spare1", standardSearchAndRescueAircraftReport.Spare1);

            writer.WriteBoolean("Dte", standardSearchAndRescueAircraftReport.Dte);

            writer.WriteNumber("Spare2", standardSearchAndRescueAircraftReport.Spare2);

            writer.WriteBoolean("AssignedMode", standardSearchAndRescueAircraftReport.AssignedMode);

            writer.WriteBoolean("Raim", standardSearchAndRescueAircraftReport.Raim);

            writer.WriteBoolean("CommunicationStateIsItdma", standardSearchAndRescueAircraftReport.CommunicationStateIsItdma);

            writer.WriteNumber("CommunicationState", standardSearchAndRescueAircraftReport.CommunicationState);
        }
    }
}
