// <auto-generated>
/*
 * Ais-Stream WebsocketObjects
 *
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// StaticDataReportReportB
    /// </summary>
    public partial class StaticDataReportReportB : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StaticDataReportReportB" /> class.
        /// </summary>
        /// <param name="valid">valid</param>
        /// <param name="shipType">shipType</param>
        /// <param name="vendorIDName">vendorIDName</param>
        /// <param name="venderIDModel">venderIDModel</param>
        /// <param name="venderIDSerial">venderIDSerial</param>
        /// <param name="callSign">callSign</param>
        /// <param name="dimension">dimension</param>
        /// <param name="fixType">fixType</param>
        /// <param name="spare">spare</param>
        [JsonConstructor]
        public StaticDataReportReportB(bool valid, int shipType, string vendorIDName, int venderIDModel, int venderIDSerial, string callSign, ShipStaticDataDimension dimension, int fixType, int spare)
        {
            Valid = valid;
            ShipType = shipType;
            VendorIDName = vendorIDName;
            VenderIDModel = venderIDModel;
            VenderIDSerial = venderIDSerial;
            CallSign = callSign;
            Dimension = dimension;
            FixType = fixType;
            Spare = spare;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Valid
        /// </summary>
        [JsonPropertyName("Valid")]
        public bool Valid { get; set; }

        /// <summary>
        /// Gets or Sets ShipType
        /// </summary>
        [JsonPropertyName("ShipType")]
        public int ShipType { get; set; }

        /// <summary>
        /// Gets or Sets VendorIDName
        /// </summary>
        [JsonPropertyName("VendorIDName")]
        public string VendorIDName { get; set; }

        /// <summary>
        /// Gets or Sets VenderIDModel
        /// </summary>
        [JsonPropertyName("VenderIDModel")]
        public int VenderIDModel { get; set; }

        /// <summary>
        /// Gets or Sets VenderIDSerial
        /// </summary>
        [JsonPropertyName("VenderIDSerial")]
        public int VenderIDSerial { get; set; }

        /// <summary>
        /// Gets or Sets CallSign
        /// </summary>
        [JsonPropertyName("CallSign")]
        public string CallSign { get; set; }

        /// <summary>
        /// Gets or Sets Dimension
        /// </summary>
        [JsonPropertyName("Dimension")]
        public ShipStaticDataDimension Dimension { get; set; }

        /// <summary>
        /// Gets or Sets FixType
        /// </summary>
        [JsonPropertyName("FixType")]
        public int FixType { get; set; }

        /// <summary>
        /// Gets or Sets Spare
        /// </summary>
        [JsonPropertyName("Spare")]
        public int Spare { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StaticDataReportReportB {\n");
            sb.Append("  Valid: ").Append(Valid).Append("\n");
            sb.Append("  ShipType: ").Append(ShipType).Append("\n");
            sb.Append("  VendorIDName: ").Append(VendorIDName).Append("\n");
            sb.Append("  VenderIDModel: ").Append(VenderIDModel).Append("\n");
            sb.Append("  VenderIDSerial: ").Append(VenderIDSerial).Append("\n");
            sb.Append("  CallSign: ").Append(CallSign).Append("\n");
            sb.Append("  Dimension: ").Append(Dimension).Append("\n");
            sb.Append("  FixType: ").Append(FixType).Append("\n");
            sb.Append("  Spare: ").Append(Spare).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="StaticDataReportReportB" />
    /// </summary>
    public class StaticDataReportReportBJsonConverter : JsonConverter<StaticDataReportReportB>
    {
        /// <summary>
        /// Deserializes json to <see cref="StaticDataReportReportB" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override StaticDataReportReportB Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> valid = default;
            Option<int?> shipType = default;
            Option<string?> vendorIDName = default;
            Option<int?> venderIDModel = default;
            Option<int?> venderIDSerial = default;
            Option<string?> callSign = default;
            Option<ShipStaticDataDimension?> dimension = default;
            Option<int?> fixType = default;
            Option<int?> spare = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "Valid":
                            valid = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "ShipType":
                            shipType = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "VendorIDName":
                            vendorIDName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "VenderIDModel":
                            venderIDModel = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "VenderIDSerial":
                            venderIDSerial = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "CallSign":
                            callSign = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "Dimension":
                            dimension = new Option<ShipStaticDataDimension?>(JsonSerializer.Deserialize<ShipStaticDataDimension>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "FixType":
                            fixType = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "Spare":
                            spare = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!valid.IsSet)
                throw new ArgumentException("Property is required for class StaticDataReportReportB.", nameof(valid));

            if (!shipType.IsSet)
                throw new ArgumentException("Property is required for class StaticDataReportReportB.", nameof(shipType));

            if (!vendorIDName.IsSet)
                throw new ArgumentException("Property is required for class StaticDataReportReportB.", nameof(vendorIDName));

            if (!venderIDModel.IsSet)
                throw new ArgumentException("Property is required for class StaticDataReportReportB.", nameof(venderIDModel));

            if (!venderIDSerial.IsSet)
                throw new ArgumentException("Property is required for class StaticDataReportReportB.", nameof(venderIDSerial));

            if (!callSign.IsSet)
                throw new ArgumentException("Property is required for class StaticDataReportReportB.", nameof(callSign));

            if (!dimension.IsSet)
                throw new ArgumentException("Property is required for class StaticDataReportReportB.", nameof(dimension));

            if (!fixType.IsSet)
                throw new ArgumentException("Property is required for class StaticDataReportReportB.", nameof(fixType));

            if (!spare.IsSet)
                throw new ArgumentException("Property is required for class StaticDataReportReportB.", nameof(spare));

            if (valid.IsSet && valid.Value == null)
                throw new ArgumentNullException(nameof(valid), "Property is not nullable for class StaticDataReportReportB.");

            if (shipType.IsSet && shipType.Value == null)
                throw new ArgumentNullException(nameof(shipType), "Property is not nullable for class StaticDataReportReportB.");

            if (vendorIDName.IsSet && vendorIDName.Value == null)
                throw new ArgumentNullException(nameof(vendorIDName), "Property is not nullable for class StaticDataReportReportB.");

            if (venderIDModel.IsSet && venderIDModel.Value == null)
                throw new ArgumentNullException(nameof(venderIDModel), "Property is not nullable for class StaticDataReportReportB.");

            if (venderIDSerial.IsSet && venderIDSerial.Value == null)
                throw new ArgumentNullException(nameof(venderIDSerial), "Property is not nullable for class StaticDataReportReportB.");

            if (callSign.IsSet && callSign.Value == null)
                throw new ArgumentNullException(nameof(callSign), "Property is not nullable for class StaticDataReportReportB.");

            if (dimension.IsSet && dimension.Value == null)
                throw new ArgumentNullException(nameof(dimension), "Property is not nullable for class StaticDataReportReportB.");

            if (fixType.IsSet && fixType.Value == null)
                throw new ArgumentNullException(nameof(fixType), "Property is not nullable for class StaticDataReportReportB.");

            if (spare.IsSet && spare.Value == null)
                throw new ArgumentNullException(nameof(spare), "Property is not nullable for class StaticDataReportReportB.");

            return new StaticDataReportReportB(valid.Value!.Value!, shipType.Value!.Value!, vendorIDName.Value!, venderIDModel.Value!.Value!, venderIDSerial.Value!.Value!, callSign.Value!, dimension.Value!, fixType.Value!.Value!, spare.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="StaticDataReportReportB" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="staticDataReportReportB"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, StaticDataReportReportB staticDataReportReportB, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, staticDataReportReportB, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="StaticDataReportReportB" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="staticDataReportReportB"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, StaticDataReportReportB staticDataReportReportB, JsonSerializerOptions jsonSerializerOptions)
        {
            if (staticDataReportReportB.VendorIDName == null)
                throw new ArgumentNullException(nameof(staticDataReportReportB.VendorIDName), "Property is required for class StaticDataReportReportB.");

            if (staticDataReportReportB.CallSign == null)
                throw new ArgumentNullException(nameof(staticDataReportReportB.CallSign), "Property is required for class StaticDataReportReportB.");

            if (staticDataReportReportB.Dimension == null)
                throw new ArgumentNullException(nameof(staticDataReportReportB.Dimension), "Property is required for class StaticDataReportReportB.");

            writer.WriteBoolean("Valid", staticDataReportReportB.Valid);

            writer.WriteNumber("ShipType", staticDataReportReportB.ShipType);

            writer.WriteString("VendorIDName", staticDataReportReportB.VendorIDName);

            writer.WriteNumber("VenderIDModel", staticDataReportReportB.VenderIDModel);

            writer.WriteNumber("VenderIDSerial", staticDataReportReportB.VenderIDSerial);

            writer.WriteString("CallSign", staticDataReportReportB.CallSign);

            writer.WritePropertyName("Dimension");
            JsonSerializer.Serialize(writer, staticDataReportReportB.Dimension, jsonSerializerOptions);
            writer.WriteNumber("FixType", staticDataReportReportB.FixType);

            writer.WriteNumber("Spare", staticDataReportReportB.Spare);
        }
    }
}
