// <auto-generated>
/*
 * Ais-Stream WebsocketObjects
 *
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// SubscriptionMessage
    /// </summary>
    public partial class SubscriptionMessage : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SubscriptionMessage" /> class.
        /// </summary>
        /// <param name="aPIKey">aPIKey</param>
        /// <param name="boundingBoxes">boundingBoxes</param>
        /// <param name="filtersShipMMSI">filtersShipMMSI</param>
        /// <param name="filterMessageTypes">filterMessageTypes</param>
        [JsonConstructor]
        public SubscriptionMessage(string aPIKey, List<List<List<double>>> boundingBoxes, Option<List<string>?> filtersShipMMSI = default, Option<List<AisMessageTypes>?> filterMessageTypes = default)
        {
            APIKey = aPIKey;
            BoundingBoxes = boundingBoxes;
            FiltersShipMMSIOption = filtersShipMMSI;
            FilterMessageTypesOption = filterMessageTypes;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets APIKey
        /// </summary>
        [JsonPropertyName("APIKey")]
        public string APIKey { get; set; }

        /// <summary>
        /// Gets or Sets BoundingBoxes
        /// </summary>
        [JsonPropertyName("BoundingBoxes")]
        public List<List<List<double>>> BoundingBoxes { get; set; }

        /// <summary>
        /// Used to track the state of FiltersShipMMSI
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> FiltersShipMMSIOption { get; private set; }

        /// <summary>
        /// Gets or Sets FiltersShipMMSI
        /// </summary>
        [JsonPropertyName("FiltersShipMMSI")]
        public List<string>? FiltersShipMMSI { get { return this.FiltersShipMMSIOption; } set { this.FiltersShipMMSIOption = new(value); } }

        /// <summary>
        /// Used to track the state of FilterMessageTypes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<AisMessageTypes>?> FilterMessageTypesOption { get; private set; }

        /// <summary>
        /// Gets or Sets FilterMessageTypes
        /// </summary>
        [JsonPropertyName("FilterMessageTypes")]
        public List<AisMessageTypes>? FilterMessageTypes { get { return this.FilterMessageTypesOption; } set { this.FilterMessageTypesOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SubscriptionMessage {\n");
            sb.Append("  APIKey: ").Append(APIKey).Append("\n");
            sb.Append("  BoundingBoxes: ").Append(BoundingBoxes).Append("\n");
            sb.Append("  FiltersShipMMSI: ").Append(FiltersShipMMSI).Append("\n");
            sb.Append("  FilterMessageTypes: ").Append(FilterMessageTypes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SubscriptionMessage" />
    /// </summary>
    public class SubscriptionMessageJsonConverter : JsonConverter<SubscriptionMessage>
    {
        /// <summary>
        /// Deserializes json to <see cref="SubscriptionMessage" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SubscriptionMessage Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> aPIKey = default;
            Option<List<List<List<double>>>?> boundingBoxes = default;
            Option<List<string>?> filtersShipMMSI = default;
            Option<List<AisMessageTypes>?> filterMessageTypes = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "APIKey":
                            aPIKey = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "BoundingBoxes":
                            boundingBoxes = new Option<List<List<List<double>>>?>(JsonSerializer.Deserialize<List<List<List<double>>>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "FiltersShipMMSI":
                            filtersShipMMSI = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "FilterMessageTypes":
                            filterMessageTypes = new Option<List<AisMessageTypes>?>(JsonSerializer.Deserialize<List<AisMessageTypes>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!aPIKey.IsSet)
                throw new ArgumentException("Property is required for class SubscriptionMessage.", nameof(aPIKey));

            if (!boundingBoxes.IsSet)
                throw new ArgumentException("Property is required for class SubscriptionMessage.", nameof(boundingBoxes));

            if (aPIKey.IsSet && aPIKey.Value == null)
                throw new ArgumentNullException(nameof(aPIKey), "Property is not nullable for class SubscriptionMessage.");

            if (boundingBoxes.IsSet && boundingBoxes.Value == null)
                throw new ArgumentNullException(nameof(boundingBoxes), "Property is not nullable for class SubscriptionMessage.");

            if (filtersShipMMSI.IsSet && filtersShipMMSI.Value == null)
                throw new ArgumentNullException(nameof(filtersShipMMSI), "Property is not nullable for class SubscriptionMessage.");

            if (filterMessageTypes.IsSet && filterMessageTypes.Value == null)
                throw new ArgumentNullException(nameof(filterMessageTypes), "Property is not nullable for class SubscriptionMessage.");

            return new SubscriptionMessage(aPIKey.Value!, boundingBoxes.Value!, filtersShipMMSI, filterMessageTypes);
        }

        /// <summary>
        /// Serializes a <see cref="SubscriptionMessage" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="subscriptionMessage"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SubscriptionMessage subscriptionMessage, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, subscriptionMessage, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SubscriptionMessage" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="subscriptionMessage"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SubscriptionMessage subscriptionMessage, JsonSerializerOptions jsonSerializerOptions)
        {
            if (subscriptionMessage.APIKey == null)
                throw new ArgumentNullException(nameof(subscriptionMessage.APIKey), "Property is required for class SubscriptionMessage.");

            if (subscriptionMessage.BoundingBoxes == null)
                throw new ArgumentNullException(nameof(subscriptionMessage.BoundingBoxes), "Property is required for class SubscriptionMessage.");

            if (subscriptionMessage.FiltersShipMMSIOption.IsSet && subscriptionMessage.FiltersShipMMSI == null)
                throw new ArgumentNullException(nameof(subscriptionMessage.FiltersShipMMSI), "Property is required for class SubscriptionMessage.");

            if (subscriptionMessage.FilterMessageTypesOption.IsSet && subscriptionMessage.FilterMessageTypes == null)
                throw new ArgumentNullException(nameof(subscriptionMessage.FilterMessageTypes), "Property is required for class SubscriptionMessage.");

            writer.WriteString("APIKey", subscriptionMessage.APIKey);

            writer.WritePropertyName("BoundingBoxes");
            JsonSerializer.Serialize(writer, subscriptionMessage.BoundingBoxes, jsonSerializerOptions);
            if (subscriptionMessage.FiltersShipMMSIOption.IsSet)
            {
                writer.WritePropertyName("FiltersShipMMSI");
                JsonSerializer.Serialize(writer, subscriptionMessage.FiltersShipMMSI, jsonSerializerOptions);
            }
            if (subscriptionMessage.FilterMessageTypesOption.IsSet)
            {
                writer.WritePropertyName("FilterMessageTypes");
                JsonSerializer.Serialize(writer, subscriptionMessage.FilterMessageTypes, jsonSerializerOptions);
            }
        }
    }
}
